### ISSUE TITLE
Table: ширина колонок не работает, как задумано

### ISSUE THREAD

**Issue by andreynovikov** [consta-design-system/uikit#1004]
В документации сказано:

> `width` — ширина колонки в пикселях. Если не укажете, подстроится под ширину данных.

У меня как раз сложная ситуация - две узких колонки и две очень широких. Если ничего не указывать, то сгенерированный код таблицы выглядит так:

```
style="grid-template-columns: 327.5px 327.5px 327.5px 327.5px; --table-width:1310px;"
```

Колонки занимают 4 равные части, узкие колонки выглядят ужасно. И, почему-то, при изменении ширины окна `grid-template-columns` не меняются, хотя `--table-width` меняется.

Когда я устанавливаю ширину для узких колонок, сгенерированный код таблицы выглядит так:

```
style="grid-template-columns: 180px minmax(min-content, 25%) minmax(min-content, 25%) 100px; --table-width:1310px;"
```

В этом случае общая ширина колонок становится меньше ширины таблицы, справа до полосы прокрутки остаётся пустое пространство.

А вот если я вручную через Developer Tools браузера устанавливаю

```
grid-template-columns: minmax(min-content, max-content) minmax(min-content, max-content) minmax(min-content, max-content) minmax(min-content, max-content);
```

что эквивалентно

```
grid-template-columns: auto auto auto auto;
```

всё работает идеально. В чём подвох? Почему нельзя использовать по-умолчанию `auto`?

**Comment by andreynovikov** [comment]
Коллеги, если вы считаете ваше решение правильным, а моё неправильным, то сделайте, _пожалуйста_, хотя бы принудительный пересчёт grid-template-columns отключаемым в свойствах таблицы. А то он срабатывает даже на изменение размера окна, и приходится заниматься полнейшим извращением во всех табличных компонентах:
```
    const mutationCallback = () => {
        table.current.style.setProperty('grid-template-columns', repeatString('auto', columns.length));
    };

    useEffect(() => {
        if (table.current) {
            const observer = new MutationObserver(mutationCallback);
            observer.observe(table.current, {attributes: true, attributeFilter: ['style']});
            return () => observer.disconnect();
        }
    }, []);
```

**Comment by monolithed** [comment]
> По умолчанию таблица растягивается на размер родителя. Но когда я ограничиваю хотя бы одну колонку в размере, все остальные сжимаются по контенту.

![photo_2022-01-25_15-23-11](https://user-images.githubusercontent.com/803674/150976414-4f4df340-36aa-4cb5-a4f9-f7076e5d5a34.jpg)
