### ISSUE TITLE
Tooltip. Добавить в фигму примеры модификаций тултипа по статусу

### ISSUE THREAD

**Issue by MariaLakomkina** [consta-design-system/uikit#1009]
Сейчас в фигме нет информации о возможности добавлять статусы тултипам, а в доке есть. Есть предложение добавить это и в фигму, и прописать какие кнопки могут использоваться в статусных тултипах — кнопки модификаций ghost либо clear
![image](https://user-images.githubusercontent.com/70386016/112974942-b898b880-915b-11eb-862b-601234863e7f.png)
![image](https://user-images.githubusercontent.com/70386016/112975053-df56ef00-915b-11eb-8e86-c83f141c67f8.png)

**Comment by Lyubavskaya** [comment]
Не в варианты, а в примеры

**Comment by hell0anna** [comment]
добавлено https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=77648%3A163900
