### ISSUE TITLE
Tag: Пофиксить наименования слоев в варианте groupN

### ISSUE THREAD

**Issue by MariaLakomkina** [consta-design-system/uikit#1010]
Сейчас у тегов модификации groupN разные названия текстовых слоёв в вариантах, из-за этого когда меняем вариант компонента — текст слетает. Надо сделать все названия текстовых слоёв в этой модификации одинаковыми, в трёх темах. Тогда при смене варианта текст слетать не будет.

https://user-images.githubusercontent.com/70386016/112976184-3610f880-915d-11eb-9e50-bf590d65c28c.mov

![image](https://user-images.githubusercontent.com/70386016/112976120-209bce80-915d-11eb-8f1e-fe6f6d1deea9.png)

**Comment by hell0anna** [comment]
готово https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=11148%3A145952
