### ISSUE TITLE
[3279] ConstaTable: Добавить возможность приклеиваться хедэру к любому скрол контейнеру

### ISSUE THREAD

**Issue by gizeasy** [consta-design-system/uikit#1015]
Сейчас возможно, приклеить шапку только при скроле самой таблицы. Нужно добавить возможность прокидывания элемента, к которому приклеиваться.

**Comment by monolithed** [comment]
По хорошему нужен компонент Sticky

**Comment by kolebayev** [comment]
описать рекомендации использования инфинит скролла, пагинации в общих случаях и при использовании стики шапки

**Comment by gizeasy** [comment]
идея не рабочая
