### ISSUE TITLE
Badge: Доработать документацию

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#1135]
Есть непонимание, что такое Badge, чем отличается от Tag. Доработать документацию (как в Сторибуке, так и в Figma)

**Comment by Lyubavskaya** [comment]
Добавить примеры с текстом

**Comment by arhayka** [comment]
Не поняла, что здесь нужно сделать. Мне кажется, что в описании максимально понятно, чем отличаются бейджик и тег: бейждик нужен для отображения статуса, тег — для группировки объектов. Да?

Если нет, то напишите, что не так.

Если в доке бейджика нужны примеры из реальной жизни, а не из выдуманного мной марсохода, давайте добавим, но мне тогда нужно посмотреть, как его используют в реальных проектах.

**Comment by arhayka** [comment]
Жду инфо от Ильи :)
