### ISSUE TITLE
docs: Дополнить документацию по созданию своего пресета

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#1146]
можно посмотреть пример доки по созданию своего пресета в Vuetify 
плюс описать, что делать, если один и тот же пресет используется в нескольких проектах

**Comment by gizeasy** [comment]
вместе с #825

**Comment by N1MBER** [comment]
Проставить ссылки на конструктор в тех местах, где это необходимо

**Comment by lisaovcharenko** [comment]
@gizeasy посмотри, пожалуйста, актуальна ли задача

**Comment by linturaven** [comment]
@gizeasy посмотри, пожалуйста, актуальна ли задача ещё раз
