### ISSUE TITLE
docs: Создать компоненты на основе Text для типографики

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#1230]
Создать компоненты на основе Text для типографики (заголовки, абзацы, ...)
Чтобы не было разношерстности в проектах - люди хотят использовать рекомендуемые дизайн-системой правила по использованию заголовков, абзацев и т.п.

**Comment by gizeasy** [comment]
Можно взять элементы из MD и все их стилизовать.

**Comment by linturaven** [comment]
https://www.figma.com/file/wNIi9rZl30Uq1IPBJRubsl/Consta-Font-Styles?node-id=0%3A1

Версия для обсуждения.

Из того, что ещё хочется: добавить примеры использования стилей, потюнить настройки шрифтов в разных стилях.

**Comment by kolebayev** [comment]
При

> https://www.figma.com/file/wNIi9rZl30Uq1IPBJRubsl/Consta-Font-Styles?node-id=0%3A1
> 
> Версия для обсуждения.
> 
> Из того, что ещё хочется: добавить примеры использования стилей, потюнить настройки шрифтов в разных стилях.

примеры точно нужны, хотя бы по одному на каждый стиль. если получится закинуть все в один артборд с интерфейсом, будет круто

**Comment by linturaven** [comment]
https://www.figma.com/file/wNIi9rZl30Uq1IPBJRubsl/%F0%9F%94%A5-Consta-Font-Styles?node-id=0%3A1

Добавил примеры связок и вложенности стилей + вводную

**Comment by linturaven** [comment]
Здесь поревьюить/почитать: https://www.figma.com/file/wNIi9rZl30Uq1IPBJRubsl/%F0%9F%94%A5-Consta-Font-Styles?node-id=3%3A8121
