### ISSUE TITLE
User: Увеличить высоту строки

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#1289]
Увеличить расстояние между именем и подписью, чтобы улучшить читаемость. У подписи обрезаются выносные элементы букв.

**Comment by gizeasy** [comment]
сделать после, https://github.com/gazprom-neft/consta-uikit/issues/1258

**Comment by Lyubavskaya** [comment]
Дизайн: https://github.com/gazprom-neft/consta-uikit/issues/927

**Comment by gizeasy** [comment]
![image](https://user-images.githubusercontent.com/13190808/216517411-22ef86aa-5095-4dbf-8264-75b7b3bf8d2e.png)

после изменения шрифта задача перестала быть актуалной
