### ISSUE TITLE
Storybook: Добавить иконки к компонентам на странице Обзор

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#1361]

**Comment by kolebayev** [comment]
[страница в фигме](https://www.figma.com/file/tChkF0Ba2YpGRd9gPNFyzd/Images-ignore?node-id=1206%3A17029), где начинали работу

**Comment by kolebayev** [comment]
https://www.figma.com/file/u4fDZ5rdcEoJUZ7cITlVJx/Github-issues?node-id=1704%3A8685

**Comment by Lyubavskaya** [comment]
- Слайдер
- https://analytic-ui.vercel.app/?path=/story/common-start--page (форма обратной связи)
- https://stats-consta.vercel.app/?path=/story/components-stats--interactive (статы)
