### ISSUE TITLE
Table: Разобраться с _core элементами ячеек

### ISSUE THREAD

**Issue by kolebayev** [consta-design-system/uikit#1392]
не получается поменять элементы core в ячейке таблицы
<img width="883" alt="изображение" src="https://user-images.githubusercontent.com/24884175/127622533-d6b1f96f-45ae-4d4b-aa40-8576d27a0f61.png">

**Comment by hell0anna** [comment]
провели ресеч и поняли, что чтобы исправить нужно перелопатить компоненты и весь подход к сборке таблицы. Эта задача глобальная, нужно обсудить внутри команды и занести в бэклог на следующий супер-спринт.
