### ISSUE TITLE
Skeleton: Добавить неактивное состояние

### ISSUE THREAD

**Issue by monolithed** [consta-design-system/uikit#1409]
Для случаев когда данные не загрузились нужен флаг, который бы явно отключал анимацию (active).

**Comment by gizeasy** [comment]
в таких случаях это решается выводом текста ошибки с кнопкой перезагрузки.

**Comment by monolithed** [comment]
@gizeasy если скелетонов несколько (пример Facebook, VK), а запрос скажем один, то писать что-то в каждом блоке не лучшее решение, а вот остановить анимацию и вывести общей нотификатор — да
