### ISSUE TITLE
Table/storybook: Исправить вычисление ширины колонок при ресайзе таблицы

### ISSUE THREAD

**Issue by eiz5** [consta-design-system/uikit#1458]
**Описание бага**

Если каким-то колонкам ставить ширину по умолчанию, то ресайзить эти колонки можно только один раз и не на ту ширину, которая была необходима.
Также, даже если у всех колонок нет ширины, но у родительского контейнера есть установленная высота, то ширина колонок не рассчитывается в grid-template-column, а устанавливается на все колонки minmax().

**Версия Consta Kit**
3.0.0

https://user-images.githubusercontent.com/36008279/130926420-e68f2f65-5054-4cfd-a45a-88a4d066bc9f.mp4

**Comment by gizeasy** [comment]
@eiz5 Мы пытались повторить проблему, у нас не вышло.
Пришли пожалуйста пропсы с которыми у тебя ломается компонент

**Comment by Lyubavskaya** [comment]
@eiz5 проблема актуальна?
