### ISSUE TITLE
Select: Упростить компонент и доработать документацию

### ISSUE THREAD

**Issue by vlxdklv** [consta-design-system/uikit#1495]
Компонент Select принимает в качестве options массив объектов с типом DefaultItem. 
```
export declare type DefaultItem = {
    label: string;
    id: string | number;
    groupId?: string | number;
    disabled?: boolean;
};
```
Как я понял, в качестве value предлагается использовать проперти "id", который является типом string или number, что в корне не соответствует типу, который я хочу использовать: мое апи ожидает строку, однако в onChange селекта прилетает тип где id соответствует строке или числу. Что нарушает корректную работу тайпскрипта. Таким образом я не могу использовать типы селекта.

Компонент селект в качестве value принимает объект с типом DefaultItem таким образом, чтобы сохранить в state значение конкретного инпута мне нужно в state положить весь объект типа DefaultItem. А перед отправкой значения в мое апи мне нужно его достать из объекта типа DefaultItem, т.е локально данные хранятся в одном формате, а перед отправкой мне нужно преобразовывать их в другой формат, что крайне не удобно. Предлагаю как в качестве value, так и качестве значения прилетающего в onChange использовать id (было бы неплохо переименовать id в value).

пример кода:
```
const options: DefaultItem[] = [
  { id: 1, label: 'Значение один' },
  { id: 2, label: 'Значение два' },
  { id: 3, label: 'Значение три' },
];

const Component = () => {
  const [value, setValue] = useState<DefaultItem | null>(null);
  const onSubmit = () => {
    api.sendForm({
      value: value.id // в этом месте мне необходимо достать id, что очень не удобно!
    })
  }
  return (
    <form>
      <Select
        placeholder='Выберите значение'
        items={options}
        onChange={({ value }) => {
          setValue(value);
        }}
        value={value}
      />
      <button type='button' onClick={onSubmit}>Отправить</button>
    </form>
  );
};
```

**Comment by vlxdklv** [comment]
![image](https://user-images.githubusercontent.com/82217595/131825692-a7ab1b00-5575-4bf2-8a81-dc25af7e2332.png)

**Comment by gizeasy** [comment]
@vlxdklv я тебя понял но вот мапить данные же перед отправкой это норм?
Наше апи позваляет вообще все что угодно ложить в Items, в целом ты можешь мапить в момент рендера и в items только массив id `number[]`. И по этому мы в value передаем ровно то что нам дали в items, так как мы понятия не имеем что там может быть, но по умолчанию ожидаем тип `DefaultItem`

почитай тут `https://consta-uikit.vercel.app/?path=/docs/components-select--playground#%D0%BA%D0%B0%D1%81%D1%82%D0%BE%D0%BC%D0%BD%D1%8B%D0%B9-%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82-%D1%81%D0%BF%D0%B8%D1%81%D0%BA%D0%B0`

**Comment by gizeasy** [comment]
ты можешь описать свой тип item и передать его в компонент, возможно компонент попросит прописать гетеры на те свойства которые не соответствуют свойствам `DefaultItem `

**Comment by VladislavYukhimenko** [comment]
Не понимаю. По дефолту в типах там DefaultItem у которого в качестве value (id) стоит тип number | string | null.
Моя апишка жрет вполне определенный тип string. Соответственно что бы тс позволил мне в функцию запихать value мне нужно его:
1. Достать value (id) из DefaultItem, т.с. определит его как string | number
2. Привести value (id) к типу который нужен апишке (что уже не типобезопасно)   ``` const value = item.id as string; ```
и только после этих манипуляций я могу запихать в мое апи конкретный аргумент


Если идти от кейса где мы задаем функции указывающие то каким образом селект обрабатывает value и label то получается огромный бойлерплейт, дублирующийся от вызова к вызову. 
Я понимаю, что я могу создать свою обертку над селектом и пользоваться ей как мне удобно, но 90% разработчиков до этого не додумается, а ui-kit должен быть максимально понятным конечному пользователю.

**Comment by gizeasy** [comment]
резюмирую:
Компонент ни как не навязывает пользователю какой тип данных использовать, многие не привыкли к такому и хотят иметь конкретный тип. Также в onChange падает весь пользовательский объект, многие привыкли что только id. И Value также многие ждут что туда нужно указать id, у нас это пользовательский объект.

Идея текущего Api такая что мы не навязываем модель данных и пользователь пользуется своей моделью, многие привыкли к тому что имеют 2е модели данных та которая попадает в IU и та которая находится в стейт менеджере.
Компонент же говорит используй одну модель для всего проекта.

Нужно разобрать 2 вопроса:
1) Как поменять доку так чтоб было понятно 
2) Подумать над упращенной версией селекта, которая принимает всегда конкретный тип данных.

**Comment by gizeasy** [comment]
https://github.com/gazprom-neft/consta-uikit/discussions/1687

**Comment by gizeasy** [comment]
Решили в value помимо всего item прокидывать уникальный id элемента 
более строго описать тип DefaultItem

**Comment by Lyubavskaya** [comment]
Решили:
