### ISSUE TITLE
Table: Не отображаются примененные фильтры, если они не влезают в таблицу 

### ISSUE THREAD

**Issue by rim1321** [consta-design-system/uikit#1501]
Добрый день.

Не обрабатывается кейс когда ширина примененных фильтров больше ширины таблицы:
![image](https://user-images.githubusercontent.com/13187096/131970545-0eca557c-738b-4d19-9e99-0bbe21da3cf5.png)

В примере выше не влезло значение фильтра "Центральное" (в конце запятая и отступ), визуально не красиво. Хотелось бы как-то обрабатывать эту ситуацию, например: text-overflow: ellipsis; (или как-то по другому).

**Comment by hell0anna** [comment]
нужно реализовать в коде
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/51019093/164216079-b1c72116-c696-4eee-a37a-4bf586f679c5.png">
