### ISSUE TITLE
[3279] Consta Table: наложение значков фильтрации и сортировки при ресайзе

### ISSUE THREAD

**Issue by znl8** [consta-design-system/uikit#1576]
компонент: Table

Описание бага:
**Значки фильтров и сортировки накладываются на текст( название колонки таблицы)**
![image](https://user-images.githubusercontent.com/90449435/133980321-0fcc5b8d-0686-4b30-b02f-2ed5d47ee5a1.png)
Как воспроизвести баг
1. Указать isResizable, filterable, stickyColumns
![image](https://user-images.githubusercontent.com/90449435/133981064-21e9ac76-0744-492a-94ac-12aa9b8a6eec.png)

2. Изменить ширину колонки на минимальную
![image](https://user-images.githubusercontent.com/90449435/133981258-a0000b69-68bf-439c-9927-fe29e319fff7.png)

3. Применить фильтрацию к любой другой колонке
![image](https://user-images.githubusercontent.com/90449435/133981414-018e08e3-96ba-450d-92b2-18fc2d4cae3a.png)

После применения фильтра, колонка, размер которой был изменен на шаге 2, отрезайзится по ширине, в результате чего значки фильтра и сортировки наложатся на название колонки

**Comment by gizeasy** [comment]
не актуально для новой таблицы
