### ISSUE TITLE
header: Дизайн в Display теме, вынос отдельно

### ISSUE THREAD

**Issue by kolebayev** [consta-design-system/uikit#1593]

**Comment by Lyubavskaya** [comment]
По хорошему надо вынести Header в отдельную библиотеку в Figma и во всех трех темах отрисовать все его компоненты

**Comment by Lyubavskaya** [comment]
И еще нужно показать, как выглядит бургер-меню на десктопе (сейчас показано только для мобил)

**Comment by linturaven** [comment]
Сделал версию в Display Colors, пока не вынес отдельно
https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/?node-id=2411%3A37833

**Comment by linturaven** [comment]
@kolebayev всё вынес и пофиксил баги после переноса в Consta Components
