### ISSUE TITLE
doc: Сделать картинку в мобильный гайд

### ISSUE THREAD

**Issue by kolebayev** [consta-design-system/uikit#1641]
Сделать рендер графики в мобильный гайд по аналогии с вебом. Сорцы запросим у @fooontic

**Comment by fooontic** [comment]
@kolebayev Я же тебе передавал сорцы =)

**Comment by hell0anna** [comment]
готовооооооо
https://www.figma.com/file/PyhBxhkGLnG1kwpXciisKD/%D0%93%D0%B0%D0%B9%D0%B4%D0%BB%D0%B0%D0%B9%D0%BD-%D0%BF%D0%BE-UX%2FUI-%D0%B4%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD%D1%83-MOBILE-APPS?node-id=411%3A7236

**Comment by linturaven** [comment]
Огнище
