### ISSUE TITLE
Вопросы по consta charts

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#1664]
1.	Выбор значений непосредственно в графиках (например, выбор компании или сотрудника). В документации Consta-Charts нет описания способов взаимодействия с чартами. Требуется выяснить, возможно ли "подсвечивать" один из столбцов в графике. Если да, то нам необходим пример кода.
Кейс следующий - необходимо кликнуть на элемент в графике, какая-то callback-функция должна сработать и сохранить выбранное значение в state. После ререндера выбранное значение должно быть каким-то образом выделено относительно других значений в графике путем передачи его в props. Соответственно, при сбросе state столбцы в графике снова должны быть без выделения.
2.	Как в компоненте Consta-Charts "Bar" отрисовать сумму колонок при режиме "stack"? Например, в данном случае это "58".
Также необходимо выводить количество в конце столба, в случае одной колонки:

**Comment by gizeasy** [comment]
Подробная документация со всеми возможностями находится на основном сайте библиотеки

https://g2plot.antv.vision/en/docs/manual/introduction

https://g2plot.antv.vision/en/docs/manual/plots/bar
