### ISSUE TITLE
Combobox: incorrect searchFunction

### ISSUE THREAD

**Issue by enbeznos** [consta-design-system/uikit#1679]
searchFunction при вводе текста поиска срабатывает столько раз сколько записей в контроле.
Как получить только один раз введенный текст в контроле?

**Comment by N1MBER** [comment]
@enbeznos 
Что вы конкретно хотите, колбек на изменения текста в контроле? На данный момент единственный вариант для получения значения в контроле это использование  кастомной функции фильтрации searchFunction.
