### ISSUE TITLE
TextField: Сlick по иконке

### ISSUE THREAD

**Issue by AntonS86** [consta-design-system/uikit#1701]
Наши пользователи, чтобы открыть dropdown часто нажимают на иконку, но календарь не открывается, возможно ли открывать календарь при нажатии на иконку?

![bugdatepickericon](https://user-images.githubusercontent.com/37770694/138423708-889c1e9e-0979-494b-bfb1-9b025f45a762.gif)

**Comment by N1MBER** [comment]
Проблема была исправлена в одном из последних ишью связанных с `TextField`
