### ISSUE TITLE
Portal: Добавить небольшой раздел про контрибьютинг

### ISSUE THREAD

**Issue by kolebayev** [consta-design-system/uikit#1712]
Нужно добавить на лендос раздел про контрибьютинг в фигму и в код, краткий. Будем прощупывать это поле

**Comment by arhayka** [comment]
Договорились, что я напишу, что там будет, а потом ребята уже задизайнят.

**Comment by linturaven** [comment]
https://docs.google.com/document/d/1noqxfYxBaMgBjaa__3MoL53-TMmiaBlcflNb4pDvWPo/edit#
