### ISSUE TITLE
Modal: Проблема с z-index в компоненте

### ISSUE THREAD

**Issue by Rndjester** [consta-design-system/uikit#1761]
Некоторые сторонние библиотеки имеют z-index выше чем z-index overlay.

Неплохо было бы манипулировать z-indexом из вне.

![image](https://user-images.githubusercontent.com/55237393/141472716-ec4bc44e-3e18-43bf-be7c-22967b2ec551.png)

**Comment by gizeasy** [comment]
вы можете манипулировать z-index `Modal` используйте `style={{'z-index': 10}}` или `className`. При вкладывании модалки в модалку или в любой другой `Popover` лучше использовать `style` тогда z-index будет расчитываться от рутового `Popover`.
