### ISSUE TITLE
[3279] Consta Table: Дать возможность вызывать resetSelectedFilters() снаружи компонента

### ISSUE THREAD

**Issue by andreynovikov** [consta-design-system/uikit#1769]
**Описание фичи или улучшения**

У меня есть компонент `EntityList`, содержащий таблицу. Я использую его в нескольких маршрутах с немного различающимся набором данных:

```
<RouteSwitch>
    <Route path='/new/' render={(props) => <EntityList {...props} status={1} />} />
    <Route path='/processing/' render={(props) => <EntityList {...props} status={16} />} />
    <Route path='/finished/' render={(props) => <EntityList {...props} status={65535} />} />
</RouteSwitch>
```

При переходе от одного маршрута к другому компонент переиспользуется, и если у таблицы есть активные фильтры, то они не сбрасываются и применяются к новому набору данных, что в моём случае неправильно. Хочется внутри `EntityList` сделать что-то типа:

```
useEffect(() => {
    entityListTable.current.resetSelectedFilters();
}, [props.status]);
```

но на данный момент это невозможно.

**Comment by gizeasy** [comment]
не актуально для новой таблицы
