### ISSUE TITLE
[3279] Consta Table: Добавить вид Excel

### ISSUE THREAD

**Issue by revidovich** [consta-design-system/uikit#1779]
**Описание фичи или улучшения**
![image](https://user-images.githubusercontent.com/63742797/142201056-7538baa2-179c-41b5-849c-6ab726064c3a.png)

**Реализация предложения**
там наверное можно через ::before или подложку сделать спозиционированную. я может даже сама сделаю, если дадите код компонента

**Comment by andreynovikov** [comment]
Код компонента тут: https://github.com/gazprom-neft/consta-uikit/blob/dev/src/components/Table/Table.tsx

**Comment by revidovich** [comment]
типа такого:
.Table {
  counter-reset: rowNumber;
}

.Table div::before {
  counter-increment: rowNumber;
}

.Table .TableHeader-Row .TableCell:first-child::before {
  content: counter(rowNumber);
}
но у меня нумерация с двойки и не стилизуется почему-то..

**Comment by revidovich** [comment]
Заглушка с ошибкой...
 
![image](https://user-images.githubusercontent.com/63742797/144594819-690001a7-6c56-420f-8f77-3016416f3a58.png)

**Comment by lisaovcharenko** [comment]
@linturaven @gizeasy нужно обсудить, будем ли учитывать в новой таблице. привязала к эпику
