### ISSUE TITLE
[3279] Consta Table: TableTextFilter с "withSearch: true"

### ISSUE THREAD

**Issue by Nikita7795** [consta-design-system/uikit#1782]
1.Открыть фильтрацию
<img width="426" alt="Снимок экрана 2021-11-17 в 16 23 05" src="https://user-images.githubusercontent.com/69715667/142208870-c3f99fc3-ea09-437b-9b05-99c5f592161d.png">

2.Ввести что нибудь в поиск
<img width="430" alt="Снимок экрана 2021-11-17 в 16 24 49" src="https://user-images.githubusercontent.com/69715667/142209105-c6d2e12e-d8a3-41b4-baf2-b26220c45a8e.png">

3. Нажать кнопку применить
4. В итоге фильтр сработает на все значение, а не только на найденные в поиске

<img width="801" alt="Снимок экрана 2021-11-17 в 16 28 03" src="https://user-images.githubusercontent.com/69715667/142209583-67ae24e2-dd4c-4b7a-abca-c99f1e5f80ab.png">

**Comment by gizeasy** [comment]
Неактуально для новой таблицы
