### ISSUE TITLE
MultiCombobox: обернуть компоненты в варианты

### ISSUE THREAD

**Issue by hell0anna** [consta-design-system/uikit#1790]
**Описание фичи или улучшения**
Нужно продублировать страницу, текущий макет убрать в Deprecated с заборчиком. В новой странице обернуть компоненты в варианты и сделать пометку Variants в названии. 

**Почему улучшение или фича необходима?**
Для удобства использования компонента

**Comment by Lyubavskaya** [comment]
дубль https://github.com/consta-design-system/uikit/issues/1974
