### ISSUE TITLE
MultiAxis: Добавить график в Consta Charts

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#1801]
Добавить пример

**Comment by gizeasy** [comment]
Если такое можно сделать с каждым графиком то сделать пример

**Comment by N1MBER** [comment]
Еще раз пересмотрел, примеров с количеством ординат > 2  не нашлось, попытался потыкать и сделать это руками, но он не отрисовывает дополнительные ординаты, так что судя по всему этого сделать нельзя (может быть дело в прослойке под реакт)
