### ISSUE TITLE
Theme: Обновить доку по пресетам

### ISSUE THREAD

**Issue by kolebayev** [consta-design-system/uikit#1804]
Описать, что пресеты рассчитываются на проекте самостоятельно
Поднял #825

**Comment by kolebayev** [comment]
не получилось пр сделать, напишите мне, когда кто-то возьмет задачу в работу

**Comment by Lyubavskaya** [comment]
Дополнить про подбор цветов и рекомендуемый порядок работы с темой в коде и в фигме

**Comment by arhayka** [comment]
Распросить Лешу о том, как создать свою тему в фигме, описать весь процесс.
