### ISSUE TITLE
Добавить возможность открытия контексного меню по правому клику по таблице

### ISSUE THREAD

**Issue by SergeyKatugin** [consta-design-system/uikit#1806]
**Описание фичи или улучшения**
На данный момент таблице не хватает контексного меню по правому клику.
Нужно что бы при клике правой клавишей по ячейке открывалась ContextMenu.
В котором мы бы могли отлавливать клики и добавлять опции.

Необходимо добавить пропс в таблицу, который принимает метод, в аргумент возвращает ячейку(или undefined для шапки) и ref. И возвращаем в метода ReactNode

```jsx
<Table onContextMenuClick={(row: Row | undefined, ref: Ref) => ...} />
```

Далее в проекте объявляем ContextMenu, или что нужно. И в зависимости от ячейки строим items и устанавливаем ref.

Сделаем сами

**Почему улучшение или фича необходима?**
Для управление контентом таблицы необходимо добавление данного функционала.

**Реализация предложения**
Описано выше

**Comment by gizeasy** [comment]
Кажется в названии пропса не стоит упомянать "контекст меню" так как по факту все что угодно может быть.

Ещё стоит в чтобы функция возвращала евент клика.

И давай ещё Возвращать объект, в котором ячейка, рефка и евент.

**Comment by SergeyKatugin** [comment]
Примерно так:

```tsx
type CellClick<T> = {
  e: React.MouseEvent,
  row: Row<T>,
  ref: Ref<T>,
}
<Table onCellClick={({ e, row, ref }) => ...} />
```

**Comment by SergeyKatugin** [comment]
Далее там уже пользователь сам отследит клик и сделает то, что считает нужным

**Comment by SergeyKatugin** [comment]
Нужно тогда будет разделять клик по шапке и по ячейке

**Comment by SergeyKatugin** [comment]
PR https://github.com/consta-design-system/uikit/pull/1983
Не могу привязать сам
