### ISSUE TITLE
Добавить decimal для колонок таблицы

### ISSUE THREAD

**Issue by SergeyKatugin** [consta-design-system/uikit#1809]
**Описание**
На данный момент не хватает свойства decimal, которое бы указывало количесто знаков после запятой.
В текущей реализации приходится обновлять данные и хранить value/formatted value у себя.
Хотелось бы что бы конкретная колонка в таблицу умела принимать количество знаков после запятой и не делать магию с обновлением данных.

**Реализация предложения**
Добавить в column новое свойство - `decimal`
Которое говорит о том, сколько знаков после запятой пользователь хочет видеть.
Свойство опциональное, если не передаем - то выводим `as is`
Если передаем, в месте рендера ячейки добавляем `toFixed(decimal)`
Нужна работа в динамике.

**Дополнительная информация**
Удобно будет сочетаться с задачей https://github.com/gazprom-neft/consta-uikit/issues/1806
В которой пользователь добавит правый клик по заголовку и там в contextMenu будет "увеличить разрядность" / "уменьшить"

**Comment by andreynovikov** [comment]
А чем `renderCell` не устраивает?

**Comment by SergeyKatugin** [comment]
Приходится каждый раз данные обновлять нам полностью, что вызывает рендер таблицы.

Получается нам нужно обновить данные конкретной колонки и потом только в render cell на основе decimal колонки указать количество знаков после запятой

**Comment by gizeasy** [comment]
Очень редкий кейс. 
В renderCell можете положить компонент который через контекст будет принимать параметр `decimal` и когда он измениться то вся таблица не будет ререндорится а будут только ячейки.
