### ISSUE TITLE
[3279] Consta Table: Стиль хедера таблицы с зафиксированным заголовком в темном оформлении при скролле

### ISSUE THREAD

**Issue by hidmitry** [consta-design-system/uikit#1832]
В дизайн библиотеке в темном оформлении таблицы при скролле зафиксированный хедер выглядит так:

<img width="1195" alt="Screenshot 2021-11-29 at 19 57 32" src="https://user-images.githubusercontent.com/95356759/145052260-a2ea9325-17af-4345-86a9-13290136fa72.png">
[Ссылка](https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=5141%3A74365)

А в библиотеке компонентов так:

<img width="664" alt="Screenshot 2021-11-29 at 19 58 07" src="https://user-images.githubusercontent.com/95356759/145052333-a23aba51-47ca-496a-a68d-8b532ebea438.png">
[Ссылка](https://consta-uikit.vercel.app/?path=/story/components-table--with-sticky-header)

Вариант в дизайн библиотеке выглядит более оправданным

**Comment by gizeasy** [comment]
Не актуально для новой таблице
