### ISSUE TITLE
[3279] Consta Table: Добавить возможность управлять текущим состоянием фильтров

### ISSUE THREAD

**Issue by AntonS86** [consta-design-system/uikit#1836]
В нашем приложении вся фильтрация и сортировка происходит на сервере, хотелось бы инструкцию, как получить выбранные фильтры, для дальнейшей передачи на сервер

![image](https://user-images.githubusercontent.com/37770694/145182523-4ef34a99-a33b-4c1b-945f-4488c6b310c6.png)
_____________________
подписаться можно на onFiltersUpdated, но как установить выбранные фильтры?
----------------------
В общем нужна полная интеграция с внешним управлением фильтров и сортировки, с установкой текущих фильтров и сортировки, на всех последних проектах вся фильтрация и сортировка происходит на бэке что делает фильтры бесполезными

**Comment by andreynovikov** [comment]
А в чём проблема? Объявляем:
```
const [currentFilters, setCurrentFilters] = useState(undefined);
```
Далее пишем:
```
    const onFiltersUpdated = (filters) => {
        if (filters) {
            const newFilters = [];
            for (var field in filters) {
                // тут ваша логика обработки фильтров
                // в простейшем случае
                const filter = filters[field];
                if (filter.value !== undefined)
                        newFilters.push({field: field, value: filter.value});
                // но это не всегда так
            }
            setCurrentFilters(newFilters);
        } else {
            setCurrentFilters(undefined);
        }
    };
```
И подключаем в таблице:
```
            <Table
                ...
                onFiltersUpdated={onFiltersUpdated} />
```
Ну а уж как передать фильтры на сервер, вы должны знать. Да и в принципе это сильно зависит от бэкенда. Очевидно, что представления фильтров на клиенте и сервере не совпадут (особенно, если это поиск по нескольким значениям или с масками), поэтому надо будет решить, где их преобразовывать - на клиенте или на сервере. Я это делаю на клиенте, чтобы не вмешиваться в серверное API.

**Comment by AntonS86** [comment]
проблема установить фильтры из вне, допусти текущие фильтры сохранены в урле или локалстор, при заходе на страницу я хочу чтобы они отображались в окне с фильтрами, сейчас же у меня нет такой возможности, так же я хочу снять их при определенном действии пользователя, мне приходится искать плашку в дом и кликать по ней

**Comment by andreynovikov** [comment]
А, ну такого да, нет. Просто Вы начали с "как получить выбранные фильтры, для дальнейшей передачи на сервер".

Тогда я бы сформулировал задачу как: **Добавить возможность управлять текущим состоянием фильтров**. Поддержу этот FR, так как и я бы хотел иметь возможность задавать начальные фильтры через URI.

Кстати, я уже просил иметь возможность программно отключить все фильтры: https://github.com/gazprom-neft/consta-uikit/issues/1769

**Comment by AntonS86** [comment]
и еще сделать функцию filterer не обязательную, если ее нет, то не фильтровать, вообщем нужна фича на полное управление фильтрами и сортировкой из вне компонента таблицей

**Comment by andreynovikov** [comment]
Ну, да, а то сейчас во всех фильтрах приходится писать `filterer: (cellValue, filterValue) => { return true; }`, что тупо.

**Comment by gizeasy** [comment]
в новой таблице управление фильтрами идет на стороне проекта.
