### ISSUE TITLE
[3279] Consta Table: Непродуманная система фильтров

### ISSUE THREAD

**Issue by andreynovikov** [consta-design-system/uikit#1842]
Нет чёткого определения, когда считать фильтр заданным, а когда нет. Это в основном надо для непротиворечивого UI и UX, но и логику `onFiltersUpdated` упростило бы.

_Пример первый:_

Обычный поиск по подстроке, типа [данного компонента](https://github.com/gazprom-neft/consta-uikit/issues/1719#issue-1039482068), если пользователь ничего не вводит и нажимает _Применить_, возвращается `undefined`. Это логично, и у вас в одном из примеров фильтрации есть проверка на `isNotNil`. Но, таблица всё равно считает такой фильтр активным и отображает его в плашке с текущими фильтрами, хотя реально никакой фильтрации не происходит.

_Пример второй:_

Ваш компонент `TableTextFilter` - всё хорошо до тех пор, пока пользователь не (а) выберет все варианты - тогда реальной фильтрации нет, (б) сбросит все варианты, тогда вообще ничего не покажется, а в плашке с текущими фильтрами будет имя фильтра с пустым значением.

**Что я предлагаю:**

1. Выработать единый подход, когда таблица будет считать, что фильтр задан или нет. Например, считать `filterValue` равным `undefined` отсутствием фильтра. Или в `onConfirm` добавить второй параметр. Или считать, что если `getTagLabel` вернул `undefined`, то данный фильтр не задан.
2. Сделать ваши компоненты настраиваемыми в этом контексте. Я могу допустить, что когда-нибудь пустой массив в `TableTextFilter` может иметь смысл, но это очень извращённый случай. Могу предложить добавить в свойства колбэк `isFilterDefined` или перечисление типа `'unset': ['all', 'none']`.

**Comment by gizeasy** [comment]
Для новой таблице не актуально, логика фильтрации лежит вне таблицы
