### ISSUE TITLE
useGlobalKeys: запретить передачу события?

### ISSUE THREAD

**Issue by andreynovikov** [consta-design-system/uikit#1847]
У меня есть `Sidebar`, из которого можно открыть `Modal`, из которого можно открыть другой `Modal` и т.д. Проблема в том, что когда нажимаешь `Esc`, закрывается вся цепочка окон, в том числе и `Sidebar`, а хочется, чтобы закрывалось только одно верхнее окно за раз. Не могу придумать, как это сделать.

**Comment by Lyubavskaya** [comment]
@andreynovikov Cамым хорошим способом будет завязаться на ваш роутинг в проекте, тогда все всплывающие окна будут иметь историю и будут закрываться последовательно в обратном порядке. Также по ссылке будет восстанавливаться состояние модалок. Тогда в onESC можно будет добавить функцию проверки, на каком роуте мы находимся, и закрывать ту или иную модалку. 
Или второй вариант: создать общее состояние стека модалок и закрывать их по очереди.

**Comment by andreynovikov** [comment]
@Lyubavskaya да, я так бы и сделал, если бы сам обрабатывал `Esc`, но его же обрабатывают компоненты и они все дружно ловят это событие. Как мне туда вмешаться?

**Comment by gizeasy** [comment]
в доку добавить пример

**Comment by linturaven** [comment]
Пример добавлен
