### ISSUE TITLE
[3279] Consta Table: Расширить возможности таблицы

### ISSUE THREAD

**Issue by AntonS86** [consta-design-system/uikit#1851]
Проблема рендера вложенных данных.
Предлагаю передавать в accesor точечную нотацию или функцию геттер как в лодаш https://lodash.com/docs/4.17.15#get
мерджить два объекта не вариант, имена полей одинаковые и их может быть очень много,
так же снять ограничение на уникальность accesor, для сортировки так же использовать точечную нотацию или функцию
```ts
const users= [
  phone: '234',
  name: 'Alex',
  company: {
    name: 'Name',
    phone: '343'
  }
]

const columns = [
  {
    title: 'Имя компании',
    accessor: 'company.name',
  },
  {
    {
     title: 'Телефон компании',
     accessor: (row) => row.company.phone,
   },
  }
]
```

**Comment by Lyubavskaya** [comment]
@gizeasy Оценить риски

**Comment by gizeasy** [comment]
Задача не актуальная. В новой таблице всегда нужно указывать `accessor` но не обязательно таблица будет брать данные по этому ключу, можно указать renderDataCell в которую на вход прилетит объект row.

```
const columns = [
  {
    title: 'Имя компании',
    accessor: 'company.name',
    renderDataCell: (row) => row.name,
  },
  {
    {
     title: 'Телефон компании',
     accessor: 'company.phone',
     renderDataCell: (row) => row.company.name,
   },
  }
]
```
