### ISSUE TITLE
DataPicker: Добавить примеры с кастомными кнопками из DateTime в DatePicker

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#1874]

**Comment by gizeasy** [comment]
+ убрать кнопку "Эта неделя"

**Comment by hell0anna** [comment]
добавила варинты с двумя размерами кнопок ¯\_(ツ)_/¯ https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=11302%3A2
