### ISSUE TITLE
Gant: Стилизация под Consta

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#1877]
1. Выбрать библиотеку
2. Подготовить дизайн
3. Сделать адаптер

**Comment by Lyubavskaya** [comment]
https://matematuk.github.io/gantt-task-react/
Тут код https://github.com/MaTeMaTuK/gantt-task-react

**Comment by Lyubavskaya** [comment]
из открытых решений можно посмотреть https://github.com/IBM/gantt-chart от IBM

**Comment by Lyubavskaya** [comment]
Из коммерческих с возможностью редактирования https://www.react-gantt.com

**Comment by N1MBER** [comment]
Я склоняюсь больше к https://matematuk.github.io/gantt-task-react/, так как это бесплатное решение, а также тут на мой взгляд более понятная документация чем у IBM
