### ISSUE TITLE
Charts: Стилизовать легенду при большом количестве параметров

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#1884]
Показать на графиках, где может располагаться легенда и как она может выглядеть (кружки/линии).
Показать, как будет выглядеть легенда, если параметров (линий разных цветов) на графике много. 
Учесть возможности G2Plot

**Comment by linturaven** [comment]
https://www.figma.com/file/lQJPpOcbtlRk18YSyb6inq/Consta-Charts?node-id=3680%3A10824

**Comment by Lyubavskaya** [comment]
Стилизовать легенду в таком виде не получится, так как в  g2plot очень узкий спектр стилизации, максимум что мы можем изменить: цвет стрелочек, прозрачность стрелочек и их размер. Я предлагаю как минимум просто заменить цвета и размеры на констовские.

**Comment by hell0anna** [comment]
новый вариант туть 
https://www.figma.com/file/lQJPpOcbtlRk18YSyb6inq/Consta-Charts?node-id=3680%3A10824

**Comment by gizeasy** [comment]
https://github.com/consta-design-system/charts/pull/49
