### ISSUE TITLE
SnackBar утечка памяти при закрытии

### ISSUE THREAD

**Issue by AntonS86** [consta-design-system/uikit#1891]
![image](https://user-images.githubusercontent.com/37770694/147582804-b6dce786-1191-416e-89b7-ae36a54b9b82.png)

**Comment by gizeasy** [comment]
на проекте тоже? просто конкретно в сторибуке, реакт может подумать так, но по факту там нет утечки. Но все равно поправим код чтоб варнинга не было.

**Comment by AntonS86** [comment]
> на проекте тоже?

да на проекте и заметили, проверил в сторебуке такая же проблема
