### ISSUE TITLE
storybook: Логотип для новых библиотек

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#1897]
Логотипы нужны еще для этих библиотек:
https://gpn-responses.vercel.app/?path=/story/components-responses--playground
https://consta-tree.vercel.app/?path=/story/components-tree--playground (adapters)
https://consta-table.vercel.app/?path=/story/components-table--playground (adapters)

Логотипы здесь: https://www.figma.com/file/tChkF0Ba2YpGRd9gPNFyzd/Images-%5Bignore%5D?node-id=1628%3A22149

**Comment by hell0anna** [comment]
лежат тут https://www.figma.com/file/tChkF0Ba2YpGRd9gPNFyzd/Images-%5Bignore%5D?node-id=806%3A0
