### ISSUE TITLE
Adapters: финальные правки

### ISSUE THREAD

**Issue by gizeasy** [consta-design-system/uikit#1902]
1) актулизировать readme.md rcTreeAdapter (Макс, Аня)
2) исправить сылку на rcTableAdapter в vercel и документации (Андрей)
3) В rcTreeAdapter написать варианты использования (Аня)
4) В rcTreeAdapter изменить названия адаптера и миксина с маленькой буквы (Аня)
5) логотип Consta Adapters (Макс)
6) Финальная проверка (Андрей)

**Comment by arhayka** [comment]
3,4 — готово
