### ISSUE TITLE
ContextMenu: Цвет текста в disabled items

### ISSUE THREAD

**Issue by levi2015mik** [consta-design-system/uikit#1924]
Если в контекстном меню присутствуют неактивные пункты указанные при помощи getDisabled, в ранних версиях они consta цвет их текста был более бледным, сейчас они черные, как по дефолту.
Проблема касается только стиля. Неактивные пункты меню на клик не реагируют, что корректно.
Я сейчас использую версию 2.2.1
Там тоже применяется функция getDisabled. Меню выглядит так https://ibb.co/frcsyRJ
В новой версии, 3.12.3 оно же выглядит так https://ibb.co/SN4N0k6
В стилях класс .ContextMenuItem_disabled отвечающий за бледный цвет перекрывается стилем из .Text_view_primary
https://ibb.co/YW0XRbH
https://ibb.co/4WcGYGy
Проблема была уже описана здесь, но закрыта без изучения https://github.com/gazprom-neft/consta-uikit/issues/1899

**Comment by N1MBER** [comment]
@levi2015mik Можете пожалуйста скинуть пример кода, в котором это возникает
