### ISSUE TITLE
MixAnimationPopover: Создать миксин анимации на поповер

### ISSUE THREAD

**Issue by gizeasy** [consta-design-system/uikit#1928]
- [x] он уже готов можно взять с `@consta/header`
- [ ] и применить ее ко всем поповерам где уже есть анимация, подумать над тем где еще добавить и добавить

**Comment by Lyubavskaya** [comment]
Осталось: применить ее ко всем поповерам где уже есть анимация, подумать над тем где еще добавить и добавить
