### ISSUE TITLE
docs: Быстрый старт для дизайнеров

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#1939]
Куда идти смотреть про цвета, отступы, графики, Сторибук и т.п. + примеры из Best Practices.
Добавить ссылку на Быстрый старт в Figma Community!!!

**Comment by linturaven** [comment]
[Структура[](url)](url
[Быстрый старт для дизайнера.pdf](https://github.com/consta-design-system/uikit/files/8425930/default.pdf)
)

**Comment by linturaven** [comment]
Структура блока с библиотекой:
**Название библиотеки**
Короткое описание
Ссылка-кнопка на библиотеку
Ссылка-кнопка на документацию (если есть)

Сноска с доп.информацией, которая не на поверхности и важна к упоминанию в связке с библиотекой.

**Comment by linturaven** [comment]
Можно смотреть:
https://www.figma.com/file/nClGhdshMEeQdqsBKncwJ0/%F0%9F%94%A5-Consta-%E2%80%93-%D0%91%D1%8B%D1%81%D1%82%D1%80%D1%8B%D0%B9-%D1%81%D1%82%D0%B0%D1%80%D1%82-%D0%B4%D0%BB%D1%8F-%D0%B4%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD%D0%B5%D1%80%D0%BE%D0%B2?node-id=86%3A34204
