### ISSUE TITLE
Figma: Примеры интерфейсов | сделать адаптив

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#1940]
Хочется больше примеров использования, примеров интерфейсов. Чтобы новичкам дизайнерам подсматривать и ориентироваться на них.
Добавить примеры в Best Practices (конкурсные + какой-нибудь свой показательный (адаптив, как мы отрисовываем макеты в разных разрешениях))
Потом их же реализуем в коде в качестве интерактивных примеров на портале.

**Comment by hell0anna** [comment]
https://www.figma.com/file/uRzmjwbrXR8sR3OwvR07zm/%D0%9F%D1%80%D0%B8%D0%BC%D0%B5%D1%80%D1%8B-%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D1%84%D0%B5%D0%B9%D1%81%D0%BE%D0%B2-%7C-Consta?node-id=53%3A2330

**Comment by hell0anna** [comment]
добавить адаптив 
- мобильный 
- планшет 
для примеров банк и букинг

**Comment by hell0anna** [comment]
https://www.figma.com/file/l6rdF0guIdH3ZDXSoehuqz/Consta-UI-Kit%3A-Best-Practices?node-id=1314%3A14093
