### ISSUE TITLE
BadgeGroup: Перенести в основную библиотеку

### ISSUE THREAD

**Issue by gizeasy** [consta-design-system/uikit#1941]
в `@consta/header` есть `Badges` компонент кажется полезным не толко там можно его вынести в основную библиотеку

**Comment by hell0anna** [comment]
https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=235%3A37206&t=Nt43LXAfKTcxrwUe-1
