### ISSUE TITLE
Figma: Компоненты на variants

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#1942]
Посмотреть, какие еще компоненты стоит переделать на variants.
Результат - созданы ишью по каждому компоненту, который необходимо переделать на variants.

**Comment by hell0anna** [comment]
списочек с комментариями 
https://docs.google.com/spreadsheets/d/1ni0R8p4ArrssuADlrnNH8LFWoXaHRJ7ddE-rZB046I4/edit#gid=0

Attachment https://github.com/consta-design-system/uikit/issues/1972
Drag'n'DropField https://github.com/consta-design-system/uikit/issues/1973
MultiCombobox https://github.com/consta-design-system/uikit/issues/1974
Table https://github.com/consta-design-system/uikit/issues/1975
Tooltip https://github.com/consta-design-system/uikit/issues/1976
UserSelect https://github.com/consta-design-system/uikit/issues/1977
