### ISSUE TITLE
Figma: Сложно найти нужный компонент в списке 

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#1943]
Компоненты завязаны на темах, компонентов много - приходится ковыряться в структуре в фигме. 
неудобно в ассетах несколько библиотек конста
Разрастается список ассетов (библиотек) - тяжело с этим работать, найти нужный компонент сложно.

Подумать, что можно сделать, чтобы список был не таким большим и запутанным.

**Comment by Lyubavskaya** [comment]
По итогам опроса: компоненты из разных тем имеют одинаковое название, вследствие через ассеты их вытягивать неудобно

**Comment by linturaven** [comment]
Изучили вопрос.

**Самое трудное - пользоваться поиском в инспекторе компонентов: при поиске по запросу "Button", например, пользователю в результатах выпадает кнопка и непонятно, какая к какой теме относится.**

_Этот вопрос решается добавлением описания к компонентам - по хаверу на компонент в поиске отображается описание, можно стартовать описание с обозначения темы._

**Вторая явная проблема - для сложных компонентов из библиотеки "Components" в инспекторе, например, у header выпадает вся портянка хедеров и их составных частей, по которой сложно ориентироваться.**

_Этот вопрос решается регламентированием названий у слоёв. Решение есть в компонентах Calendar и MegaMenu._ 

Итого для решения проблемы можно:
— Добавить тип темы в описание компонента
— Поработать над иерархией и вложенностью слоёв в Consta Components и изучить такую же возможность в UI-Kit

Если фидбек будет сохраняться, то можно подумать над разделением библиотек, но. этот вариант не самый практичный и очень трудоемкий, но справедливости ради, такой опыт в других компаниях есть.
