### ISSUE TITLE
docs: Текст, для каких проектов подходит Consta

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#1946]
Принципы? Для чего Consta? Что важно? Какими ГПН хочет видеть свои интерфейсы? Было бы проще пользоваться. Нравится, как описано это в Carbon, UK-gov. Важно показать примеры - иллюстрации принципов.

**Comment by gizeasy** [comment]
https://github.com/consta-design-system/uikit/pull/2104
