### ISSUE TITLE
docs: Описать подробно, как работать с цветами

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#1948]
Как вводить новые цвета? 
Категориальная цветовая палитра - по какому принципу они должны вводиться? 
Можно ли использовать другие цвета? Корпоративные цвета - это важно? Можно ли всё раскрасить зеленым?
Обзор и руководство про то, как пользоваться цветами. Сейчас дизайнеры часто берут компонент не оттуда. Как-то упростить работу.

**Comment by gizeasy** [comment]
делать в месте #825

**Comment by lisaovcharenko** [comment]
Делаем в рамках #2614
