### ISSUE TITLE
Attachment: Не работает сужение или растягивание

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#1955]
Аттач - сужать или растягивать - он не работает. Автолэйаут неправильно настроен, приходится ломать компонент

Исправлять нужно в Attach (Deprecated)

**Comment by errorry** [comment]
Исправлено: заполнение контейнера по ширине компонента Attach (Deprecated)
Доп: В компоненте Attachment добавлен отступ 4пх между текстом
