### ISSUE TITLE
Charts: Подход к отрисовке графиков

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#1958]
Посмотреть графики от Идриса, обсудить

**Comment by linturaven** [comment]
Подход к разработке компонентов графиков

Каждый элемент графика – отдельный мини компонент. Получаем некий конструктор графиков:
– сетка
– легенда
– иная обвязка
- объект визуализирующий данные

Основа каждого графика – сетка. Делаем её гибконастраиваемой:
Оси X и Y:
– настройка количества направляющих/делений (в разумных пределах)
– настройка отображения направляющих по оси
– настройка стиля направляющих
– учесть вопрос масштабирования сетки

Визуализация данных:
– показываем в качестве примера, как можно визуализировать данные по каждому типу графиков
– основа одна и та же – сетка

Из получившихся компонентов можем собирать любой интересующий график, преимущество – не нужно детачить весь график целиком, как сейчас. Сетка и обвязка остаются нетронутыми, пользователь кастомит только визуализацию данных.

https://www.figma.com/file/2dRWBLcHeX3kPne7gSTF59/ComponentChart-(Copy)?node-id=0%3A1
Наброски Идриса
