### ISSUE TITLE
Charts: Добавить масштабирующий ползунок на графиках

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#1959]
Когда тянешь за края ползунка, и масштаб графика меняется
Особенно для Line и Area актуально
В G2plot он есть

**Comment by N1MBER** [comment]
https://g2plot.antv.vision/zh/docs/api/components/slider#gatsby-focus-wrapper , тут прям с указателями все расписано, по факту стилизовать можно в слайдере почти все

**Comment by hell0anna** [comment]
компоненты Line Example Slider
 https://www.figma.com/file/lQJPpOcbtlRk18YSyb6inq/Consta-Charts?node-id=3766%3A10914
пример использования https://www.figma.com/file/lQJPpOcbtlRk18YSyb6inq/Consta-Charts?node-id=3680%3A10824

если есть возможность менять высоту самой шкалы, давайте сделаем 20px (как в макете)

**Comment by gizeasy** [comment]
https://github.com/consta-design-system/charts/pull/48
