### ISSUE TITLE
Drag'n'DropField: завернуть компоненты в вариант

### ISSUE THREAD

**Issue by hell0anna** [consta-design-system/uikit#1973]
добавить в вариант другие состояния компонента (подумать какие нужны, например ховер не надо, а когда что-то добавлено -- надо)
https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=32774%3A0

**Comment by nixolympica** [comment]
Надо, наверное пересмотреть задачу, всё уже в вариантах, стейты тоже присутствуют.

**Comment by Lyubavskaya** [comment]
Что имелось ввиду?
