### ISSUE TITLE
MultiCombobox: завернуть компоненты в вариант

### ISSUE THREAD

**Issue by hell0anna** [consta-design-system/uikit#1974]
**Тут нужно подумать**
возможно занести селекст с крестиком в вариант 
и возможно занести в варианты MultiComboboxList и/или MultiComboboxListItem
https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=367%3A0

**Comment by Lyubavskaya** [comment]
Описание фичи или улучшения
Нужно продублировать страницу, текущий макет убрать в Deprecated с заборчиком. В новой странице обернуть компоненты в варианты и сделать пометку Variants в названии.

Почему улучшение или фича необходима?
Для удобства использования компонента
