### ISSUE TITLE
Ag-grid-adapter: Ячейка шапки, теги

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#2010]

**Comment by Ilyashis** [comment]
https://www.figma.com/file/LKYyjgQ3khFHvXraZAG1n1/Consta-Components?node-id=404%3A29189

**Comment by Ilyashis** [comment]
https://www.figma.com/file/LKYyjgQ3khFHvXraZAG1n1/Consta-Components?node-id=404%3A29189
