### ISSUE TITLE
AutoComplite: создать компонент

### ISSUE THREAD

**Issue by gizeasy** [consta-design-system/uikit#2016]
арибут list для автокомплита, проверить и создать пример

**Comment by hell0anna** [comment]
на ревью
https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=96814%3A196231

**Comment by hell0anna** [comment]
Заменила AutoCompleteList на инстант List/Modules/AutoCompleteList
