### ISSUE TITLE
ContextMenu: Проблема с ворнингом на компоненты с выпадающим контекстном меню

### ISSUE THREAD

**Issue by imurion** [consta-design-system/uikit#2034]
**Описание бага**
<img width="1438" alt="w12" src="https://user-images.githubusercontent.com/98826457/152812492-27004a41-4dca-4188-bf14-3fcf312844fd.png">

**Как воспроизвести баг** (опционально)  
При открытии выпадающего меню, в консоле всплывает ворнинг. (скрин выше)

**Версия Consta Kit**
        "@consta/uikit": "3.13.0",

**Параметры софта на компьютере:**

- ОС:
- MacOS Monterey
- MacBook Pro (13-inch, M1, 2020)
- Браузер и его версия:
- Google Chrome Версия 97.0.4692.99

**Дополнительная информация**
Все, что считаете нужным.

**Comment by gizeasy** [comment]
@N1MBER проверь все места где используется Trasition и TrasitionCss
