### ISSUE TITLE
ContextMenu: добавить размер `xs`

### ISSUE THREAD

**Issue by gizeasy** [consta-design-system/uikit#2062]
в хлебных крошках при размере `xs` меню выглядит большим, хочется чтобы размер одинаковых сущностей был один
![image](https://user-images.githubusercontent.com/13190808/154248937-e2e9d766-cebf-4542-b073-a0fe821911a9.png)

**Comment by hell0anna** [comment]
https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=4894%3A74617
