### ISSUE TITLE
Доработки по планшету

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#2068]

**Comment by linturaven** [comment]
Обновления:
- Новые шапки планшета и дискретных треков: теперь могут быть несколькоэтажными
- Новые шапки для треков с кривыми: теперь с подложкой, удобнее делать многоэтажные шапки
- К блоку шапок добавлен разделитель от тела планшета
- Появились маркеры для выделения интервалов треков
- Появился зум-скроллбар с легендой данных по всей высоте трека
- Теперь компоненты планшетов могут находиться вплотную друг к другу или быть отклеенными друг от друга, как в ранних примерах
- Обновлен пример реализации планшета
- Появился пример реализации корреляционной схемы
+ всякий микротюнинг компонентов, цветов
