### ISSUE TITLE
RCTable: поправить баги

### ISSUE THREAD

**Issue by Tweek123** [consta-design-system/uikit#2069]
**Описание бага**
1) Таблица не занимает полную ширину родительского блока
2) Не задан стиль темы консты для хедер таблицы
3) Нету скролла по боди таблицы, если строки не вмещаются
4) <RCTable sticky={true} prefixCls={prefix} data={infoData.rows} columns={columns} /> при sticky={true} фиксировании хедера при скроле хедер и боди съезжают друг от друга

![Снимок](https://user-images.githubusercontent.com/23486699/154415012-e60bd904-5f54-4e34-85fb-2e278fa44960.PNG)

**Ожидаемое поведение** (опционально)  
![ожидаемое](https://user-images.githubusercontent.com/23486699/154415282-0bc3250e-d42c-4f63-ba15-4dac7489c1c1.PNG)

стили которые немного решают проблему, но это без sticky={true}

.RcTable {
    overflow: auto;
    height: 100%;
}

.RcTable-content > table {
    width: 100%;
}

.RcTable-thead {
    position: sticky;
    top: 0;
    z-index: 1;
}

.Theme .RcTable-thead {
    background: var(--color-bg-default)
}

**Версия Consta Kit**
@consta/uikit@^3.15.1
@consta/rc-table-adapter@^1.0.1

**Comment by N1MBER** [comment]
День добрый! Можете пожалуйста предоставить те данные, которые вы используете для таблицы, а также код как вы используете саму таблицу

**Comment by Tweek123** [comment]
Добрый день!

https://dropmefiles.com/7RFAz
