### ISSUE TITLE
Slider: Доработки

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#2099]

**Comment by pavel-sid** [comment]
### Чек-лист для Slider.
Легенда: :white_check_mark: — PASSED, :x: — FAILED, :grey_question: — SKIPPED
|№|Описание проверки|Win10+ Chrome99|Win10+ Firefox98|Android12+ Chrome|iOS15+ Safari|Monterey+ Safari15|
| ------------- | ------------- | :-------------: | :-------------: | :-------------: | :-------------: | :-------------: |
||**Включение/выключение (disabled)**| | | | | |
|1|Параметр disabled = true деактивирует слайдер| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|2|[disabled = true] Цвет линии выбранного диапазона  — тёмно-серый| :x:| :x:| :x:| :x:| :x:|
|3|[disabled = true] Цвет линии вне диапазона и внешнего контура у точек — светло-серый| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|4|[disabled = true] Нельзя двигать точки слайдера| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|5|[disabled = true] Недоступен ввод значений в опциональное поле ручного ввода| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|6|Параметр disabled=false активирует слайдер| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|7|[disabled = false] Цвет линии выбранного диапазона и внешнего контура у точек — светло-синий 0078D2| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|8|[disabled = false] Цвет линии вне диапазона — светло-серый| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
||**Лейбл (label)**| | | | | |
|9|Значение введённое в параметр label отображается слева над слайдером| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|10|Лейбл выровнен по левому краю| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|11|Допустимо пустое значение — лейбл не отображается, остальные элементы не ломаются| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|12|Длинное значение не вылезает за границу слайдера — строка переносится или обрезается троеточием| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
||**Подпись (caption)**| | | | | |
|13|Значение введённое в параметр caption отображается слева под слайдером| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|14|Подпись выровнена по левому краю| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|15|Допустимо пустое значение — подпись не отображается, остальные элементы не ломаются| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|16|Длинное значение не вылезает за границу слайдера — строка переносится или обрезается троеточием| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
||**Статус (status)**| | | | | |
|17|В параметр status можно выбрать значения alert, warning, success или оставить пустым| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|18|Параметр status не задан — «Подпись» серого цвета| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|19|Параметр status=alert — «Подпись» красного цвета| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|20|Параметр status=warning — «Подпись» оранжевого цвета| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|21|Параметр status=success  — «Подпись» зелёного цвета| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|22|На другие элементы этот параметр не влияет| :x:| :x:| :x:| :x:| :x:|
||**Размер (size)**| | | | | |
|23|В параметр size можно выбрать значения L, M, S, XS| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|24|[size = L] Размер шрифта «Лейбла» 18px| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|25|[size = L] Размер иконки 24 x 24 px| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|26|[size = L] Размер шрифта поля ввода 18px| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|27|[size = L] Ширина х Высота поля ввода: 102 х 48px| :x:| :x:| :x:| :x:| :x:|
|28|[size = M] Размер шрифта «Лейбла» 16px| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|29|[size = M] Размер иконки 24 x 24 px| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|30|[size = M] Размер шрифта поля ввода 16px| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|31|[size = M] Ширина х Высота поля ввода: 102 х 40px| :x:| :x:| :x:| :x:| :x:|
|32|[size = S] Размер шрифта «Лейбла» 14px| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|33|[size = S] Размер иконки 24 x 24 px| :x:| :x:| :x:| :x:| :x:|
|34|[size = S] Размер шрифта поля ввода 14px| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|35|[size = S] Ширина х Высота поля ввода: 102 х 32px| :x:| :x:| :x:| :x:| :x:|
|36|[size = XS] Размер шрифта «Лейбла» 12px| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|37|[size = XS] Размер иконки 16 x 16 px| :x:| :x:| :x:| :x:| :x:|
|38|[size = XS] Размер шрифта поля ввода 12px| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|39|[size = XS] Ширина х Высота поля ввода: 102 х 24px| :x:| :x:| :x:| :x:| :x:|
|40|На другие элементы этот параметр не влияет| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
||**Границы диапазона слайдера (min/max)**| | | | | |
|41|Параметр min задаёт значение для крайнего левого положения точки на слайдере — параметр aria-valuenow не может быть меньше| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|42|Параметр max задаёт значение для крайнего правого положения точки на слайдере —  параметр aria-valuenow не может быть больше| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
||**Шаг (step)**| | | | | |
|43|Параметр step задаёт минимальную длину шага — точки на слайдере перемещают «прыжками» указанной длины| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|44|Значения aria-valuenow установленных точек внутри диапазона кратны шагу| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|45|Если шаг не кратен выбранному общему диапазону слайдера — aria-valuenow точек в крайних положениях равен границам диапазона| :x:| :x:| :x:| :x:| :x:|
|46|Невалидные для параметра step значения игнорируются, применяется значение по умолчанию равное «1»| :x:| :x:| :x:| :x:| :x:|
||**Диапазон (range)**| | | | | |
|47|[range = false] Слайдер с одной точкой| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|48|[range = false] Слева от точки линия в цвете, справа серая| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|49|[range = false] Значения aria-valuenow у точки на границах совпадают с выставленными границами всего слайдера min и max| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|50|[range = false] Точку нельзя переместить за границы слайдера| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|51|[range = true] Слайдер с двумя точками| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|52|[range = true] Между точками линия в цвете, снаружи серая| :x:| :x:| :x:| :x:| :x:|
|53|[range = true] Значения aria-valuenow для левой и правой точек на границах совпадают с выставленными границами всего слайдера min и max| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|54|[range = true] Значение aria-valuenow правой точки всегда больше либо равно левой| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|55|[range = true] Точки нельзя переместить за границы слайдера| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
||**Тултип (withTooltip + withFormatter)**| | | | | |
|56|[withTooltip = false] Тултип под точкой не отображается| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|57|[withTooltip = true] Отображает тултип под точкой| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|58|Если под точкой для тултипа недостаточно места на экране — отображается над точкой| :x:| :x:| :x:| :x:| :x:|
|59|[withFormatter = true] Работает только для тултипа| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|60|[withFormatter = true] В тултипе отображается кастомная информация — на тестовом стенде к числу в тултипе добавляется символ %| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|61|[withFormatter = false] В тултипе отображается только выбранное точкой на слайдере число| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
||**Фиксированные кастомные значения шагов (customStep + steparray)**| | | | | |
|62|Параметр customStep принимает массив целых чисел — фиксированных значений шагов| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|63|[steparray = false] Фиксированные кастомные шаги не применяются, параметр customStep игнорируется| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|64|[steparray = true] Точки слайдера могут перемещаться только на фиксированные кастомные шаги из массива customStep и на граничные значения| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|65|[steparray = true] Для слайдера с одним значением — точка может перемещаться только на фиксированные кастомные шаги из массива customStep и на граничные значения| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|66|[steparray = true] Для слайдера с диапазоном — точки могут перемещаться только на фиксированные кастомные шаги из массива customStep и на граничные значения, левая точка всегда меньше либо равна правой| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
||**Вид линии (view)**| | | | | |
|67|В параметр view можно выбрать значения default и division| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|68|Параметр view = default — сплошная линия| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|69|Параметр view = division — прерывистая линия| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|70|Промежутки между отрезками прерывистой линии — значения, которые можно выбрать точками слайдера| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
||**Доп.элементы слева от слайдера (leftSide)**| | | | | |
|71|У параметра leftSide может быть только одно значение — input| :x:| :x:| :x:| :x:| :x:|
|72|[leftSide = input] Слева от слайдера отображается поле ввода со значением текущего положения точки| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|73|[leftSide = input] Поле ввода становится левой границей всего элемента, линия слайдера пропорционально сокращается (значение на границе прежнее)| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|74|[leftSide = input] Сдвиг точки на слайдере изменяет значение в поле ввода| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|75|[leftSide = input] Ввод значения в поле ввода + снятие фокуса с него — сдвигает точку слайдера на указанное значение| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|76|[leftSide = input] Можно изменять значение нажатием на стрелочки в правой части поля| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|77|[leftSide = input] Поле принимает только доступные для точки слайдера значения (недопустимые значения автоматически изменяются на ближайшие допустимые при снятии фокуса)| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
||**Доп.элементы справа от слайдера (rightSide)**| | | | | |
|78|У параметра rightSide может быть только одно значение — icon| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|79|[rightSide = icon] Справа от слайдера отображается иконка из набора компонентов (на тестовом стенде — «шестерёнка»)| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|80|[rightSide = icon] Иконка становится правой границей всего элемента, линия слайдера сокращается (значение на границе прежнее)| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
||**Ховер**| | | | | |
|81|Область ховера — выбранный диапазон и граничные точки| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|82|Ховер изменяет стиль линии и внешнего контура у точек| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|83|Меняется цвет на голубой 0091FF| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|84|Курсор меняется на «Руку» при ховере на точке| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|85|Если включено отображение тултипов, то при ховере на точке отображается тултип| :white_check_mark:| :white_check_mark:| :grey_question:| :grey_question:| :white_check_mark:|
|86|При снятии ховера стили активной линии и точки слайдера возвращаются к исходному состоянию, тултип скрывается| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
||**Фокус**| | | | | |
|87|При фокусе на точке применяются стили ховера для активной линии и точки| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|88|При фокусе на точке отображается короткая анимация в виде волны от точки, после остаётся ореол вокруг| :white_check_mark:| :white_check_mark:| :x:| :x:| :x:|
|89|Если включено отображение тултипов, то при фокусе на точке отображается тултип| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|90|При снятии фокуса стили активной линии и точки слайдера возвращаются к исходному состоянию, тултип скрывается| :x:| :x:| :x:| :x:| :x:|
||**Проверки для мобильного устройства**| | | | | |
|91|Компонент сохраняет параметры и вёрстку при смене ориентации экрана| :grey_question:| :grey_question:| :x:| :x:| :grey_question:|

**Comment by pavel-sid** [comment]
|||
| ------------- | ------------- |
|**Номер:**|1|
|**Приоритет:**|Minor|
|**Название:**|Параметр status изменяет цвет рамки поля ручного ввода значения.|
|**Окружение:**|Win 10 + Chrome 99 / Win 10 + Firefox 98 / Android 12 + Chrome / iOS 15 + Safari / Monterey + Safari15|
|**Описание:**|При указании параметра status (alert, warning или success) помимо цвета текста подписи изменяется ещё и цвет рамки поля ручного ввода значения слайдера. Однако в требованиях https://consta-uikit.vercel.app/?path=/docs/components-slider--playground есть чёткая формулировка: «Статус влияет только на подпись к ползунку. Если у ползунка нет подписи, пользователь никак не узнает о его статусе.»|
|**Скриншоты/видео:**|https://s.csssr.ru/U02CCH7BNTB/2022-03-07-17-38-50-Ntq9B.mp4|
|**Воспроизведение:**|1. Открыть страницу с компонентом Slider;|
||2. Установить параметр leftSide = input;|
||3. Выбрать для параметра status поочерёдно значения: alert, warning и success.|
|||
|**ФР:**|Изменяется цвет рамки поля ввода.|
|**ОР:**|Изменяется только цвет текста подписи.|

**Comment by pavel-sid** [comment]
|||
| ------------- | ------------- |
|**Номер:**|2|
|**Приоритет:**|Minor|
|**Название:**|Неточности вёрстки иконки.|
|**Окружение:**|Win 10 + Chrome 99 / Win 10 + Firefox 98 / Android 12 + Chrome / iOS 15 + Safari / Monterey + Safari15|
|**Описание:**|У опционального элемента «иконка» есть некоторые неточности вёрстки: 1. Иконка выровнена по верхнему краю области слайдера, а должна быть выровнена по центру; 2. Размеры иконки отличаются от макетов. В текущей реализации используются размеры 12х12, 16х16 для размеров элемента XS, S соответственно, а по макетам должно быть 16x16, 24x24.|
|**Скриншоты/видео:**||
|**Воспроизведение:**|1. Открыть страницу с компонентом Slider;|
||2. Установить параметр rightSide = icon;|
||3. Установить параметр size = XS;|
||4. Установить параметр size = S.|
|||
|**ФР:**|В шаге 3 размер иконки 12х12. В шаге 4 размер иконки 16х16. Иконка не выровнена по центру линии слайдера.|
|**ОР:**|В шаге 3 размер иконки 16х16. В шаге 4 размер иконки 24х24. Иконка выровнена по центру линии слайдера.|

**Comment by pavel-sid** [comment]
|||
| ------------- | ------------- |
|**Номер:**|3|
|**Приоритет:**|Major|
|**Название:**|Невозможно выбрать граничные значения слайдера при шаге некратном длине диапазона.|
|**Окружение:**|Win 10 + Chrome 99 / Win 10 + Firefox 98 / Android 12 + Chrome / iOS 15 + Safari / Monterey + Safari15|
|**Описание:**|Если указать размер шага некратный диапазону 0-max слайдера, то значение aria-valuenow для точки слайдера в крайнем правом положении будет больше максимально допустимого (ближайшее кратное значение в большую сторону). Если минимальное значение слайдера — отрицательное число некратное размеру шага, то в этом случае невозможно установить точку слайдера на минимально возможное (не идёт дальше ближайшего кратного значения). Воспроизводится как для слайдера с одной точкой, так и с двумя.|
|**Скриншоты/видео:**|https://s.csssr.ru/U02CCH7BNTB/2022-03-07-20-12-03-Ifu6o.mp4|
|**Воспроизведение:**|1. Открыть страницу с компонентом Slider;|
||2. Оставить значения min и max по умолчанию — -20 и 80;|
||3. Установить параметр step = 7;|
||4. Открыть в devtools просмотр кода точки слайдера;|
||5. Сдвинуть точку слайдера максимально вправо;|
||6. Сдвинуть точку слайдера максимально влево.|
|||
|**ФР:**|В шаге 5 значение aria-valuenow = 84. В шаге 6 слайдер нельзя установить в минимальное положение, значение aria-valuenow = -14.|
|**ОР:**|Точка(-и) слайдера можно установить в крайние положения, значения в них равны заданным параметрам min и max (-20 и 80 соответственно)|

**Comment by pavel-sid** [comment]
|||
| ------------- | ------------- |
|**Номер:**|4|
|**Приоритет:**|Major|
|**Название:**|Опорной точкой отсчёта шагов является ноль|
|**Окружение:**|Win 10 + Chrome 99 / Win 10 + Firefox 98 / Android 12 + Chrome / iOS 15 + Safari / Monterey + Safari15|
|**Описание:**|[Важно: для соответствия описания требуется исправление бага №3, иначе невозможно выставить значения на края диапазона] Для конфигураций слайдера с шагом больше 1 и минимальной границей в виде отрицательного числа получаем ситуацию, что шаги всегда отсчитываются от 0. Например, для диапазона слайдера от -5 до +25 с шагом в 10 — получим набор значений: -5, 0, 10, 20, 25, но фактически правильным был бы диапазон -5, 5, 15, 25. Второй проблемой является несоответствие шагов точки слайдера и отрезков линий в режиме view = division — линия разделяется на отрезки правильно, а точка шага выставляется мимо.|
|**Скриншоты/видео:**|https://s.csssr.ru/U02CCH7BNTB/2022-03-07-20-44-22-utp9G.mp4|
|**Воспроизведение:**|1. Открыть страницу с компонентом Slider;|
||2. Установить значения min и max — -5 и 25;|
||3. Установить параметр step = 10;|
||4. Установить параметр view = division;|
||5. Открыть в devtools просмотр кода точки слайдера;|
||6. Перемещать точку слайдера от минимума до максимума.|
|||
|**ФР:**|Точку слайдера можно установить на значения -5, 0, 10, 20, 25. Точка перемещается не попадая на промежутки в линии.|
|**ОР:**|Точка перемещается по разрывам линии слайдера, принимает значения -5, 5, 15, 25.|

**Comment by pavel-sid** [comment]
|||
| ------------- | ------------- |
|**Номер:**|6|
|**Приоритет:**|Critical|
|**Название:**|Слайдер «блокируется», если обе точки переместить максимально вправо (режим диапазона).|
|**Окружение:**|Win 10 + Chrome 99 / Win 10 + Firefox 98 / Android 12 + Chrome / iOS 15 + Safari / Monterey + Safari15|
|**Описание:**|Если в режиме диапазона (range = true) передвинуть обе точки в крайнее правое положение, то становится невозможным дальнейшее перемещение точек слайдера — правая точка находится переднем плане относительно левой и мешает «схватить» и переместить левую точку налево. Правая точка также не может быть сдвинута, т.к. не может быть левее левой точки и правее границы диапазона.|
|**Скриншоты/видео:**|https://s.csssr.ru/U02CCH7BNTB/2022-03-09-10-37-36-JGS4W.mp4|
|**Воспроизведение:**|1. Открыть страницу с компонентом Slider;|
||2. Установить параметр range = true;|
||3. Переместить правую точку в крайнее правое положение;|
||4. Переместить левую точку в крайнее правое положение.|
|||
|**ФР:**|Сдвиг точек диапазона более невозможен, т.к. не получается «схватить» левую точку для сдвига влево.|
|**ОР:**|Левую точку можно сдвинуть налево.|

**Comment by pavel-sid** [comment]
|||
| ------------- | ------------- |
|**Номер:**|7|
|**Приоритет:**|Normal|
|**Название:**|Нет тултипа над точкой, если внизу страницы нет места для него.|
|**Окружение:**|Win 10 + Chrome 99 / Win 10 + Firefox 98 / Android 12 + Chrome / iOS 15 + Safari / Monterey + Safari15|
|**Описание:**|Если включить отображение тултипов и сдвигать нижнюю границу страницы под слайдер, то тултип сначала смещается левее и выше (частично перекрывая линию), а при дальнейшем смещении границы экрана перестаёт отображаться. Кажется было бы правильнее отображать тултип сверху над точкой, как только снизу для него перестаёт хватать места.|
|**Скриншоты/видео:**|https://s.csssr.ru/U02CCH7BNTB/2022-03-09-11-07-39-Eue3R.mp4|
|**Воспроизведение:**|1. Открыть страницу с компонентом Slider с включенным отображением тултипов: https://consta-uikit.vercel.app/iframe.html?id=components-slider--playground&knob-withTooltip=true ;|
||2. Установить высоту страницы 100 px;|
||3. Навести курсор на точку ;|
||4. Установить высоту страницы 95 px;|
||5. Навести курсор на точку.|
|||
|**ФР:**|В шаге 3 тултип отображается слева от точки, перекрывая линии слайдера. В шаге 5 тултип не отображается.|
|**ОР:**|В шагах 3 и 5 тултип отображается над точкой.|

**Comment by pavel-sid** [comment]
|||
| ------------- | ------------- |
|**Номер:**|8|
|**Приоритет:**|Minor|
|**Название:**|Доступно отображение иконки для левой стороны слайдера.|
|**Окружение:**|Win 10 + Chrome 99 / Win 10 + Firefox 98 / Android 12 + Chrome / iOS 15 + Safari / Monterey + Safari15|
|**Описание:**|Для параметра leftSide можно выбрать значение icon → отображается иконка слева от линии слайдера. Однако в требованиях https://consta-uikit.vercel.app/?path=/docs/components-slider--playground есть такая строка «У свойства leftSide может быть только одно значение — input».|
|**Скриншоты/видео:**|https://s.csssr.ru/U02CCH7BNTB/2022-03-09-11-20-46-bqJ9Q.jpg|
|**Воспроизведение:**|1. Открыть страницу с компонентом Slider;|
||2. Установить параметр leftSide = icon.|
|||
|**ФР:**|Есть возможность выбрать значение icon для параметра leftSide, слева от слайдера отображается иконка.|
|**ОР:**|Для параметра leftSide может быть только одно значение — input.|

**Comment by pavel-sid** [comment]
|||
| ------------- | ------------- |
|**Номер:**|10|
|**Приоритет:**|Normal|
|**Название:**|Недопустимое значение в параметре step «вешает» страницу.|
|**Окружение:**|Win 10 + Chrome 99 / Win 10 + Firefox 98 / Android 12 + Chrome / iOS 15 + Safari / Monterey + Safari15|
|**Описание:**|Если ввести в поле step значение «0», дробное, отрицательное или просто очистить поле — страница зависает, системный процесс отвечающий за страницу значительно увеличивает потребление памяти, страница выдаёт ошибку.|
|**Скриншоты/видео:**|https://s.csssr.ru/U02CCH7BNTB/2022-03-09-11-51-03-l9P3k.mp4|
|**Воспроизведение:**|1. Открыть страницу с компонентом Slider;|
||2. Очистить поле параметра step.|
|||
|**ФР:**|Страница зависает, процесс страницы начинает потреблять значительные ресурсы системы, страница падает с ошибкой.|
|**ОР:**|Недопустимые значения для параметра step игнорируются, применяется значение по умолчанию = 1.|

**Comment by pavel-sid** [comment]
|||
| ------------- | ------------- |
|**Номер:**|12|
|**Приоритет:**|Normal|
|**Название:**|Сбивается положение точки шага при смене ориентации экрана.|
|**Окружение:**|Android 12 + Chrome / iOS 15 + Safari|
|**Описание:**|При смене ориентации мобильного устройства сбивается положение точки, при этом судя по полю ввода значение aria-valuenow не нарушается. Хорошо воспроизводится и заметно на крайних положениях точки. Воспроизводится для всех режимов (одиночное значение и диапазон, разные размеры шага, режим набора фиксированных шагов).|
|**Скриншоты/видео:**|https://s.csssr.ru/U02CCH7BNTB/2022-03-09%2016-15-43.MP4|
|**Воспроизведение:**|1. Открыть страницу с компонентом Slider;|
||2. Установить точку в крайнее правое положение;|
||3. Сменить ориентацию устройства;|
||4. Поправить положение точки в крайнем правом положении;|
||5. Изменить ориентацию устройства обратно;|
||6. Повторить шаги 2-5 для левого крайнего положения точки.|
|||
|**ФР:**|После смены ориентации точка располагается некорректно — заезжает на иконку/поле ввода или наоборот располагается не на краю слайдера.|
|**ОР:**|Точка сохраняет выставленное крайнее положение.|

**Comment by pavel-sid** [comment]
|||
| ------------- | ------------- |
|**Номер:**|14|
|**Приоритет:**|Minor|
|**Название:**|Не срабатывает отображение фокуса для точки слайдера.|
|**Окружение:**|Android 12 + Chrome / iOS 15 + Safari / Monterey + Safari15|
|**Описание:**|Если переместить точку на слайдере, то она не срабатывает стиль фокуса (анимация и ореол вокруг точки). Если же просто тапнуть на точку, то стиль применяется. Для MacOS + Safari клик на точке не вызывает сработку фокуса, но фокус срабатывает при перемещении по странице по кнопке «Tab».|
|**Скриншоты/видео:**|https://s.csssr.ru/U02CCH7BNTB/2022-03-09%2017-29-36.MP4|
|**Воспроизведение:**|1. Открыть страницу с компонентом Slider;|
||2. Переместить точку на слайдере.|
|||
|**ФР:**|Не срабатывает стиль фокуса для точки.|
|**ОР:**|На точку применяется стиль фокуса — анимация и ореол вокруг.|

**Comment by pavel-sid** [comment]
|||
| ------------- | ------------- |
|**Номер:**|15|
|**Приоритет:**|Normal|
|**Название:**|Вызывается обычная клавиатура, а не цифровая при фокусе на поле ввода.|
|**Окружение:**|iOS 15 + Safari / iOS 15 + Chrome|
|**Описание:**|Если установить фокус в поле ввода, то открывается обычная клавиатура, а не цифровая. Воспроизводится только в браузерах на iOS. В браузерах на Android открывается цифровая клавиатура.|
|**Скриншоты/видео:**||
|**Воспроизведение:**|1. Открыть страницу с компонентом Slider с включенным полем ввода: https://consta-uikit.vercel.app/iframe.html?id=components-slider--playground&knob-leftSide=input ;|
||2. Тапнуть на поле ввода.|
|||
|**ФР:**|Открылась обычная клавиатура.|
|**ОР:**|Открылась цифровая клавиатура.|

**Comment by pavel-sid** [comment]
|||
| ------------- | ------------- |
|**Номер:**|16|
|**Приоритет:**|Normal|
|**Название:**|Не скрывается тултип при снятии фокуса.|
|**Окружение:**|Android 12 + Chrome / iOS 15 + Safari / Monterey + Safari15|
|**Описание:**|Если нажать на точку на слайдере или подвигать её, то под точкой отображается тултип. Но он не исчезает при снятии фокуса. Воспроизводится и на живых устройства, и в браузере в режиме «Mobile» в devtools и в обычном режиме для MacOS + Safari.|
|**Скриншоты/видео:**|https://s.csssr.ru/U02CCH7BNTB/2022-03-10-10-20-00-IeA8g.mp4|
|**Воспроизведение:**|1. Открыть страницу с компонентом Slider с включенным полем ввода и тултипом: https://consta-uikit.vercel.app/iframe.html?id=components-slider--playground&knob-leftSide=input&knob-withTooltip=true&knob-withFormatter=true ;|
||2. Тапнуть на точку слайдера;|
||3. Тапнуть в пустое место вне слайдера;|
||4. Установить фокус в поле ввода;|
||5. Тапнуть по любой стрелочке в поле ввода.|
|||
|**ФР:**|В шагах 3-4 тултип продолжает отображаться и только в шаге 5 исчезает.|
|**ОР:**|Тултип исчезает при любом взаимодействии НЕ с точкой на слайдере.|
