### ISSUE TITLE
ProgressStepBar: Доработки

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#2100]

**Comment by pavel-sid** [comment]
### Чек-лист для вертикального ProgressStepBar.
Легенда: :white_check_mark: — PASSED, :x: — FAILED, :grey_question: — SKIPPED
|№|Описание проверки|Win10+ Chrome99|Win10+ Firefox98|Android12+ Chrome|iOS15+ Safari|Monterey+ Safari15|
| ------------- | ------------- | :-------------: | :-------------: | :-------------: | :-------------: | :-------------: |
|1|**Вертикальное расположение (Параметр direction=vertical**| | | | | |
|2|Элементы/шаги расположены вертикально| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|3|Элемент ProgressStepBar имеет минимальную высоту в зависимости от размера элементов| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|4|Расстояние между шагами минимально, если заголовок в одну строчку и нет доп.опций| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|5|Расстояние между шагами увеличивается на размер заголовка и/или доп.опций| :grey_question:| :grey_question:| :grey_question:| :grey_question:| :grey_question:|
|6|От крайних точек линии отходят только внутрь элемента| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|7|От средних точек линии отходят вверх и вниз| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
||**Заголовок**| | | | | |
|8|Заголовок шага располагается справа от точки/иконки шага| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|9|Текст заголовка шага выровнен по левому краю| :x:| :x:| :x:| :x:| :x:|
||**Тултип**| | | | | |
|10|Тултип отображается справа от заголовка шага при наведении курсора на область круга или заголовка| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|11|Текст в тултипе выровнен по левому краю| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|12|Если недостаточно места для тултипа на странице справа — он отображается слева от точки шага| :x:| :x:| :x:| :x:| :x:|
|13|В тултипе отображается текст| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|14|Рамка тултипа выровнена по центру относительно точки шага| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|15|Треугольник указателя указывает на точку шага| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
||**Дополнительные опции**| | | | | |
|16|Описание шага отображается под заголовком, рекомендованная длина — не более 4 строк, но ограничений нет| :grey_question:| :grey_question:| :grey_question:| :grey_question:| :grey_question:|
|17|Под заголовком/описанием шага можно включить отображение иконки| :grey_question:| :grey_question:| :grey_question:| :grey_question:| :grey_question:|
|18|Под заголовком/описанием шага можно включить отображение дополнительного статуса| :grey_question:| :grey_question:| :grey_question:| :grey_question:| :grey_question:|
|19|Под заголовком/описанием шага можно включить отображение кнопки| :grey_question:| :grey_question:| :grey_question:| :grey_question:| :grey_question:|
|20|Иконка, доп.статус и кнопка располагаются в одну строку под описанием шага| :grey_question:| :grey_question:| :grey_question:| :grey_question:| :grey_question:|
|21|Иконка, доп.статус и кнопка выровнены по левому краю| :grey_question:| :grey_question:| :grey_question:| :grey_question:| :grey_question:|
||**Размер (size)**| | | | | |
|22|[size = xs] Заголовок: font-size: 14px, line-height: 16px, Weight: 400| :x:| :x:| :x:| :x:| :x:|
|23|[size = xs] Толщина линии = 2px| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|24|[size = xs] Диаметр точки шага = 8px| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|25|[size = xs] Точки шагов не имеют содержимого, только сплошную заливку| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|26|[size = xs] Описание шага: 12px, line-height: 16px, Weight: 400"| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|27|[size = s] Заголовок: font-size: 14px, line-height: 16px, Weight: 400| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|28|[size = s] Толщина линии = 4px| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|29|[size = s] Диаметр точки шага = 16px| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|30|[size = s] Внутри точек шага отображается номер/иконка| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|31|[size = s] Описание шага: 12px, line-height: 16px, Weight: 400"| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|32|[size = m] Заголовок: font-size: 16px, line-height: 24px, Weight: 400| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|33|[size = m] Толщина линии = 4px| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|34|[size = m] Диаметр точки шага = 24px| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|35|[size = m] Внутри точек шага отображается номер/иконка = 24px| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|36|[size = m] Описание шага: 14px, line-height: 18px, Weight: 400"| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
||**Адаптив**| | | | | |
|37|Если элемент ProgressStepBar не умещается на малой ширине экрана — переключается на адаптив| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|38|В адаптивном формате элемент ProgressStepBar сворачивается в область с прокруткой| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|39|Список прокручивается нажатием на стрелки| :x:| :x:| :x:| :x:| :x:|
|40|Список прокручивается свайпом| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
||**Активный шаг (activeStepIndex)**| | | | | |
|41|В параметре activeStepIndex указывается текущий активный шаг (Нумерация с 0 — это первый шаг)| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|42|[Активный шаг] Серая точка шага закрашивается в цвет из свойства status| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|43|[Активный шаг] [Опционально] Иконка точки шага сменяется на иконку лоадера| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|44|[Активный шаг] Если шаг НЕ последний, то серая линия следующая от шага закрашивается в цвет из свойства lineStatus| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|45|[Пройденный шаг] Точка остаётся закрашенной в цвет из свойства status| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|46|[Пройденный шаг] [Опционально] Иконка лоадера сменяется на иконку заданную в свойстве point| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|47|[Пройденный шаг] Если шаг НЕ последний, то линия следующая от шага остаётся закрашенной в цвет из свойства lineStatus| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|48|[Ожидающий шаг] Точка закрашена серым| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
|49|[Ожидающий шаг] Если шаг НЕ последний, то линия следующая от шага серая| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:| :white_check_mark:|
||**Кликабельная точка шага**| | | | | |
|50|Если указано свойство onClick — область точки шага становится кликабельной| :grey_question:| :grey_question:| :grey_question:| :grey_question:| :grey_question:|
|51|При ховере на курсор сменяется на руку| :grey_question:| :grey_question:| :grey_question:| :grey_question:| :grey_question:|
|52|По клику выполняется заданное действие| :grey_question:| :grey_question:| :grey_question:| :grey_question:| :grey_question:|

**Comment by pavel-sid** [comment]
|||
| ------------- | ------------- |
|**Номер:**|1|
|**Приоритет:**|Minor|
|**Название:**|Галочка при загрузке компонента.|
|**Окружение:**|Win 10 + Chrome 99 / Win 10 + Firefox 98 / Android 12 + Chrome / iOS 15 + Safari / Monterey + Safari15|
|**Описание:**|Во время загрузки страницы с компонентом — отображается огромный символ «галочка». Судя по всему отображаются ещё не отформатированные символы из точек шагов и тексты заголовков.|
|**Скриншоты/видео:**|https://s.csssr.ru/U02CCH7BNTB/2022-03-05-17-10-19-YCN8n.mp4|
|**Воспроизведение:**|1. Открыть страницу с компонентом ProgressStepBar;|
||2. Перезагружать страницу и наблюдать за экраном.|
|||
|**ФР:**|Перед загрузкой компонента на короткий момент отображается не отформатированное содержимое, например огромная галочка.|
|**ОР:**|Страница отображает компонент в готовом виде.|

**Comment by pavel-sid** [comment]
|||
| ------------- | ------------- |
|**Номер:**|2|
|**Приоритет:**|Minor|
|**Название:**|Слишком близко расположенные заголовки шагов на узкой странице.|
|**Окружение:**|Win 10 + Chrome 99 / Win 10 + Firefox 98 / Android 12 + Chrome / iOS 15 + Safari / Monterey + Safari15|
|**Описание:**|В пограничном состоянии ширины компонента, перед тем как отображение переключится на адаптив со скроллом, текст заголовков располагается без зазоров. При определённом сочетании ширины страницы и размера заголовков может получится некрасиво.|
|**Скриншоты/видео:**|https://s.csssr.ru/U02CCH7BNTB/2022-03-05-17-59-59-jXO2X.mp4|
|**Воспроизведение:**|1. Открыть страницу с компонентом ProgressStepBar;|
||2. Уменьшать ширину страницы до момента максимального сближения заголовков шагов.|
|||
|**ФР:**|Шаги сближаются до отсутствия дистанции между заголовками шагов.|
|**ОР:**|При уменьшении ширины экрана всегда есть расстояние между заголовками, иначе происходит переключение в адаптив.|

**Comment by pavel-sid** [comment]
|||
| ------------- | ------------- |
|**Номер:**|3|
|**Приоритет:**|Minor|
|**Название:**|Неравная дистанция между точками шагов.|
|**Окружение:**|Win 10 + Chrome 99 / Win 10 + Firefox 98 / Android 12 + Chrome / iOS 15 + Safari / Monterey + Safari15|
|**Описание:**|В требованиях (страница описания в макете) есть строка «Выравнивание пунктов происходит не по тексту, а по точкам «points». Но в реализации расстояния между шагами не одинаковое, зависит ещё и от размера заголовков.|
|**Скриншоты/видео:**|https://s.csssr.ru/U02CCH7BNTB/2022-03-05-18-08-39-EQQ8T.jpg|
|**Воспроизведение:**|1. Открыть страницу с компонентом ProgressStepBar;|
||2. Уменьшить ширину страницы до 320px.|
|||
|**ФР:**|Расстояние между всеми шагами разное.|
|**ОР:**|Расстояние между точками шагов одинаковое.|

**Comment by pavel-sid** [comment]
|||
| ------------- | ------------- |
|**Номер:**|4|
|**Приоритет:**|Normal|
|**Название:**|Некорректно отображается тултип над шагом.|
|**Окружение:**|Win 10 + Chrome 99 / Win 10 + Firefox 98 / Android 12 + Chrome / iOS 15 + Safari / Monterey + Safari15|
|**Описание:**|Если для отображения тултипа под шагом/заголовком шага не хватает места внизу страницы, то его стоит отображать над точкой шага. Недостаток в том, что тултип вверх при ховере на Заголовке отображается над этим Заголовком, перекрывая точку шага, а при ховере на точку шага не отображается (мелькает только при ховере на границе точки). А тултип для крайнего левого шага всегда отображается вниз, уходя за границу экрана. Хорошо бы при ховере и на точке и на заголовке отображать тултип над точкой шага (как это делается для отображения тултипа вниз).|
|**Скриншоты/видео:**|https://s.csssr.ru/U02CCH7BNTB/2022-03-07-14-31-17-oMr2U.mp4|
|**Воспроизведение:**|1. Открыть страницу с компонентом ProgressStepBar;|
||2. Опустить компонент ProgressStepBar на 5 строчек ниже на странице (чтобы было место для отображения тултипа вверх);|
||3. Через dev-tools выставить размеры экрана 800*200;|
||4. Навести курсор на Заголовок и точку крайнего левого шага;|
||5. Навести курсор на заголовки всех остальных шагов;|
||6. Навести курсор на точки всех остальных шагов.|
|||
|**ФР:**|Для крайнего левого шага тултип всегда отображается вниз — под заголовком шага. Для остальных шагов при ховере на заголовке тултип отображается вверх, но перекрывает точку шага. Для остальных шагов тултип мелькает при ховере на границе круга, но не отображается при ховере внутри круга.|
|**ОР:**|При недостатке места внизу странице тултип отображается над точкой шага при ховере на точке и на заголовке.|

**Comment by pavel-sid** [comment]
|||
| ------------- | ------------- |
|**Номер:**|5|
|**Приоритет:**|Normal|
|**Название:**|Некорректная вёрстка тултипа крайнего правого шага.|
|**Окружение:**|Win 10 + Chrome 99 / Win 10 + Firefox 98 / Android 12 + Chrome / iOS 15 + Safari / Monterey + Safari15|
|**Описание:**|Тултип крайнего правого шага имеет несколько несоответствий: 1. Рамка не выровнена справа по краю компонента — вылезает вправо до края экрана. 2. Стрелка указатель на рамке расположена посередине, а не в правой части. 3. Рамка ограничена слева — содержимое тултипа растягивается вниз даже на широкой странице.|
|**Скриншоты/видео:**|https://s.csssr.ru/U02CCH7BNTB/2022-03-07-14-46-26-qd82S.jpg|
|**Воспроизведение:**|1. Открыть страницу с компонентом ProgressStepBar;|
||2. Навести курсор на заголовок крайнего правого шага.|
|||
|**ФР:**|Рамка тултипа ограничена слева и не ограничена справа. Стрелка указатель посередине рамки.|
|**ОР:**|Вёрстка крайнего правого тултипа зеркально повторяет вёрстку крайнего левого — рамка ограничена справа по размеру компонента, а слева ограничения нет, стрелка указатель справа.|

**Comment by pavel-sid** [comment]
|||
| ------------- | ------------- |
|**Номер:**|6|
|**Приоритет:**|Minor|
|**Название:**|Шрифт заголовка 12px для XS-размера компонента.|
|**Окружение:**|Win 10 + Chrome 99 / Win 10 + Firefox 98 / Android 12 + Chrome / iOS 15 + Safari / Monterey + Safari15|
|**Описание:**|В текущей реализации компонента в размере XS величина шрифта заголовка равна 12px. Это совпадает с документацией компонента https://s.csssr.ru/U02CCH7BNTB/2022-03-07-14-54-43-peJ3y.jpg, но противоречит макетам — там размер шрифта 14px.|
|**Скриншоты/видео:**|https://s.csssr.ru/U02CCH7BNTB/2022-03-10-15-59-15-Ynj3x.jpg|
|**Воспроизведение:**|1. Открыть страницу с компонентом ProgressStepBar;|
||2. Указать параметр size=xs;|
||3. Измерить шрифт заголовка шагов.|
|||
|**ФР:**|Размер шрифта заголовков 12px|
|**ОР:**|Размер шрифта заголовков 14px: https://s.csssr.ru/U02CCH7BNTB/2022-03-07-14-58-07-Mob4j.jpg|

**Comment by pavel-sid** [comment]
|||
| ------------- | ------------- |
|**Номер:**|7|
|**Приоритет:**|Minor|
|**Название:**|Заголовок крайнего нижнего шага выравнивается по правому краю.|
|**Окружение:**|Win 10 + Chrome 99 / Win 10 + Firefox 98 / Android 12 + Chrome / iOS 15 + Safari / Monterey + Safari15|
|**Описание:**|Текст заголовка крайнего нижнего шага размером в две и более строки выравнивается по правому краю. Этого не наблюдается для остальных шагов.|
|**Скриншоты/видео:**|https://s.csssr.ru/U02CCH7BNTB/2022-03-07-15-36-21-YzM2l.mp4|
|**Воспроизведение:**|1. Открыть страницу с компонентом ProgressStepBar;|
||2. Указать параметр direction=vertical;|
||3. Уменьшить размер экрана до сдвига заголовка нижнего шага в две строки.|
|||
|**ФР:**|Текст заголовка крайнего нижнего шага выровнен по правому краю.|
|**ОР:**|Текст заголовка крайнего нижнего шага выровнен по левому краю.|

**Comment by pavel-sid** [comment]
|||
| ------------- | ------------- |
|**Номер:**|9|
|**Приоритет:**|Major|
|**Название:**|Нет первой прокрутки компонента стрелкой вправо в режиме адаптива.|
|**Окружение:**|Win 10 + Chrome 99 / Win 10 + Firefox 98 / Android 12 + Chrome / iOS 15 + Safari / Monterey + Safari15|
|**Описание:**|После загрузки страницы в режиме адаптива компонент progressstepbar отображается от крайнего левого шага. Нажатие на стрелку «вправо» не приводит к прокрутке. Если же нажать на стрелку «влево», то отобразится правая часть progressstepbar. После этого нажатия на стрелки сдвигает компонент в обоих направлениях.|
|**Скриншоты/видео:**|https://s.csssr.ru/U02CCH7BNTB/2022-03-10-16-04-55-HOF4T.mp4|
|**Воспроизведение:**|1. Установить размер окна браузера в 320х300 px;|
||2. Открыть страницу с компонентом ProgressStepBar в размере М: https://consta-uikit.vercel.app/iframe.html?id=components-progressstepbar--playground&knob-size=m ;|
||3. Нажать на стрелку прокрутки вправо;|
||4. Нажать на стрелку прокрутки влево.|
|||
|**ФР:**|В шаге 3 изменений на странице нет, элемент не прокручивается. В шаге 4 компонент отображается с правого крайнего шага.|
|**ОР:**|В шаге 3 элемент прокручивается вправо. В шаге 4 элемент не прокручивается, т.к. уже в крайнем левом положении.|

**Comment by pavel-sid** [comment]
|||
| ------------- | ------------- |
|**Номер:**|10|
|**Приоритет:**|Minor|
|**Название:**|Неодинаковые размеры для содержимого под шагами в горизонтальном режиме.|
|**Окружение:**|Win 10 + Chrome 99 / Win 10 + Firefox 98 / Android 12 + Chrome / iOS 15 + Safari / Monterey + Safari15|
|**Описание:**|В горизонтальном режиме у крайних шагов область под заголовок/доп.опции в два раза меньше, чем у средних шагов. Из-за чего при небольшой ширине экрана и/или большом количестве шагов можем получить изображение, где при одинаковой длине текста заголовков всех шагов, у крайних шагов заголовки будут отображаться в две строки.|
|**Скриншоты/видео:**|https://s.csssr.ru/U02CCH7BNTB/2022-03-07-17-15-31-JmH5T.jpg|
|**Воспроизведение:**|1. Открыть страницу с компонентом ProgressStepBar;|
||2. Установить ширину окна в 730 px;|
|||
|**ФР:**|Заголовок четвёртого шага в две строки.|
|**ОР:**|Заголовок четвёртого шага переносится на вторую строку, когда размер блока под текст становится меньше 1/4 от размера всего ProgressStepBar.|

**Comment by pavel-sid** [comment]
|||
| ------------- | ------------- |
|**Номер:**|11|
|**Приоритет:**|Major|
|**Название:**|Полоса прокрутки во всю ширину/высоту компонента в Firefox|
|**Окружение:**|Windows 10 + Firefox 98|
|**Описание:**|В браузере Firefox рядом с компонентом отображается полоса прокрутки во всю ширину (для горизонтального расположения) и во всю высоту (для вертикального расположения). Воспроизводится только в браузере Firefox.|
|**Скриншоты/видео:**|1. https://s.csssr.ru/U02CCH7BNTB/2022-03-10-11-55-15-3sP8A.jpg|
||2. https://s.csssr.ru/U02CCH7BNTB/2022-03-10-11-55-38-7KJ8v.jpg|
|**Воспроизведение:**|1. Открыть страницу с компонентом ProgressStepBar;|
||2. Указать параметр direction=vertical.|
|||
|**ФР:**|В шаге 1 ниже компонента отображается полоса прокрутки. В шаге 2 справа от компонента отображается полоса прокрутки.|
|**ОР:**|Полоса прокрутки не отображается.|
