### ISSUE TITLE
Кнопка с иконкой не корректно работает с loading

### ISSUE THREAD

**Issue by SergeyKatugin** [consta-design-system/uikit#2101]
**Описание бага**
При использовании onlyIcon, iconLeft и loading иконка не пропадает и при этом лоадер имеется.

**Как воспроизвести баг** (опционально)  
Листинг
```js
<Button
          size="xs"
          iconSize="m"
          view="clear"
          onClick={openDropdown}
          onlyIcon
          loading={loading || false}
          iconLeft={IconMoreVertical}
        />
```

**Ожидаемое поведение**
Пропадает иконка и виден лоадер

**Версия Consta Kit**
Последняя

**Comment by Lyubavskaya** [comment]
![image](https://user-images.githubusercontent.com/75978078/156380991-ce334f11-6c5c-4816-9370-05f462256304.png)

**Comment by N1MBER** [comment]
Проблема с созданием кастомной иконки, исправление документации: https://github.com/consta-design-system/uikit/issues/2207
