### ISSUE TITLE
[3279] Consta Table: Исправить баг при раскрытии строки с объединенными ячейками

### ISSUE THREAD

**Issue by roman9688** [consta-design-system/uikit#2102]
**Описание бага**
Имеем таблицу, в которой одновременно есть строка с объединенными ячейками и вложенными строками, скрин 1
![ntex1](https://user-images.githubusercontent.com/100828560/156513749-aecce5cd-0a68-445b-a2e7-084e28032961.PNG)
Пытаемся раскрыть месторождение Северное и получаем 2 строки с месторождением Северное, скрин 2
![ntex2](https://user-images.githubusercontent.com/100828560/156513919-a8045600-057c-41f2-b249-49fa7dea7452.PNG)

**Как воспроизвести баг** (опционально)  
1. Переходим в сторибук (https://consta-uikit.vercel.app/?path=/story/components-table--with-collapcing-rows)
2. Добавляем объединение ячеек для столбика Месторождение с помощью ``` "mergeCells": true```
3. Изменяем в ```rows``` у строчки с ```id: row2``` поле ```field``` с Южное на Северное
4. Щелкаем стрелку, чтоб раскрыть строку Северное

**Ожидаемое поведение** (опционально)  
В таблице продолжает оставаться одна строка со значением Северное в столбце Месторождение. Под ней появляются вложенные строки

**Текущее поведение**
Строка со значением Северное разбивается на две строки. Под первой появляются вложенные строки

**Версия Consta Kit**
3.13.0

**Параметры софта на компьютере:**

- ОС: Windows 10
- Браузер и его версия: Chrome 98.0.4758.102

**Comment by lisaovcharenko** [comment]
Надо учесть в рамках https://github.com/consta-design-system/uikit/issues/3279

**Comment by lisaovcharenko** [comment]
@gizeasy возможно это нужно поправить в текущей таблице

**Comment by gizeasy** [comment]
Теперь реализация раскрытия строк лежит на проекте. Задача не актуальная
