### ISSUE TITLE
EventInterceptor: добавить в eventInterceptorMap новые компоненты consta (Tag, Card)

### ISSUE THREAD

**Issue by NIRumiantsev** [consta-design-system/uikit#2103]
**Описание фичи или улучшения**
На данный момент eventInterceptorMap поддерживает лишь компоненты Button, Checkbox, Select, SnackBar и TextField. Для решения задачи по настройке аналитики нам необходимо добавить еще 2 компонента: Tag и Card.

**Comment by gizeasy** [comment]
Думаем добавить все компоненты в EventInterceptor, но в eventInterceptorMap не будем добавлять так как, функции обработки действий могут быть разными на каждом проекте.
То есть если прописать свою функцию обработки в `eventInterceptorMap` то она сработает.
