### ISSUE TITLE
рассмотреть возможность добавления Breadcrumbs с меню к элемам как можно скорее

### ISSUE THREAD

**Issue by Troonsply** [consta-design-system/uikit#2120]
Работаю над проектом, где в дизайне есть бредкрамбсы с выпадающим списком, так как весь дизайн проекта на консте, прошу рассмотреть возможность поскорее добавить этот элемент в библиотеку.

**Comment by Lyubavskaya** [comment]
@Troonsply Вы имеете ввиду в коде добавить? (в дизайне это есть) 
На эту тему есть ишью https://github.com/consta-design-system/uikit/issues/2075

**Comment by Troonsply** [comment]
@Lyubavskaya Да, я имею ввиду код.

**Comment by Lyubavskaya** [comment]
Тогда это дубль https://github.com/consta-design-system/uikit/issues/2075
