### ISSUE TITLE
Step с ошибкой

### ISSUE THREAD

**Issue by AntonS86** [consta-design-system/uikit#2141]
![image](https://user-images.githubusercontent.com/37770694/159001333-0e3d309c-257d-43a3-ba19-724a2ed1365d.png)

при включении гугл переводчика, и в последующем переключении степов, приложение падает с ошибкой, просто нажмите перевести страницу и попереключайте

**Comment by gizeasy** [comment]
Возможно проблема ушла, нужно проверить.
