### ISSUE TITLE
Charts: Графики по новому подходу 

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#2149]
- Area
- Bar
- Column
- Pie
- Waterfall
- Bullet

Напишу еще сюда коммент из опроса: 
Виджеты с графиками сделаны. с ошибками в констрейнах - где-то виджет не тянется вообще, а где-то съезжают подписи, потому что констрейны неправильно стоят. Фигмовским виджетам вообще невозможно задать другой размер, но при этом не понятно в какую сетку их можно вписать, они все разного размера. Нельзя например сделать маленькую круговую диаграмму. Где-то легенда в фигме стоит сверху, но в коде она выравнивается по центру. Разарботчики жалуются что отрезаны возможности настраивать виджет. В дизайне так же виджет можно поставить только как есть, но что-то поменять нельзя. В большой круговой диаграмме цифры долей подписываются странно, всех это удивляет, приходится отрывать компонент и переделывать руками.

**Comment by hell0anna** [comment]
+ 
- поправить сетку (логика с геологических графиков, добавить TrackBody -- фон, который можно красить)
- поправить GraphScale (заменить прямоугольники на line, добавить черточки у оси Y)

**Comment by hell0anna** [comment]
- [ ] Area
- [ ] Bar
- [ ] Column
- [ ] Pie
- [ ] Waterfall
- [ ] Bullet

**Comment by hell0anna** [comment]
- [ ] radar

**Comment by hell0anna** [comment]
- [ ] bullet
- [ ] dualAxes
- [ ] histogram
- [ ] scatter
- [ ] mix plot
- [ ] gaude

**Comment by hell0anna** [comment]
- [ ] добавить MultiAxis график в Consta Charts
