### ISSUE TITLE
Icons: Ревью иконок, добавление маленьких размеров

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#2155]
Из опроса: Иконки в разном стиле - некоторые выполнены обводкой, некоторые заливкой. Для некоторых очень давно нет размеров, только самый крупный, а он редко используется, потому что большинство иконок используется в кнопках, а не отдельностоящими.

**Comment by hell0anna** [comment]
https://www.figma.com/file/SLc0YGhuDotve6MTCBHlGxDU/Consta-Graphics?node-id=0%3A1
