### ISSUE TITLE
MultiCombobox: Состояние с заполненными тегами в несколько строк

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#2157]
Для multicombobox хочется чтобы было состояние с заполненными тегами в несколько строк, а не просто пустая строка  с крестиком - он так не выглядит - приходится каждый раз рисовать заполненный вид с компонентами tag и растягивать компонент в высоту.

**Comment by Ilyashis** [comment]
https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=76904%3A154850

**Comment by errorry** [comment]
добавлены заполненные multicombobox для всех тем
