### ISSUE TITLE
Icons: При замене одной иконки на другую не наследуются стили

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#2161]
По итогам опроса: "некоторые иконки забагованные. при замене одной на другую через swap instance не наследуются стили. скорее всего связано с неймингов векторных слоев"

**Comment by hell0anna** [comment]
иконки должны иметь один векторный слой с одним и тем же названием — **Vector** 
https://www.figma.com/file/SLc0YGhuDotve6MTCBHlGxDU/Consta-Graphics?node-id=0%3A1
