### ISSUE TITLE
Card: Добавить пример с хедером

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#2162]
Из опроса: "нет хедеров для карточки / раздела страницы, компонент достаточно типовый"
Нужно добавить пример в figma

**Comment by Lyubavskaya** [comment]
есть в best practices, нужно добавить ссылку

**Comment by arhayka** [comment]
Поставить ссылку на общий файл в Best Practices в Community, написать, куда смотреть
