### ISSUE TITLE
Гайд по дэшбордам и графикам

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#2240]

**Comment by hell0anna** [comment]
https://www.figma.com/proto/p4Hl43RIZrLQDg3lOQXiFM/%F0%9F%93%8A-%D0%93%D0%B0%D0%B9%D0%B4%D0%BB%D0%B0%D0%B9%D0%BD-%D0%BF%D0%BE-%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D0%BA%D0%B0%D0%BC?page-id=0%3A1&node-id=2%3A4&viewport=448%2C3715%2C0.77&scaling=min-zoom
