### ISSUE TITLE
Недоступен сайт с документацией DNS_PROBE_FINISHED_NXDOMAIN

### ISSUE THREAD

**Issue by lloydbanks** [consta-design-system/uikit#2248]
**Описание бага**
Не доступна ни одна ссылка как минимум с утра. Ни consta.design, ни consta.gazprom-neft.ru, ни uikit.gizeasy.ru, ни consta-uikit.vercel.app, снова поменялся урл?

![consta](https://user-images.githubusercontent.com/21862483/164461246-3e080e2b-ce94-45f2-a8fd-ac3f2b7b12bb.jpg)

**Параметры софта на компьютере:**

- ОС: Windows
- Браузер и его версия: Chrome последний

**Comment by Lyubavskaya** [comment]
Пока опять вся документация и стенды временно переехали сюда:  

@consta/uikit - [uikit.gizeasy.ru](http://uikit.gizeasy.ru)
@consta/charts - [charts.gizeasy.ru](http://charts.gizeasy.ru)
@consta/header - [header.gizeasy.ru](http://header.gizeasy.ru)
@consta/rc-table-adapter - [rc-table-adapter.gizeasy.ru](http://rc-table-adapter.gizeasy.ru)
@consta/rc-tree-adapter - [rc-tree-adapter.gizeasy.ru](http://rc-tree-adapter.gizeasy.ru)


А лендинг сюда: h[ttp://landing.gizeasy.ru/](http://landing.gizeasy.ru/)
