### ISSUE TITLE
[3279] Consta Table: Доработки resize & scroll

### ISSUE THREAD

**Issue by N1MBER** [consta-design-system/uikit#2250]
- [ ] Добавить свойство отвечающее за распределение свободного пространства:
- последнему столбцу (по умолчанию)
- задать номер столбца
- равномерно раскидать по всем столбцам
- [ ] Исправить баг со скроллом
<img width="1440" alt="Снимок экрана 2022-04-22 в 16 50 35" src="https://user-images.githubusercontent.com/44449561/164727809-1613058f-912f-47a3-96db-55e063d9c3ec.png">

<img width="1440" alt="Снимок экрана 2022-04-22 в 16 51 25" src="https://user-images.githubusercontent.com/44449561/164727965-9976b956-9755-452d-b11d-0baedf4574cb.png">

**Comment by gizeasy** [comment]
В новой таблице есть 2 режима распределения свободного пространства, плюс можно тонко настроить поведение ресайза для каждого столбца.
