### ISSUE TITLE
все компоненты, defaultProps

### ISSUE THREAD

**Issue by mirgorod-igor** [consta-design-system/uikit#2252]
прошу добавить тайпинг defaultProps для всех компонентов (Text, TextField, Tag, Badge, Button, Breadcrumbs, Icon)

![image](https://user-images.githubusercontent.com/44164795/165068349-a50c8fa7-6a85-4b23-a642-97c6b9d7c493.png)

сейчас ts compiler выдает ошибку, (приходится глушить комментом ts-ignore)

**Comment by lisaovcharenko** [comment]
@gizeasy проверь актуальность, пожалуйста
