### ISSUE TITLE
Icon: Геологические иконки (в отдельную пачку)

### ISSUE THREAD

**Issue by kolebayev** [consta-design-system/uikit#2258]

**Comment by Ilyashis** [comment]
Часть №1 - иконок для обьектов моделирования Сейсмики.
нужно отрисовать цветные иконки, для светлой и темной темы

![image](https://user-images.githubusercontent.com/76221581/168964183-e60dd786-2af6-4650-b4c8-b8c2c2db555f.png)

**Comment by Ilyashis** [comment]
Некоторые иконки могут быть иметь настраиваемые цвета

**Comment by Ilyashis** [comment]
размеры - s
xs и m - менее приоритетны

**Comment by hell0anna** [comment]
https://www.figma.com/file/ZFRh6p2whp9bPfrrKUQjie/Untitled?node-id=46%3A11472
первая итерация, нужно согласовать с Ильясом

**Comment by hell0anna** [comment]
переложила сюда
https://www.figma.com/file/SLc0YGhuDotve6MTCBHlGxDU/Consta-Graphics?node-id=23616%3A1669

**Comment by hell0anna** [comment]
финал
https://www.figma.com/file/SLc0YGhuDotve6MTCBHlGxDU/Consta-Graphics?node-id=3201%3A0
