### ISSUE TITLE
что со стендом?

### ISSUE THREAD

**Issue by AntonS86** [consta-design-system/uikit#2263]

**Comment by AntonS86** [comment]
В репу ссылки добавьте

**Comment by Lyubavskaya** [comment]
Переехали на https://uikit.consta.design/
В репах ссылки обновлены
•  @consta/uikit (https://uikit.consta.design/?path=/story/common-about--page) 
•  @consta/charts (https://charts.consta.design/?path=/story/common-start--page) 
•  @consta/header (https://header.consta.design/?path=/story/common-start--page) 
•  @consta/stats (https://stats.consta.design/?path=/story/common-start--page) 
•  @consta/rc-table-adapter
 (https://rc-table-adapter.consta.design/?path=/story/common-start--page)
•  @consta/ag-grid-adapter
 (https://ag-grid-adapter.consta.design/?path=/story/common-start--page)
•  @consta/gantt-task-react-adapter 
 (https://gantt-task-react-adapter.consta.design/?path=/story/common-start--page)
•  @consta/rc-tree-adapter (https://rc-tree-adapter.consta.design/?path=/story/common-start--page) 
•  @consta/gpn-responses (https://gpn-responses.consta.design/?path=/story/common-start--page) 
•  @consta/analytic-ui (https://analytic-ui.consta.design/?path=/story/common-start--page) 
•  @consta/widgets (https://widgets.consta.design/?path=/story/common-start--page)
