### ISSUE TITLE
Charts: Легенда. Изменить отступ между иконкой и текстом.

### ISSUE THREAD

**Issue by nixolympica** [consta-design-system/uikit#2272]
Раньше в легенде между иконкой и текстом был отступ 4px, в новой версии сделали 8px. Надо вернуть 4, иначе смотрится разорвано, слишком много воздуха. 

Также мастер легенд ведет на какой то сторонний документ, то есть мастер не в consta charts находится. 
![2022-04-29_13-28-17](https://user-images.githubusercontent.com/93970306/165928121-c8909bc4-fca2-4c57-8af4-bc23f7220a15.png)

![2022-04-29_13-11-43](https://user-images.githubusercontent.com/93970306/165927276-d9a38510-8bc5-4842-9c14-7cf8126cd97d.png)

**Comment by hell0anna** [comment]
привет, ссылки на мастер-компонент уже поправили, возможно обновление не долетело

**Comment by nixolympica** [comment]
Да, это я поправила, забыла перенести в done
