### ISSUE TITLE
Chart: Замечания после обновления графиков

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#2305]
1. Серая линия так же должна быть по середине ноля? 
![image](https://user-images.githubusercontent.com/75978078/169143969-c46fcee5-6b5b-4f8f-8ae0-ba05b775aa96.png)
2. В легендах расхождение, верхняя легенда - это я из файла кончтачартс скачала, нижняя - из assets, верхняя 8 px расстояние, нижняя 4 
![image](https://user-images.githubusercontent.com/75978078/169144061-3971e515-5189-4a62-8cd8-484abe94a2ed.png)
3. Так же в новых графиках не нашла, как регулировать положение легенды относительно графика, в примерах ввиду только позиционирование сверху, как настроить легенду снизу или справа как список?
4. И ещё важный момент, на столбчатых диаграммах, отображение значения только внутри столбца, а у нас заказчик просит делать сверху  над столбиком, тоже не нашла таких вариантов в консте. Или у нас тех ограничение и число может отображаться только внутри столбца по середине?
5. Про хвостики у шкалы - вот тут получается что и полосочки и цифры выровнены по высоте бокса, но по сути по боксу надо выровнять цифры а хвостики по центру цифр. Верней. тут только у крайних цифр выровнен хвостик не по их центру. 
![image](https://user-images.githubusercontent.com/75978078/169144477-66eaca2e-b14e-4f0f-8085-9a668d621931.png)
6. Когда выбираю в сетке графика значение 5 делений, то полоски становятся толще, при любых других значениях все ок, тоненькие как везде. 
![image](https://user-images.githubusercontent.com/75978078/169144621-42e6fbc3-5dc3-40b4-9ac1-385485d77977.png)
![image](https://user-images.githubusercontent.com/75978078/169144653-67283007-879e-4982-8b0b-fd3c784a4b0c.png)
нашла в чем причина толстых линий - только в значении 5 в настройке позиционирования обводки указано Inside, а во всех других - centre
7. Очень важный момент, надо что то сделать с отображением значений в столбчатого диаграмме. Нам необходимо выводить значения над столбцом, А оказывается, максимальное значение будет обрезано сеткой графика. Можно ли это как то в консте докрутить? (тут необходимо уточнить у разработчика, ишью https://github.com/consta-design-system/charts/issues/59)

**Comment by hell0anna** [comment]
так же этих багов касается задача https://github.com/consta-design-system/uikit/issues/2305

При отключенном GridBody пересечение осей X и Y выглядит криво
Варианты:
- при отключенном GridBody, убирать краевые значения шкал (нежелательно, лучше избежать)
- перепридумать логику наложения шкал на GridBody, возможно сделать с нахлестом как в геологических графиках. Тогда цвет шкалы должен быть без прозрачности

<img width="454" alt="image" src="https://user-images.githubusercontent.com/51019093/166686813-596fbd86-7bfc-48d4-a497-510e8b118ea4.png">
<img width="426" alt="image" src="https://user-images.githubusercontent.com/51019093/166687142-1af2b3f1-c380-45d1-8a4c-9a6d31a501b0.png">

**Comment by hell0anna** [comment]
- [ ] 1
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [ ] 6
- [ ] 7

**Comment by kolebayev** [comment]
+ задача https://github.com/consta-design-system/uikit/issues/2281

@hell0anna
