### ISSUE TITLE
Портал: Компонеты MDX формата

### ISSUE THREAD

**Issue by gizeasy** [consta-design-system/uikit#2327]
сделать все компоненты из [списка](https://mdxjs.com/table-of-components/)

возможно стоит вынести в отдельную библиотеку @consta/typography
в ней описать все компоненты и сделать обвязку для быстрой использования с [@mdx-js/react](https://mdxjs.com/packages/react/)

**Comment by linturaven** [comment]
#1230 Закончили с этой задачей, @gizeasy чекни свою часть по MDX формату здесь: https://www.figma.com/file/wNIi9rZl30Uq1IPBJRubsl/Consta-Font-Styles?node-id=0%3A1
