### ISSUE TITLE
Text: уменьшить шрифт на 1 пункт

### ISSUE THREAD

**Issue by kolebayev** [consta-design-system/uikit#2331]
>  уменьшить размер шрифта везде на 1 пункт, например, M- не 16, а 15, S - не 14, а 13. Поскольку шрифт Inter сам по себе имеет чуть большую высоту, чем Segoe. В итоге при одном размере, мы видим явное различие

- [ ] рисерч
- [ ] в дизайне
- [ ] в коде

**Comment by nixolympica** [comment]
![2022-05-25_15-23-53](https://user-images.githubusercontent.com/93970306/170261700-8e08d723-49b8-40e8-9442-1f5b61b42389.png)
![2022-05-25_15-25-39](https://user-images.githubusercontent.com/93970306/170261708-82371387-d5bd-4024-a9d3-c0e55bd0993d.png)
![2022-05-25_15-22-36](https://user-images.githubusercontent.com/93970306/170261712-ec5e7f09-8223-4ef3-8c27-2f0fbb25b4ab.png)

**Comment by gizeasy** [comment]
Решили не делать, возникнут проблемы на проектах в которых нет необходимости в уменьшении шрифта.
