### ISSUE TITLE
GeoKit: 3D Scatter реализация

### ISSUE THREAD

**Issue by kolebayev** [consta-design-system/uikit#2334]
см прошлую задачу
https://github.com/consta-design-system/uikit/issues/2299

**Comment by Ilyashis** [comment]
https://www.figma.com/file/deD46VCwleYNjUYr1PRQtj/Consta-Geo-Kit?node-id=520%3A14130

**Comment by Ilyashis** [comment]
Добавлен компонент - GraphScaleIsometric Default Theme
Странаница - Parts
Файл - https://www.figma.com/file/deD46VCwleYNjUYr1PRQtj/Consta-Geo-Kit?node-id=5%3A8

**Comment by Ilyashis** [comment]
Добавлен компонент - 3D Scene
Пример - Seicmic Cube
Страница - 3D View
Файл - https://www.figma.com/file/deD46VCwleYNjUYr1PRQtj/Consta-Geo-Kit?node-id=520%3A14130
