### ISSUE TITLE
Пример интерфейса на consta (дашборд)

### ISSUE THREAD

**Issue by gizeasy** [consta-design-system/uikit#2347]

**Comment by linturaven** [comment]
https://www.figma.com/file/l6rdF0guIdH3ZDXSoehuqz/Consta-UI-Kit%3A-Best-Practices?node-id=1314%3A14093

@kolebayev готово

<img width="664" alt="Снимок экрана 2022-06-22 в 13 50 26" src="https://user-images.githubusercontent.com/94055055/175011647-58b675e2-5b61-42ec-bfd9-6d1891b30339.png">
