### ISSUE TITLE
slider: ползунок не успевает за мышкой 

### ISSUE THREAD

**Issue by monolithed** [consta-design-system/uikit#2378]
Slider во всех [примерах](https://uikit.consta.design/?path=/docs/components-slider--playground) жутко тормозит, ползунок не успевает за мышкой

https://user-images.githubusercontent.com/803674/172805494-535564db-f741-44de-b00e-d10f843e7ba1.mov

**Comment by N1MBER** [comment]
Закрыто в версии v3.26.0
