### ISSUE TITLE
[3279] Consta Table: Адаптив на изменение ширины экрана

### ISSUE THREAD

**Issue by vovijan** [consta-design-system/uikit#2380]
При изменении ширины экрана не адаптируются элементы внутри компонента <Table /> и <Layout />
![photo_2022-06-09_11-30-05](https://user-images.githubusercontent.com/31822850/172858705-03e3dd19-7dba-46ce-86e6-98c5777fcd13.jpg)
![photo_2022-06-09_11-30-03](https://user-images.githubusercontent.com/31822850/172858718-33b34c6f-7b9d-4435-9321-eb5011c25bb2.jpg)

**Comment by gizeasy** [comment]
готово в новой таблице
