### ISSUE TITLE
storybook: Дергается пример со Steps

### ISSUE THREAD

**Issue by monolithed** [consta-design-system/uikit#2385]
https://user-images.githubusercontent.com/803674/173405745-e906f468-da07-4087-983a-5ba2a9fef2c8.mov

[Активным](https://uikit.consta.design/?path=/story/components-steps--playground) должен быть только выбранный элемент, а не вся строка

**Comment by gizeasy** [comment]
не трогаем

**Comment by monolithed** [comment]
@gizeasy, почему? Выглядит как баг

**Comment by gizeasy** [comment]
> @gizeasy, почему? Выглядит как баг

Шрифт не имеет одинаковой ширины при разных начертаниях. Если высчитывать запас, то линия будет чуть больше чем шрифт. Ну и дизайн такой.

**Comment by monolithed** [comment]
@gizeasy посмотри как [тут ](https://ant.design/components/steps/#components-steps-demo-nav) сделано

**Comment by monolithed** [comment]
Сторибук — лицо проекта с идеальными условиями, там ничего не должно дергаться
