### ISSUE TITLE
Pagination: Обрезаются значения при lazy подгрузке

### ISSUE THREAD

**Issue by dropex7** [consta-design-system/uikit#2393]
**Описание бага**
При ленивой подгрузке компоненты `<Pagination />` стили элементов не успевают подгружаться, поэтому они перезатираются стилями кнопки и трехзначные номера страниц обрезаются.
Пример бага представлен тут: https://codesandbox.io/s/intelligent-blackwell-62hetc?file=/src/Test.jsx

![image](https://user-images.githubusercontent.com/32023430/174072250-d90a17c2-7d58-4a16-99f1-7d8a0975cca5.png)
 
**Версия Consta Kit* - 3.24.5*

**Параметры софта на компьютере:**

- ОС: Ubuntu 22.04
- Браузер и его версия: Google chrome Version 102.0.5005.115 (Official Build) (64-bit)

**Comment by gizeasy** [comment]
Возможно нужно в зависимости от ширины контейнера прятать элементы а не как сейчас в зависимости от пропса
