### ISSUE TITLE
GallerySlider: Слайдер галереи новый компонент

### ISSUE THREAD

**Issue by hell0anna** [consta-design-system/uikit#2399]
есть запрос на такую листалку галереи

![telegram-cloud-document-2-5300759151079594962](https://user-images.githubusercontent.com/51019093/174801356-60e6ba3d-61f2-4941-bc00-541c589988a4.jpg)

нужно провести ресеч насколько часто используем такое в проектах, и понять нужен ли нам такой компонент
ресеч согласован с @linturaven =))))))))

**Comment by MyasoutovaTatiana** [comment]
Провели ресерч и пришли к выводу, что есть необходимость и запрос от дизайнеров разработать данный элемент.
<img width="730" alt="Снимок экрана 2022-07-20 в 15 36 39" src="https://user-images.githubusercontent.com/108055994/180256422-432edd39-5791-43c9-826b-df5f6fecc673.png">

**Comment by Ilyashis** [comment]
https://www.figma.com/file/LKYyjgQ3khFHvXraZAG1n1/Consta-Components?node-id=2233%3A103376

**Comment by Lyubavskaya** [comment]
Дизайн готов https://www.figma.com/community/file/1045349329378392766
