### ISSUE TITLE
FieldGroup: Добавить примеры с компонентом в Figma

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#2400]
Добавили новый компонент FieldGroup, который склеивает несколько элементов формы — например, два поля или поле и кнопку. Не нужно думать про позиционирование элементов, проставлять отступы и скругление, компонент сделает всё сам. Использовать можно будет для любых элементов, у которых есть свойство form — TextField, Button, Select, UserSelect, Combobox, DatePiker и похожих.
https://uikit.consta.design/?path=/docs/components-fieldgroup--playground

В фигме по нему ничего нет. Нужно добавить примеры в Best Practices, в ui-ките сделать моковый компонент, сделать перекрестные ссылки на Best Practices

**Comment by Ilyashis** [comment]
https://www.figma.com/file/u4fDZ5rdcEoJUZ7cITlVJx/Github-issues?node-id=2477%3A35350
