### ISSUE TITLE
BigCalendar: Дизайн компонента и разработка

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#2402]
https://fullcalendar.io/

**Comment by linturaven** [comment]
http://jquense.github.io/react-big-calendar/examples/index.html?path=/story/about-big-calendar--page

Выбрали этот

**Comment by linturaven** [comment]
@N1MBER готово, лежит здесь: https://www.figma.com/file/LKYyjgQ3khFHvXraZAG1n1/Consta-Components?node-id=1336%3A68963
