### ISSUE TITLE
storybook: Картинки в обзор для новых компонентов

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#2446]
аватар груп

**Comment by errorry** [comment]
https://www.figma.com/file/u4fDZ5rdcEoJUZ7cITlVJx/Github-issues?node-id=1696%3A7232

**Comment by Lyubavskaya** [comment]
Новый компонент: https://uikit.consta.design/?path=/docs/components-avatargroup--playground
