### ISSUE TITLE
Checkbox: добавить новые размеры

### ISSUE THREAD

**Issue by errorry** [consta-design-system/uikit#2456]
Необходимо добавит новый размер S (возможно XS) для разработки других компонентов, например droplist для combobox

**Comment by errorry** [comment]
Добавлен размер S для всех тем, компонент находится в Github-issues:

https://www.figma.com/file/u4fDZ5rdcEoJUZ7cITlVJx/Github-issues?node-id=2554%3A48262

**Comment by linturaven** [comment]
Всё хорошо, но нужно поправить свойства у вариантов (выползает ошибка Conflicting Variants) и можно переносить в UI-Kit
