### ISSUE TITLE
Ревью портала

### ISSUE THREAD

**Issue by gizeasy** [consta-design-system/uikit#2502]

**Comment by N1MBER** [comment]
В теге code текст вылезает за размеры окна
<img width="1061" alt="Снимок экрана 2022-08-15 в 19 17 12" src="https://user-images.githubusercontent.com/44449561/184673775-400e162c-a125-4f53-9bb3-dbe69bf7d6dc.png">

**Comment by gizeasy** [comment]
дизайнеру и разрабодчику ссылки поменять местами

**Comment by gizeasy** [comment]
при генерации стендов надо добавит их предварительное удаление

**Comment by gizeasy** [comment]
![image](https://user-images.githubusercontent.com/13190808/184872908-fe26a323-503f-4032-8021-74b7e48f4829.png)
выделяюся сразу несколько активных пунктов если пункты называются одиногоко

**Comment by gizeasy** [comment]
sidebar анимация открытия сломалась

**Comment by gizeasy** [comment]
при клике на сслку около заголовка появляется ошибка
```
main.ba509ca5.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'writeText')
```

![image](https://user-images.githubusercontent.com/13190808/184880823-41487d98-947d-442e-b0dc-b7f30e11ed7d.png)

**Comment by gizeasy** [comment]
не хорошо выглядит ссылка на заголовке, она прилипла к тексту а на мобильных устройствах прилипла к краю экрана и заголовку

**Comment by gizeasy** [comment]
Modal, ThemeToggler: обновить тесты

**Comment by gizeasy** [comment]
![image](https://user-images.githubusercontent.com/13190808/184887277-84fb03b8-87fc-433b-b1fd-8447243ee94f.png)
в коде при одной строчке блок кнопки вылазит за пределы

**Comment by gizeasy** [comment]
modal сломалась анимация открытия

**Comment by gizeasy** [comment]
сортировка компонентов на странице обзора

**Comment by gizeasy** [comment]
подумать о скрытии табов в которых нет ни каких данных

**Comment by gizeasy** [comment]
оформление страници обзора

**Comment by gizeasy** [comment]
добавить в картинки компонентов переменные, чтоб они подстраивались под тему

**Comment by N1MBER** [comment]
Не работают ссылки на библиотеки в таблицах
| [`anchorRef`](#прикрепление-к-якорю)      | `React.RefObject<HTMLElement>`        | -            | см. [Popover] (##LIBS.STAND| stand:uikit-components-popover-stable) |
разделитель  между LIBS.STAND и stand воспринимается за колонку

**Comment by gizeasy** [comment]
![image](https://user-images.githubusercontent.com/13190808/185148815-941b7faf-1b8a-49ac-b30f-61e077dafbd8.png)
поправить z-index у шапки

**Comment by arhayka** [comment]
Левое меню:
- [ ] хуки, хоки и миксины в конце, до них фиг докрутишь и никак не узнать, что они там есть.
- [ ] кнопка Обзор выехала из компонентов, непонятно, обзор чего. Переименовать в **Обзор компонентов** или **Все компоненты**
- [ ] сделать у меню побольше отступ снизу, сейчас нижняя ссылка прилипает, закрывается системными сообщениями и пр.

**Comment by gizeasy** [comment]
блок `Полезная информация?` скрыть так как не работает

**Comment by gizeasy** [comment]
Эта статья `в репозитории` на Github должна вести на конкретный файл с докой

**Comment by arhayka** [comment]
Нужно добавить стили для примечания в маркдауне.

> Это примечание, его нужно стилизовать

**Comment by arhayka** [comment]
Ссылка на деприкейтнутую доку из стабильной не работает.

**Comment by arhayka** [comment]
Нужно поставить ссылку наоборот, из деприкейтнутой доки на стабильную.

**Comment by gizeasy** [comment]
https://github.com/react-syntax-highlighter/react-syntax-highlighter

уменшить размер `react-syntax-highlighter`

**Comment by gizeasy** [comment]
добавить фавиконку

**Comment by gizeasy** [comment]
добавить css лоадер пока грузится JS

**Comment by gizeasy** [comment]
highlighter тришейпнул, и более тонко настроил, теперь он по разному парсит css, js, json
но необходимо создат тему для него 1 в 1 как стандартная но на наших переменных

**Comment by arhayka** [comment]
сделать примеры адаптивными (и сверстать на консте заодно)

**Comment by arhayka** [comment]
Под вопросом: когда уходишь со страницы компонента и возвращаешься по кнопке назад, левое меню уезжает к началу. Если компонент в конце, до него далеко крутить. Вот даже не знаю, бага ли это, но неудобно :)

**Comment by arhayka** [comment]
layout: в примерах нет границ между блоками (их и в сторибуке нет почему-то, но поправить нужно).

**Comment by N1MBER** [comment]
Добавить разделение стабильные и деприкейтед версии в обзоре

**Comment by gizeasy** [comment]
![image](https://user-images.githubusercontent.com/13190808/185591104-bfdbca84-b2e9-494f-9442-35e9642d0420.png)
в темной теме все поповеры думают что они в белой
проблема из-за ого что @consta/stand контекст из npm пакета а в самих доках из репозитория
2 вариана решения:
1) Алиасы впри сборки
2) сделать обертку для документов в который кидать тему из атома в @consta/stand

**Comment by arhayka** [comment]
Нужно увеличить отступы вокруг примеров. Например, между примером и следующим заголовком. Как это правильно сделать: внутри примера, в стилях заголовка, в стилях примера , и то, и то?

<img width="1437" alt="Screenshot 2022-08-22 at 11 52 16" src="https://user-images.githubusercontent.com/12581569/185881426-9a28a474-b511-4e83-b788-4c9796fa941f.png">

**Comment by gizeasy** [comment]
лоадер на фигме должен быть по центру

**Comment by gizeasy** [comment]
удалить пустые докменты mdx

**Comment by N1MBER** [comment]
> ![image](https://user-images.githubusercontent.com/13190808/185591104-bfdbca84-b2e9-494f-9442-35e9642d0420.png) в темной теме все поповеры думают что они в белой проблема из-за ого что @consta/stand контекст из npm пакета а в самих доках из репозитория 2 вариана решения:
> 
> 1. Алиасы впри сборки
> 2. сделать обертку для документов в который кидать тему из атома в @consta/stand

2. Пункт не работает, попробовал использовать тему из атома в темплейтах и по итогу проблема остается

**Comment by arhayka** [comment]
SnackBar добавить хотя бы один нормальный интерактивный пример. Сейчас как-то вообще непонятно, что оно делает и зачем оно нужно.

**Comment by arhayka** [comment]
Table: перенести примеры из сторибука, там часть примеров в  stories.

**Comment by gizeasy** [comment]
не показывать переключаль `Показывать deprecated` если нет таких компонентов

**Comment by gizeasy** [comment]
не показывать обзор если всего один компонент и переадресовывать на этот компонент

**Comment by arhayka** [comment]
На вкладке **Дизайн** убрать фразу **раздел в разработке** при генерации стенда, если:
- ссылка на фигму есть
- файлика design в папке __stand__ нет

**Comment by gizeasy** [comment]
```
import {
  RemadeInfo,
  RemadeTableInfo,
} from '##/stand/components/RemadeInfo';
```
в mdx файлах не работают пути через `##`

**Comment by gizeasy** [comment]
`*.stand.ts` не попадает в сборку только `*.stand.tsx`

**Comment by arhayka** [comment]
если в стенде не указан 'status', в урл на странице компонента добавляется undefined

**Comment by arhayka** [comment]
Если в заголовке есть точка, MdxMenu в правом сайдбаре не генерируется. Пример в Как подключить свой пресет.

**Comment by arhayka** [comment]
передавать массив с вкладками, и называть их как угодно

**Comment by arhayka** [comment]
На стедне 0.0.32 сломался поиск по компонентам.

**Comment by arhayka** [comment]
Добавить флаг компонентам, которые надо/не надо показывать в обзоре.

**Comment by arhayka** [comment]
В обзоре компонентов нужна возможность добавить заголовок и описание сверху: заголовок, пару слов о том, что это за библиотека, ссылку на гитхаб и пр.

**Comment by gizeasy** [comment]
`useSelect` при выборе нулевого элемента, `value` не отображается

также если в  опции `Select` `lable` это пустая строка то опция короткая по высоте

<img width="643" alt="image" src="https://user-images.githubusercontent.com/13190808/194856532-2a45c38d-f6ac-43e2-8b9a-e96aec44d7ba.png">

**Comment by arhayka** [comment]
Поправьте тире и добавьте точку, плиз)

Предлагайте доработки - будем рады контрибьюторам —> Предлагайте доработки — будем рады контрибьюторам.

**Comment by arhayka** [comment]
А у примечания точно такие маленькие отступы должны быть? Выглядит странно
<img width="955" alt="Screenshot 2022-10-12 at 14 48 59" src="https://user-images.githubusercontent.com/12581569/195335545-0983c342-ed0f-4fe3-a4b4-5507943989ce.png">

**Comment by arhayka** [comment]
В File добавить примеры расширений, для которых есть иконки — списком куда-то вывести. Можно в варианты тоже, но список нужен.

**Comment by Lyubavskaya** [comment]
https://github.com/consta-design-system/uikit/issues/2691 Portal: Нет кнопки меню в разрешении 1366х768

**Comment by Lyubavskaya** [comment]
Поправить фавикон на всех стендах

**Comment by arhayka** [comment]
Оч большой отступ между строкой перед списком и самим списком. В идеальном мире должно быть два типа отступов:
- как внутри абзаща, если список идет сразу после строки (это частая история)
- как перед абзацем, если список идет отдельно.
<img width="1435" alt="Screenshot 2022-10-13 at 11 06 07" src="https://user-images.githubusercontent.com/12581569/195539117-f2bf9941-fc59-4f0d-b5e0-f6b754bdf6b4.png">

**Comment by arhayka** [comment]
Добавить сандбокс к [FeedbackForm](https://analytic-ui.consta.design/libs/analytic-ui/components-feedbackform-stable)

**Comment by N1MBER** [comment]
> layout: в примерах нет границ между блоками (их и в сторибуке нет почему-то, но поправить нужно).

https://github.com/consta-design-system/uikit/pull/2705

**Comment by Lyubavskaya** [comment]
Нет песочницы  AutoComplete

**Comment by gizeasy** [comment]
![image](https://user-images.githubusercontent.com/13190808/196935784-8750ac20-5a60-4ea9-8f32-81f7da996f46.png)

пункты только одной библиотеки, по хорошему бы еще в скрол это все дело завернуть

**Comment by gizeasy** [comment]
избавиться от createaRouter, в нем нет необходимости

**Comment by Lyubavskaya** [comment]
В компоненте Badge "Раздел в разработке" ![image](https://user-images.githubusercontent.com/75978078/197028554-31a6f7e9-03f4-4152-9874-912c610c5ceb.png)

**Comment by gizeasy** [comment]
![image](https://user-images.githubusercontent.com/13190808/197155739-33868236-d5f2-4896-ab2b-9d8543de2b5d.png)

выводить переключатели если вообще присутствуют такие компоненты в библиотеке

**Comment by N1MBER** [comment]
Автоматически открывать меню при переходе на страницу через хедер

**Comment by N1MBER** [comment]
При открытом состоянии при первом рендере он должен открываться без раскрытия (анимации)

**Comment by Lyubavskaya** [comment]
Страница Библиотеки, первые 2 абзаца - поправить съехавшее тире и точку.

**Comment by N1MBER** [comment]
https://github.com/consta-design-system/uikit/issues/2648

**Comment by Lyubavskaya** [comment]
Почему-то "раздел в разработке" https://portal.consta.design/libs/portal/about-aboutconsta

**Comment by Lyubavskaya** [comment]
> 

Так и не работает пока

**Comment by Lyubavskaya** [comment]
В списке библитек, может, Consta icons повыше сделать, после Основных библиотек. Или вообще в основные библиотеки включить

**Comment by Lyubavskaya** [comment]
Кликабельные карточки в списке библиотек 
![image](https://user-images.githubusercontent.com/75978078/204520132-3b190713-d787-4f1a-bbb1-bb24054a9893.png)

**Comment by Lyubavskaya** [comment]
Нет ссылки "Открыть на гитхаб" в карточке Иконки в списке библиотек

**Comment by Lyubavskaya** [comment]
В Consta Widgets нет раздела Документация в левом меню

**Comment by Lyubavskaya** [comment]
Косячный лоадер на вкладке Дизайнерам (после нажатия на кнопку "Я хочу увидеть компонент"
![image](https://user-images.githubusercontent.com/75978078/204524616-6afa22e9-9964-49a1-ab06-5fa69fa555e3.png)

**Comment by Lyubavskaya** [comment]
Badge не отображается на портале 
![image](https://user-images.githubusercontent.com/75978078/204905790-18842833-7c31-4a2f-b3ef-6aabe0924376.png)

**Comment by gizeasy** [comment]
Реализовать, авто проверку версии пакетов и портала, если версии отличаются то обновлять сраницу

**Comment by Lyubavskaya** [comment]
Добавить выбор дисплейной темы

**Comment by hell0anna** [comment]
в ссылке на переключатель тем в разделе Тематизация ошибка:
<img width="324" alt="image" src="https://user-images.githubusercontent.com/51019093/207595336-47b8cc03-3eaa-4b5a-afde-d380a307e7db.png">

ссылка там такая https://consta.design/libs/portal/components-themetoggler-stable

**Comment by Lyubavskaya** [comment]
![image](https://user-images.githubusercontent.com/75978078/209010258-5ccb8904-e326-4b3b-addd-45f09af84c22.png)

**Comment by gizeasy** [comment]
> Добавить выбор дисплейной темы

Думаю пока не надо, у нас будет редизайн и там кажется это место будем трогать

**Comment by N1MBER** [comment]
<img width="297" alt="Снимок экрана 2023-01-20 в 10 57 20" src="https://user-images.githubusercontent.com/44449561/213645214-04e4cacb-6afc-4eeb-a5ea-057a9e389c79.png">
Растянуть контейнер названия в карточке (в обзоре) на 100%

**Comment by Lyubavskaya** [comment]
Бесконечная загрузка на вкладке дизайнерам 
![image](https://user-images.githubusercontent.com/75978078/214833042-4f8e37f6-ba19-4e68-bbc4-81acb4908dac.png)

**Comment by BagenovA** [comment]
Страница: https://portal.consta.design/libs/uikit/components-autocomplete-canary

1. Вкладка Разработчикам, пункт Тип поля - поправить маркированный список (отображается некорректно)
2. Гиперссылка Форма списка - неактивна
3. Пункт Поиск - убрать из Содержания
4. Добавить в Содержание гиперссылку на пункт Пример

**Comment by BagenovA** [comment]
Страница: https://portal.consta.design/libs/uikit/components-breadcrumbs-stable

1. Исправить текст во вкладке Обзор. Исправить на: Компонент, который используется для навигации по страницам. Breadcrumbs позволяют проследить путь к странице, на которой находится пользователь и перейти к другим.
2. Вкладка Разработчикам, пункт Пример использования - гиперссылка неактивна, на самой странице пример не выделен в блок с таким заголовком.

**Comment by Lyubavskaya** [comment]
В кнобе Size расположить варианты размеров от меньшего к большему (xs, s, m, l и т.д.) - для всех компонентов

**Comment by Lyubavskaya** [comment]
Скроллы на витрине rcTreeAdapter: 
![image](https://user-images.githubusercontent.com/75978078/218508364-be0c2d94-7c4f-4dfe-8d38-fd5ac72b55f3.png)

**Comment by BagenovA** [comment]
Страница: https://portal.consta.design/libs/uikit/components-card-stable

1. Пункт Форма. Некорректный текст на примерах карточек. Может лучше так: Первый вариант и Второй вариант
2. Примеры пунктов Тень и Граница перепутаны (поменять местами)
3. Примеры карточек с границами и без границ: оба примера сейчас с границами
4. В пункте Адаптивность указать под примерами разрешения экранов

**Comment by BagenovA** [comment]
Страница: https://portal.consta.design/libs/uikit/components-checkboxgroup-stable

1. Пункт Внешний вид: примеры видов выглядят идентично. Название вида группы чекбоксов лучше писать над примером, а не под ним (так как примеры идут друг за другом).

**Comment by BagenovA** [comment]
Страница: https://portal.consta.design/libs/uikit/components-collapse-stable

1. Гиперссылка Пример использования (в Содержимом) неактивна
2. Пункт Расположение иконки: в примере с иконкой справа, текст находится далеко от иконки.

**Comment by BagenovA** [comment]
Страница: https://portal.consta.design/libs/uikit/components-combobox-stable

1. При клике на верхние пункты Содержимого, оно (Содержимое справа) перемещается вместе с контентным полем страницы
2. Пункты Поиск и Неактивный выпадающий список идут на странице не попорядку.

**Comment by N1MBER** [comment]
От @BagenovA Проверить корректность прокрутки контентной области и Содержимого. Пример: при нажатии на ссылку "Дополнительная информация" и на некоторые ссылки ниже, содержимое слишком прокручивается наверх и пользователь уже не видит ссылки и (или) блока в содержимом откуда он перешёл в конкретный блок страницы (то есть иногда блок в контентной области и соответвующая часть содержимого находятся не на одном уровне, приходится снова крутить наверх). Проблема встречается на портале не первый раз, возможно это связано с большим списком Содержимого.

**Comment by Lyubavskaya** [comment]
- [ ] Скролл в safari
- [ ] Правки согласно дизайну по мобильной версии
- [ ] На большом экране группу ссылок на на фигму, гитхаб и сандбокс переместить вправо согласно дизайну
- [ ] На вкладке Разработчикам не четко отрабатывают переходы по пунктам в навигации в правой части экрана

**Comment by Lyubavskaya** [comment]
Header: пометить как устаревший https://github.com/consta-design-system/uikit/issues/2971

**Comment by BagenovA** [comment]
![image](https://user-images.githubusercontent.com/121568340/230620883-d532b74c-9a59-4b2f-bc50-39e28a961638.png)

**Comment by BagenovA** [comment]
Заменить эмодзи на иконки

![image](https://user-images.githubusercontent.com/121568340/230621122-ad8cf181-499c-44a8-a38e-34f7fa7eaadc.png)

**Comment by BagenovA** [comment]
Проверить корректность расположения элементов, перегружен верх

![image](https://user-images.githubusercontent.com/121568340/230621418-31e98a13-7640-48b4-96e3-03c6c44e3c53.png)

**Comment by Lyubavskaya** [comment]
Cделать библиотеки в суперобзоре по-умолчанию раскрытыми.

**Comment by linturaven** [comment]
<img width="937" alt="Снимок экрана 2023-05-04 в 18 26 28" src="https://user-images.githubusercontent.com/94055055/236254994-c0f49831-f091-4e4c-ba5e-85e086b8cd24.png">
Кажется, что потерялись ссылки на фиргму в суперобзоре

**Comment by linturaven** [comment]
<img width="427" alt="Снимок экрана 2023-05-04 в 18 31 18" src="https://user-images.githubusercontent.com/94055055/236256110-2529e315-ad33-40c5-8715-50eed17aacfe.png">
Неправильный размер стрелки в кнопке

**Comment by linturaven** [comment]
<img width="402" alt="Снимок экрана 2023-05-04 в 18 31 48" src="https://user-images.githubusercontent.com/94055055/236256243-7e19e7a4-5093-45d4-adac-2262bfdb7dfa.png">
Кажется, что потерялась кнопка с изменением вида в свёрнутом виде

**Comment by linturaven** [comment]
<img width="352" alt="Снимок экрана 2023-05-04 в 18 36 29" src="https://user-images.githubusercontent.com/94055055/236257420-96f29206-3009-4b02-bb04-221f43b37742.png">
Вес шрифта в пунктах некорректный, см. левое меню и спеку по правому сайдбару

**Comment by linturaven** [comment]
<img width="896" alt="Снимок экрана 2023-05-04 в 18 42 40" src="https://user-images.githubusercontent.com/94055055/236258958-b73d42ef-d45e-45d3-ad61-5bc1925f98b4.png">
Что-то не так с весом шрифта, надо созвониться

**Comment by BagenovA** [comment]
Вместо "Документация дизайн-системы" оставить заголовок "Обзор". Когда обсуждали редизайн, хотели отказаться от формулировки "Документация".

[image](https://drive.google.com/file/d/16iMP9wB8vmXHamEitCqydyRwmhIMbOaS/view?usp=sharing)

**Comment by gizeasy** [comment]
Пропали тултипы 
![image](https://github.com/consta-design-system/uikit/assets/13190808/90c1efa7-4ccd-4cb7-a780-d1437281bbda)

**Comment by gizeasy** [comment]
Описание не верное
![image](https://github.com/consta-design-system/uikit/assets/13190808/be98bc36-8fdb-4def-a1d9-ba5dc52f972c)

**Comment by gizeasy** [comment]
по умолчание компоненты адаптеры и специальные компоненты надо развернуть

**Comment by BagenovA** [comment]
Вкладки "уехали" в правую часть контентной области

![image](https://github.com/consta-design-system/uikit/assets/121568340/51e37407-9073-4de1-8bbd-3b9a604eef82)
]

**Comment by Lyubavskaya** [comment]
На страницах:https://consta.design/libs/portal/guidelines-fontinter https://consta.design/libs/portal/contributers-owerview

**Comment by Lyubavskaya** [comment]
В Charts пропали ссылки на Figma
![image](https://github.com/consta-design-system/uikit/assets/75978078/a7acde0b-7085-47c1-a0d8-0bfc65191db6)

**Comment by Lyubavskaya** [comment]
Нет витрины у FileField: https://consta.design/libs/uikit/components-filefield-stable

**Comment by gizeasy** [comment]
![telegram-cloud-photo-size-2-5440898625824737725-y](https://github.com/consta-design-system/uikit/assets/13190808/86987a32-d4d2-4be3-9600-01a09d781010)

**Comment by Lyubavskaya** [comment]
- [ ] Добавить ссылку на канал в Телеграм в соответствии с дизайном 
- [ ] Отступы в левом меню в соответствии с дизайном
