### ISSUE TITLE
Button: Использовать <input type="submit">

### ISSUE THREAD

**Issue by manazoid** [consta-design-system/uikit#2569]
**Описание фичи или улучшения**
HTML тег <form> может иметь внутри себя <input type="submit"> для подтверждения отправки формы. Но <Button as={"input"} type="submit"> не работает как ожидалось. <Button type="submit"> отправляет форму корректно, так что это является незначительным улучшением.

**Почему улучшение или фича необходима?**
Предполагается, что какой-нибудь новичок будет использовать такой синтаксис. И было бы удобно использовать вариант as="input" без вызыва ошибок. Чтобы можно было писать как <Button as={"input"} type="submit">, так и <Button type="submit">. И все работало корректно.

**Дополнительная информация**
Кстати type="submit" содержит локализированную надпись "Отправить" в зависимости от языка браузера. То есть необходимости писать в внутри тега Button текст на кнопке.

**Comment by AntonS86** [comment]
работает!!!
<form onSubmit={() => {}}>
<Button
            view="ghost"
            size="s"
            type="submit"
            label="Отправить"
            disabled={!isValid}
            loading={isSubmitting}
          />
   </form>       
для type submit нужны тэги <form ></form>

**Comment by Lyubavskaya** [comment]
@AntonS86 спасибо

**Comment by manazoid** [comment]
> работает!!!
> 
> ```
> <form onSubmit={() => {}}>
> <Button
>             view="ghost"
>             size="s"
>             type="submit"
>             label="Отправить"
>             disabled={!isValid}
>             loading={isSubmitting}
>           />
>    </form>       
> ```
> 
> для type submit нужны тэги
> 
> ```
> <form ></form>
> ```

Вы не читали мой вопрос внимательно, а гитхаб после публикации похерил мое описание: внимание на as="input", хотелось бы иметь возможность использовать input type="submit", а не только button type="submit".

**Comment by manazoid** [comment]
@AntonS86 чтобы в двух вариантах это работало одинаково
