### ISSUE TITLE
Portal: Дизайн обзорной страницы + картинки

### ISSUE THREAD

**Issue by gizeasy** [consta-design-system/uikit#2577]

**Comment by arhayka** [comment]
Когда доберешься до этого, посмотри, плиз, не только обзор в uikit, но еще и обзоры в других библиотеках. Мы туда добавим заголовок и описание, но там всё равно останется куча картиночек, которых сейчас просто нет)

Может, с этим что-то сделать системно?

Если что, пока что это — главные страницы наших док.

Основной обзор тут: http://v4.uikit.consta.design/libs/uikit

Еще можно посмотреть тут:
http://refs-pull-22-merge.rc-table-adapter.consta.design/libs/rc-table-adapter
http://refs-pull-65-merge.charts.consta.design/libs/charts
http://refs-pull-11-merge.ag-grid-adapter.consta.design/libs/ag-grid-adapter
