### ISSUE TITLE
Button: Добавить возможность передавать вместо label -> children

### ISSUE THREAD

**Issue by vitaliyirtlach** [consta-design-system/uikit#2586]
> Полные [правила оформления issue](https://consta-uikit.vercel.app/?path=/docs/common-develop-issues--page)

**Описание фичи или улучшения**
Добавить возможность передать children (в виде ReactNode или Element) кнопке вместо однотипных типов (строки и числа)

**Почему улучшение или фича необходима?**
<img width="660" alt="Пример" src="https://user-images.githubusercontent.com/63682036/185901707-f6eff969-6c21-4227-9e92-2d7acee8c55b.png">

Бывают случаи когда в кнопку нужно поместить картинку или отформатированный текст и приходится прописывать @ts-ignore чтобы это срабатывало

**Реализация предложения**
Если children передается label становится необязательным пропсом. И отображать или label или children.

**Comment by Lyubavskaya** [comment]
Опишите, пожалуйста, случаи, в которых вам необходимо помещать в кнопку картинку или отформатированный текст. Почему не можете использовать иконки?

**Comment by vitaliyirtlach** [comment]
Поместить картинку, отформатированный текст

**Comment by gizeasy** [comment]
вы можете отправить запрос на добавление иконки в библиотеку [тут](https://t.me/consta_ui_releases/499)

Также можете создать иконку самостоятельно [подробнее](https://consta.design/libs/icons/docs-addicons/dev)

И использовать ее в кнопке.
