### ISSUE TITLE
storybook: Не копируется цвет

### ISSUE THREAD

**Issue by monolithed** [consta-design-system/uikit#2591]
<img width="863" alt="Screenshot 2022-08-23 at 13 16 58" src="https://user-images.githubusercontent.com/803674/186133851-c6481126-9126-46a9-8d08-b1c070ef3090.png">

https://uikit.consta.design/?path=/story/components-theme--playground

И не плохо бы добавить названия кодов

**Comment by gizeasy** [comment]
готово
