### ISSUE TITLE
Button: Добавить view 'alert'

### ISSUE THREAD

**Issue by vitaliyirtlach** [consta-design-system/uikit#2593]
**Почему улучшение или фича необходима?**
Полезно иметь красную кнопку, которая характеризует опасное действие (например удалить). В теме консты есть цвета.

**Comment by Lyubavskaya** [comment]
Подумать над тем, какие нужны статусы. Либо дополнить доку по кнопке - показать примерами (в Сторибук и в Figma), как другими способами можно показывать, например, опасное действие.

**Comment by gizeasy** [comment]
сделаем возможным в этой задаче
https://github.com/consta-design-system/uikit/issues/3286
