### ISSUE TITLE
TextField: _type_number и _withClearButton

### ISSUE THREAD

**Issue by gizeasy** [consta-design-system/uikit#2594]
сделать возможным использовать _type_number и _withClearButton вместе

**Comment by gizeasy** [comment]
Сейчас нет возможности использовать 2е модификации вместе. Если будем делать то нужно продумать как стрелочки и крестик вместе поставить.

**Comment by lisaovcharenko** [comment]
Посмотреть опыт других ДС

**Comment by linturaven** [comment]
СДЕЛАНО!
