### ISSUE TITLE
storybook: В Safari поехали таблицы Table

### ISSUE THREAD

**Issue by monolithed** [consta-design-system/uikit#2600]
Safari:

<img width="2302" alt="Screenshot 2022-08-24 at 16 50 00" src="https://user-images.githubusercontent.com/803674/186435849-01a7279c-b957-42ca-9eda-ea91fc5857c8.png">

Chrome:
<img width="2323" alt="Screenshot 2022-08-24 at 16 49 24" src="https://user-images.githubusercontent.com/803674/186435860-2f150312-0176-4fb4-8365-6e2edfa8cf39.png">

**Comment by N1MBER** [comment]
Проверил на версии uikit 4.3.0 (на новом портале), проблема не обнаружена.
