### ISSUE TITLE
Text: Добавить пунктирное подчеркивание (dashed)

### ISSUE THREAD

**Issue by monolithed** [consta-design-system/uikit#2601]
<img width="400" alt="Screenshot 2022-08-25 at 13 58 14" src="https://user-images.githubusercontent.com/803674/186647311-275ef5da-31db-4772-9a1f-5281a66fb929.png">

Довольно частое явление, когда пунктирное подчеркивание более уместно

**Comment by Lyubavskaya** [comment]
Это устаревший паттерн. В данном случае лучше сделать либо отдельную кнопку, либо использовать view link.

**Comment by monolithed** [comment]
@Lyubavskaya, не согласен. Давайте ориентироваться на лидеров рынка. Вот пример всплывающего окна в Mirо:
<img width="863" alt="Screenshot 2022-07-23 at 20 24 16" src="https://user-images.githubusercontent.com/803674/189303110-10574eb3-274c-4dd9-ba16-de788dd7713b.png">

Если такой паттерн устарел, то нужен пруф.

**Comment by monolithed** [comment]
`<Text view="link" />` — решил бы проблему, но он тоже не умеет добавлять ни подчеркивание, ни пунктир. Для этого нужно дописывать стили, хотя кейсы весьма распространенные.
