### ISSUE TITLE
SnackBar: Добавить варианты скруглений

### ISSUE THREAD

**Issue by monolithed** [consta-design-system/uikit#2603]
<img width="1010" alt="Screenshot 2022-08-26 at 13 00 06" src="https://user-images.githubusercontent.com/803674/186879881-4f8098c7-2eed-4779-bfc6-ad5467337f18.png">

У кнопок, полей ввода и информеров 3 типа скруглений, а у снекбара 1, который иногда совсем ни к месту если интерфейс более острый.

**Comment by Lyubavskaya** [comment]
Дизайн готов https://www.figma.com/community/file/853774806786762374
