### ISSUE TITLE
Docs: Цветовая палитра - раздел на портале

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#2614]
проработать контент на портале о цветах, переменных, темах и тп

рассказать 
- откуда появилась такая система, 
- как она работает, 
- принципы работы с палитрой,
- как добавлять свои цвета, 
- что нужно учитывать при этом 
- и тп

**Comment by lisaovcharenko** [comment]
Связанная задача: https://github.com/consta-design-system/uikit/issues/1948

**Comment by alyonurchick1** [comment]
https://www.notion.so/9eedf2f69d184660b424aec5b0444eb6?pvs=4

**Comment by alyonurchick1** [comment]
https://github.com/consta-design-system/portal/pull/40
https://refs-pull-40-merge---portal.consta.design/libs/portal/theme-colorpalette
