### ISSUE TITLE
DatePicker: Реализовать кастомное форматирование данных в поле ввода

### ISSUE THREAD

**Issue by N1KN** [consta-design-system/uikit#2623]
**Описание фичи или улучшения**
Добавить в компонент DatePicker возможность форматировать отображаемые в поле ввода данные не только с помощью используемой в компоненте функции format из библиотеки date-fns, но и с помощью своей кастомной функции.

Предлагаю такой тип: `<T extends DatePickerPropType) (data: { type: T, value: DatePickerPropValue<T> }) => string|[string?,string?]`

**Почему улучшение или фича необходима?**
Нет возможности лично указать то, что будет отображаться в поле ввода, только по собственному шаблону.
Например, нельзя использовать русские названия месяцев в поле ввода.

**Comment by monolithed** [comment]
1. Текущая реализация ограничивает применение стандартного форматирования:

```js
const date= new Date(Date.UTC(2012, 11, 20, 3, 0, 0));

date.toLocaleString('ru-RU, {
  month: 'long',
  year: 'numeric',
});
```

2. Поле format — должно быть произвольной строкой

**Comment by Lyubavskaya** [comment]
Дубль https://github.com/consta-design-system/uikit/issues/2625
