### ISSUE TITLE
Slider: Отображение TextField с обеих сторон

### ISSUE THREAD

**Issue by MyasoutovaTatiana** [consta-design-system/uikit#2626]
Есть вариант отображения TextFied с левой стороны или с правой, но нет варианта отображения текстового поля с обеих сторон для какого-то отрезка
<img width="344" alt="Снимок экрана 2022-09-07 в 19 31 33" src="https://user-images.githubusercontent.com/108055994/188931674-3f36c091-30d8-47bd-8b0b-b4d9c2aaf3c2.png">

В Storybook есть отображение компонента, но только когда текстовое поле находится с левой стороны, с правой стороны нет вариант выбора инпута

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/108055994/188932337-d9d2c09f-c1be-40df-a272-30006f1efc55.png">
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/108055994/188932441-21dabb6e-ef6c-4b0f-9c34-19252ade4d1a.png">

<img width="1231" alt="Снимок экрана 2022-09-07 в 19 39 48" src="https://user-images.githubusercontent.com/108055994/188933362-4ef12788-efb3-46a6-b46e-5bfff51b6938.png">

**Comment by Lyubavskaya** [comment]
4. Дополнить доку примерами с инпутами 
5. проверить в доке пример с размерами (хs и s) + добавить отступы между ними

**Comment by errorry** [comment]
Спроектированы варианты отображение TextField с обеих сторон компонента Slider
https://www.figma.com/file/u4fDZ5rdcEoJUZ7cITlVJx/Github-issues?node-id=2825%3A52859

Цветам из сторука, компонент textfield из ui kit


**Найдены ошибки в сборке большинства компонентов slider:**

- В размерах m,s,xs есть отступы между краем компонента и названием (label)
- В компонентах использован сторонний textfield (не из ui kit)

**Comment by Lyubavskaya** [comment]
Чекнуть, куда ссылаются инпуты в некоторых вариантах и поправить, где неправильно

**Comment by Lyubavskaya** [comment]
Дизайн: https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=67568%3A129967
