### ISSUE TITLE
Не работает меню в Consta Header при использовании Layout

### ISSUE THREAD

**Issue by p1uton** [consta-design-system/uikit#2631]
В Consta Header при создании кастомной шапки с помощью Layout не работает элемент Menu.
Воспроизводится на сайте Consta Header - https://header.consta.design/?path=/story/components-layout--playground
Воспроизводится в браузерах Chrome, Firefox, Opera
![2](https://user-images.githubusercontent.com/4601747/189886148-b50b08ed-8c5e-4e90-9c4e-4c78b2fe82cd.png)
![3](https://user-images.githubusercontent.com/4601747/189886165-4a2d0b2a-e3f8-4f80-9643-fd173581842a.png)

**Comment by gizeasy** [comment]
проверить css свойства, либо установить по умолчанию стили, либо сделать модификатор чтоб при его активации нормално отображалось меню в Header, ну или написать какойе css свойство надо накинуть на меню чтоб оно адекватно работало в Header
