### ISSUE TITLE
Stand: В вариантах в полях типа boolean едет верстка

### ISSUE THREAD

**Issue by gizeasy** [consta-design-system/uikit#2648]
При длинных названиях едет верстка в полях типа boolean
![image](https://user-images.githubusercontent.com/13190808/191492075-1642007d-474c-4699-9f92-6edcebff2444.png)

`loadingWithProgressSpin`

**Comment by Lyubavskaya** [comment]
Сгруппировать свойства, которыми могут пользоваться разработчики и отделить от свойств, которые мы сделали специально для витрины, чтобы показать возможности компонента
