### ISSUE TITLE
Loader: ресеч верстки

### ISSUE THREAD

**Issue by gizeasy** [consta-design-system/uikit#2650]
что-то очень странное поцизионирование лоадера

он тянется на всю ширину, и прибивается к низу блока, возможно стоит ограницит его ширину и высоту чтоб его на проекте уже позиционировали на проекте сами

![image](https://user-images.githubusercontent.com/13190808/191494615-1997ecf9-9594-483b-a7d3-29d7a6eb0544.png)

**Comment by N1MBER** [comment]
Создать Canary версию
