### ISSUE TITLE
Компонент Card не применяет тему.

### ISSUE THREAD

**Issue by PetrMKO** [consta-design-system/uikit#2654]
Я использую компонент Card, чтобы разместить в нем контент, также хочу, чтобы оформление блока Card изменялось в соответствии с одной из стандартных тем, но если обернуть Card в Theme, то цвет фона у card не изменяется, меняется только шрифт. Как сделать так, чтобы изменялся также и задний фон у Card при смене цвета

**Comment by gizeasy** [comment]
сама карточка не имеет фона, вы всегда можете указать ей фон через `className` нужной для вас переменной

**Comment by PetrMKO** [comment]
Спасибо, помогло
