### ISSUE TITLE
Components: Создать для разных статусов компонентов свои `cn` функции

### ISSUE THREAD

**Issue by gizeasy** [consta-design-system/uikit#2658]
для тотого чтобы уберечь от пересечение стилей создать отдельно для 
canary и depricated свои `cn` функции

Так же это способствует быстрому переименованию всех классов при изменении статуса у компонента

**Comment by gizeasy** [comment]
Также пройтись по компонентам и убрать из названия блоков и элементов Canary и Depricated

**Comment by N1MBER** [comment]
- [ ] uikit
- [ ] rc-tree-adapter
- [ ] header
- [ ] charts
- [ ] icons
- [ ] rc-table-adapter
- [ ] react-big-calendar-adapter
- [ ] ag-grid-adapter
- [ ] gantt-task-react-adapter
- [ ] widgets
- [ ] analytic-ui
- [ ] stats
- [ ] gpn-responses
- [ ] react-slick-adapter
