### ISSUE TITLE
Checkbox: Добавить размер XS

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#2672]
Сам чекбокс оставляем размера S, шрифт уменьшаем на 2 пункта

**Comment by Ilyashis** [comment]
Размер S

**Comment by Ilyashis** [comment]
https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=56%3A37365

**Comment by Ilyashis** [comment]
Обновлены отступы у размера М как на фронте

**Comment by Ilyashis** [comment]
Добавлен размер XS для трех тем
https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=56%3A37365
