### ISSUE TITLE
ProgressLine: поправить названия и обернуть в варианты

### ISSUE THREAD

**Issue by hell0anna** [consta-design-system/uikit#2678]
Рефакторнуть компонент:

- сделать все как варианты одного компонента со свойствами steps=true/false, legend=true/false
- переименовать в ProgressLine (сейчас это ProgressBar и LinearIndicator
- привести страницу к единому виду со всеми компонентами

https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=87813%3A160639

**Comment by errorry** [comment]
Виды компонента объединены, добавлены варианты

https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=87813%3A160639&t=bX1PtIxb5IMaEdyi-1
