### ISSUE TITLE
Badge: При переключении цветовой темы появляется доп. заливка 

### ISSUE THREAD

**Issue by MyasoutovaTatiana** [consta-design-system/uikit#2679]
При переключении цветовой темы  на Dark или Display появляется дополнительная заливка 

<img width="813" alt="Снимок экрана 2022-10-10 в 12 02 26" src="https://user-images.githubusercontent.com/108055994/194832451-065b87b7-6abe-40b8-9a63-786e4e901d0f.png">

<img width="767" alt="Снимок экрана 2022-10-10 в 12 02 52" src="https://user-images.githubusercontent.com/108055994/194832471-9dc2b61f-432d-4e40-8d85-13ca52de0fda.png">

<img width="777" alt="Снимок экрана 2022-10-10 в 12 02 39" src="https://user-images.githubusercontent.com/108055994/194832474-6c07d881-64bd-4db0-a725-8fdc87cc0bcc.png">

**Comment by hell0anna** [comment]
в темной и дисплейной теме есть вложенность компонентов, которые ссылаются на несуществующих родителей, нужно поправить. Возможно из-за этого происходит ошибка с заливками при переключении темы 

<img width="461" alt="image" src="https://user-images.githubusercontent.com/51019093/194839295-0d046a74-5a48-46b3-8434-1ec4509fadd2.png">

**Comment by errorry** [comment]
Исправлена сборка badge в темных темах
дефолтный компонент внутри разгруппирован, убраны лишние отступы, переназначены цвета

https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=40%3A119&t=WBCE2DWijXiU5Gcs-1
