### ISSUE TITLE
Tabs: Добавить в Figma варианты Icon=False и OnlyIcon=True

### ISSUE THREAD

**Issue by linturaven** [consta-design-system/uikit#2687]
Сейчас в Figma невозможно с помощью свойств управлять отображением иконки. Иногда дизайнеры задают вопросы на тему того, можно ли отключить иконку. Нужно привести в соответствие с тем, как компонент работает в коде.

**Comment by errorry** [comment]
добавлены варианты и состояние дизейбл

опять встретилась проблема, что компоненты из дефолтной темы перекрашивают в темные, а не заменяют на соответсвующий вариант компонента из темных тем

https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=12745%3A116509&t=NK60VxarV7aeR5Z9-1
