### ISSUE TITLE
Portal: Нет кнопки меню в разрешении 1366х768

### ISSUE THREAD

**Issue by linturaven** [consta-design-system/uikit#2691]
В инспекторе разрешений, когда выбираю разрешение 1366х768 скрывается левый навбар, но бургер не появляется. При этом при смене разрешения на пару пунктов больше или меньше — всё появляется.

**Comment by linturaven** [comment]
![Снимок экрана 2022-10-12 в 16 07 36](https://user-images.githubusercontent.com/94055055/195351003-2d8575b6-e08c-4623-a4cf-167f208e0b82.png)

**Comment by gizeasy** [comment]
исправили
