### ISSUE TITLE
Consta Colors: Проверить доступность цветов на разных экранах 

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#2707]
нужно провести небольшое исследование по доступности цветов палитры Consta Default/Dark/Display на разных мониторах (плохие, очень плохие и тп). Есть гипотеза, что серые оттенки пропадают, а статусные меняют оттенок на не самый приятный.

По результатам исследования поставить задачки на внесение изменений в палитру, если потребуется.

**Comment by linturaven** [comment]
Было бы неплохо успеть в рамках 2.0, пока снижаю приоритет

**Comment by lisaovcharenko** [comment]
Дубль https://github.com/consta-design-system/uikit/issues/3136
