### ISSUE TITLE
Docs: Поправить ссылки на компоненты в Figma

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#2709]
Проверить статусы реализации в коде.

**Comment by arhayka** [comment]
Остался вопрос про статусы: в фигме у нескольких графиков статус **В работе.** Это акутально?

<img width="657" alt="Screenshot 2022-11-11 at 12 31 51" src="https://user-images.githubusercontent.com/12581569/201461012-12a89a51-2e1c-407a-aa91-a4337db7d521.png">

**Comment by arhayka** [comment]
Решили, поменяла все статусы **В работе** на **Актуально**, всё готово.
