### ISSUE TITLE
User: Ошибка в обозначениях размерностей в Figma

### ISSUE THREAD

**Issue by linturaven** [consta-design-system/uikit#2714]
В Figma не совпадает описание размеров компонента и свойства размеров:
L | M | S - описание (также и в документации)
M | S | XS - свойства в фигме

**Comment by hell0anna** [comment]
готово
https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=58%3A39679
