### ISSUE TITLE
IconFavorite: Добавить в набор пустую звезду

### ISSUE THREAD

**Issue by Turgut710** [consta-design-system/uikit#2734]
На текущий момент есть только иконка залитой звезды, и чтобы сделать звезду пустой приходится отдельно возиться с границами иконки и заливкой. 

Это не очень удобно, когда делаешь функционал по добавлению объекта в Избранные. Сейчас приходится подбирать цвета заливки, которые бы соответствовали состояниям: 1) объект добавлен в Избранные 2) объект не является Избранным

Необходимо добавить в библиотеку иконку пустой звезды (пример прикладываю):
![image](https://user-images.githubusercontent.com/117706585/200481829-7b38c3ac-62ff-4e76-90aa-a5c6276d7ac6.png)

**Comment by MyasoutovaTatiana** [comment]
Добавить иконку дизлайка, скайпа, вай-фай

**Comment by hell0anna** [comment]
добавила иконки скайпа, вифи, дизлайк
