### ISSUE TITLE
Combobox: логика задизейбленых элементов

### ISSUE THREAD

**Issue by N1KN** [consta-design-system/uikit#2749]
### Описание бага
Combobox с пропсом multiple не корректно отображает выбранные(в поле value) элементы списка с пропсом `disabled ` .

- Галочка у `disabled` элемента в списке выглядит, как активная
- Тэг в поле ввода позволяет удалить `disabled` элемент, т.к. у неё есть крестик

![image](https://user-images.githubusercontent.com/37019408/201670458-3c444e7b-981b-489d-b721-358c7ae5b9b3.png)

**Версия Consta Kit**
3.29.0

**Comment by gizeasy** [comment]
возможно мделать флаг переключающий логику работы задизейбленных элементов или оставить только одно верное повидение
