### ISSUE TITLE
Charts: react 18 ругается на ReactDOM.render

### ISSUE THREAD

**Issue by gizeasy** [consta-design-system/uikit#2760]
![image_2022-11-16_13-42-05](https://user-images.githubusercontent.com/13190808/202175353-634064e8-428a-40a6-8b6c-9e33703e671c.png)

customContent для тултипов ругается в графиках консты

можно смотреть на присутствие нового api или на `React.version`

**Comment by Dem0nZ** [comment]
Приветствую. Это поправят?

**Comment by gizeasy** [comment]
@Dem0nZ не подскажешь в каком случае выходит эта ошибка и какая версия пакета и реакта у вас?

**Comment by Dem0nZ** [comment]
@gizeasy Приветствую. Везде где юзаются чарты. 
"@consta/charts": "^0.7.1",
"react": "^18.2.0",
