### ISSUE TITLE
Table/landing/storybook/doc: Добавить в конфигурацию столбцов возможность указания компаратора для сортировки конкретного столбца

### ISSUE THREAD

**Issue by semwett0301** [consta-design-system/uikit#2767]
**Описание фичи или улучшения**
Фича касается улучшения компонента Table, а точнее сортировки по каждому из столбцов: перенести конфигурацию сортировки из общей для всех полей функции в отдельное поле конфигурации для каждого столбца, если стандартная сортировка не подходит и нам нужно написать свою собственную.

Что бы хотелось: 
- Чтобы через еще одно поле после sortable (предположим, поле будет называться comparator) можно было указать функцию компаратор, с помощью которой компонент бы сравнивал значения именно этого столбца

Что придется сделать: 
- написать глобальную функцию для этой таблицы, которая будет задавать правила сортировки для всех столбцов, и положить ее в пропс onSortBy компонента Table

Результат:
вместо одного поля, приходится писать огромную функцию для всех полей с большим switch/case

В прикрепленных файлах лежит описание объекта, который поступает в ячейку, и как он преобразуется в компонент через renderCell.

**Почему улучшение или фича необходима?**
При наличии одной или нескольких собственных сортировок (например, когда в ячейку передается объект, который потом через renderCell превращается в ячейке в компонент) требуется написать большую функцию, которая будет сортировать массив относительно параметров, которые предварительно создаются в качестве стейта в компоненте, где находится Table. В этой функции помимо особенных столбцов также необходимо учесть поля, которые сортируются также, как и в режиме по умолчанию. В итоге:

1. Разрастается компонент, в котором инициализируется сортировочная функция
2. Сама функция содержит избыточные манипуляции, так как при написании своей сортировки приходится дублировать сортировку по умолчанию
3. При работе с ассинхронностью могут возникать проблемы отрисовки данных
4. Если архитектура приложения многослойна и Table используется на 1-2 уровня ниже того, в котором конфигурируется сортировочная функция, то может возникнуть проблема с внезапным изменением стейта, который мы сортируем (это конкретно наш случай, так как по какой-то причине стейт при сортировке менялся, хотя сортировочная функция возвращала не оригинальный, а новый массив. Из-за этого сброс сортировки также не работал).

**Дополнительная информация**
Если есть вопросы по поводу описания проблемы, то всегда готов ответить на них в телеграме: @sem_wett

![image](https://user-images.githubusercontent.com/90400355/203131519-adfad10e-003d-4f1a-8db9-7e9fc74d0b1a.png)
![image](https://user-images.githubusercontent.com/90400355/203131534-6b2efa9d-9f4c-4859-b183-17f550f43c58.png)

**Comment by N1MBER** [comment]
Всю сортировку можно вынести в поле [`filters`](https://uikit.consta.design/libs/uikit/components-table-stable/dev?hash=%D1%84%D0%B8%D0%BB%D1%8C%D1%82%D1%80%D1%8B)
