### ISSUE TITLE
TextField:  тип  value при type='number'

### ISSUE THREAD

**Issue by N1MBER** [consta-design-system/uikit#2769]
При указании  type='number', поле запрашивает тип string вместо number

**Comment by gizeasy** [comment]
Не уверен баг ли это, но TextField с пропсом type='number', в качестве value хочет string, поэтому приходится делать что-то такое. 
https://t.me/fi_tymi - от пользоваеля

**Comment by gizeasy** [comment]
Решили оставить нативное поведение
