### ISSUE TITLE
Components: Исправить сборку компонента в темных темах

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#2772]
Здесь собираем случаи, когда компонент в темах dark и display просто обернут в компонент и перекрашен.

- [x] Дефолтный бейдж
- [x] Avatar, AvatarGroup
- [x] Radio
- [x] Responses
- [x] Scrollbar
- [x] SnackBar
- [x] User

**Comment by errorry** [comment]
Исправлена сборка Avatar, AvatarGroup в темных темах
https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=56%3A30966&t=sh7OckgkW7OqW9G7-1
