### ISSUE TITLE
ag-grid-adapter: Баг в таблице

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#2793]
- [ ] Баг в Consta ag-grid-adapter.

Перемещается календарь при выборе даты для фильтрации таблицы. После того как пользователь выбирает дату, календарь пропадает, но чтобы фильтр применился, надо нажать еще раз на иконку «Фильтр» и нажать на кнопку «Применить».
 
![image](https://user-images.githubusercontent.com/75978078/204351788-b2322340-5d4c-4ecd-805f-a40c9e176229.png)
![image](https://user-images.githubusercontent.com/75978078/204351812-ee00c367-6d89-46d7-aa8a-3b5434a894f9.png)
![image](https://user-images.githubusercontent.com/75978078/204351847-f14076eb-9288-44f9-8807-f13d9c258337.png)

- [ ] #2804
![image](https://user-images.githubusercontent.com/75978078/204352003-664a95a5-bb08-46c4-bf3a-c0eef679b015.png)

- [x] Некорректная сортировка. При нажатии на иконку «Сортировка» таблица сначала сортируется с теми данными, которые отображены на FE, после того как приходит ответ с бэка сортирует данные еще раз.

- [x] После применения фильтра в шапке колонки появляется еще одна иконка, указывающая, что на выбранную колонку применен фильтр
![image](https://user-images.githubusercontent.com/75978078/204352127-4511451a-20f5-4722-aff3-65b1922016ef.png)

- [x] Не пропадает окно фильтра. Для колонки «Статус» доступна фильтрация. После того как пользователь выбрал нужный ему статус, пользователь нажимает «применить» и окно не пропадает
![image](https://user-images.githubusercontent.com/75978078/204352263-d159c977-02d3-41b5-b593-6a69fd6cd04c.png)

- [x] При загрузке данных для таблицы, лоудер отображается по середине таблицы. Лоудер размещен внутри самой таблицы, поэтому если кол-во записей полностью не умещаются на странице, то пользователь не увидит лоудер. На скриншоте пример, записей на странице 20, прользователь видит 10, и лоудер отображается у 10 записи
![image](https://user-images.githubusercontent.com/75978078/204352360-a12e2e8c-65d0-4b02-ae23-c9a84f3819a3.png)

**Comment by N1MBER** [comment]
"В шапке таблица не отображается иконка «Сортировка» для колонки, которой доступна сортировка. При клике на шапку колонки сортировка применяется и иконка появляется. На скриншоте сортировка доступна для колонок «Заявка», «Дата создания» и «Дата обновления», но иконка только у колонки «Заявка», т.к. на эту колонку применена сортировка" - этого функционала нет в ag-grid, иконка сортировки отображается только для тех колонок к которым применена сортировка.

**Comment by N1MBER** [comment]
"Некорректная сортировка. При нажатии на иконку «Сортировка» таблица сначала сортируется с теми данными, которые отображены на FE, после того как приходит ответ с бэка сортирует данные еще раз." - этот баг относится не к адаптеру, а к самой таблице ag-grid
