### ISSUE TITLE
Theme: Возможность выставить дефолтный размер для всех компонентов в проекте.

### ISSUE THREAD

**Issue by PetrMKO** [consta-design-system/uikit#2801]
> Полные [правила оформления issue](https://consta-uikit.vercel.app/?path=/docs/common-develop-issues--page)

**Описание фичи или улучшения**

Сделать возможность выставить дефолтный размер для всех компонентов в проекте.

**Почему улучшение или фича необходима?**
Допустим во всем проекте по дизайну используются компоненты размера s(мой случай, сейчас дефолтный размер m). Тогда необходимо каждый раз при написании любого компонента указывать size=‘s', это очень сильно нарушает DRY и увеличивает размер кода.

**Реализация предложения**
Так как все компоненты итак обращаются к контексту, темы (Theme), то можно передавать ей опциональный пропс с параметрами, в том числе дефолтный размер элемента, которые будут заменять дефолтные. Таким образом, можно не только указать эти параметры один раз, при оборачивании App в компонент Theme, но и локально, допустим в модалке.

**Дополнительная информация**
Все, что считаете нужным

**Comment by gizeasy** [comment]
Привет подумали над задачей:

```tsx
<Theme componentsDefaultProps={{Button: {size: 's'}}, {Select: {size: 's'}}}/>
```

Из данного подхода получается что при использовании `Button` и `Select` не явно переопределяются пропсы, так как сам `Theme` может находися на много выше в другом файле. Так же, при желании добавить новые дефолтные пропсы нужно искать в каком экземпляре `Theme` он находится.

По этому предлагаю сделать хок `withDefaultProps` и использовать его в конкретных случаях там где это необходимо, он прозрачнее всегда IDE подскажет где находится определение этого компонента.

```tsx
const ButtonLogin = withDefaultProps({size: 's'})(Button);
const ButtonInTable = withDefaultProps({size: 's', view: 'secondary'})(Button);
const UserDescription = withDefaultProps({size: 's', view: 'secondary'})(Text);
const Link = withDefaultProps({size: 's', view: 'link', decoration: 'underline'})(Text);
```

Такой хок мы видим полезным, что думаешь о такой реализации?

Также если тебе на проекте хочется видеть именно реализацию через контекст и проблемы которые я описал у тебя в проекте не возникнут из-за архитектуры проекта. Можешь самостоятельно реализовать такой контекст. 
Напишешь хок для того чобы дружить компоненты с контексом 
```tsx
const Button = withContextProps(Button, 'button');
const Text = withContextProps(Text, 'text'); 
```

и сам Компонент с контекстом

```tsx
<DefaultProps button={{size: 's'}}>
    <Button/>
</DefaultProps>
```

**Comment by lisaovcharenko** [comment]
@gizeasy проверь, пожалуйста, это уже реализовано?
