### ISSUE TITLE
uikit/Table баг в Развернутые строки

### ISSUE THREAD

**Issue by Nikita7795** [consta-design-system/uikit#2821]
Когда меняется состояние значение строки(rows), коллапс мгновенно закрывается. Например, если в коллапсе будет TextField, и в нем вводим текст, коллапс закрывается. Происходит из-за значение defaultExpand, если оно false(по дефолту- false), то при изменении значение rows, которая сейчас открыта, срабатывает функция в useEffect и опять проставляет defaultExpand все строкам, и закрывает их.

https://user-images.githubusercontent.com/69715667/207036019-b764efd6-cf43-4faa-a6da-2f44329fe521.mov

<img width="562" alt="Снимок экрана 2022-12-12 в 14 29 32" src="https://user-images.githubusercontent.com/69715667/207034617-a8a5a65c-02c4-4f1f-ae6a-afc79fbdb2e5.png">

**Версия Consta Kit - 4.6.0

**Comment by N1MBER** [comment]
День добрый! Можете пожалуйста прикрепить пример кода, как у вас работает рендер функция и код конфигурации таблицы

**Comment by Nikita7795** [comment]
`
import './App.css';
import { TextField } from '@consta/uikit/TextField';
import { Table } from '@consta/uikit/Table';
import React, {
  useState,
} from 'react';
import { Theme, presetGpnDefault } from '@consta/uikit/Theme';

function App() {
  const [myButton, setMyButton] = useState('');
  const myColumns = [
    {
      title: 'Месторождение',
      accessor: 'field',
      align: 'left',
      sortable: true,
      // eslint-disable-next-line react/display-name, @typescript-eslint/no-unused-vars
    },
    {
      title: 'Год открытия',
      accessor: 'year',
      align: 'center',
      sortable: true,
      renderCell: ({ column }) => (
        <TextField
          onChange={({value}) => setMyButton(value)}
          value={myButton}
          size="xs"
          iconSize="s"
          label="ff"
        />
      ),
    },
    {
      title: 'Тип',
      accessor: 'type',
      align: 'left',
    },
  ];

  const expandableRowsData = [
    {
      id: 'row1',
      field: 'Северное',
      year: 1982,
      type: 'Нефть',
      rows: [
        {
          id: 'row1.1',
          field: 'Северо-Западное',
          year: 1985,
          type: 'Конденсат',
        },
        {
          id: 'row1.2',
          field: 'Северо-Восточное',
          year: 1983,
          type: 'Конденсат',
        },
      ],
    },
    {
      id: 'row2',
      field: 'Восточное',
      year: 1989,
      type: 'Конденсат',
      rows: [
        {
          id: 'row2.1',
          field: 'Восточное-1',
          year: 1989,
          type: 'aa',
        },
        {
          id: 'row2.2',
          field: 'Восточное-2',
          year: 1989,
          type: 'Конденсат',
          rows: [
            {
              id: 'row2.2.1',
              field: 'Восточное-3',
              year: 1989,
              type: 'Конденсат',
              rows: [
                {
                  id: 'row2.2.1.1',
                  field: 'Восточное-8',
                  year: 1989,
                  type: 'Конденсат',
                },
                {
                  id: 'row2.2.1.2',
                  field: 'Восточное-7',
                  year: 1993,
                  type: 'Нефть',
                },
              ],
            },
            {
              id: 'row2.2.2',
              field: 'Восточное-4',
              year: 2001,
              type: 'Нефть',
            },
          ],
        },
      ],
    },
  ];
  return (
    <div className="App">
      <Theme preset={presetGpnDefault}>
      <Table
          columns={myColumns}
          rows={expandableRowsData}
          borderBetweenColumns
          borderBetweenRows
          isResizable={false}
          headerVerticalAlign="center"
          verticalAlign="top"
        />
      </Theme>
    </div>
  );
}

export default App;
`

**Comment by Nikita7795** [comment]
<img width="1091" alt="Снимок экрана 2022-12-21 в 14 34 13" src="https://user-images.githubusercontent.com/69715667/208897248-74c72c67-d22b-433b-b957-176271cbe409.png">
<img width="434" alt="Снимок экрана 2022-12-21 в 14 34 57" src="https://user-images.githubusercontent.com/69715667/208897290-f602d482-1938-4e4c-ab14-e72af3884acd.png">
<img width="424" alt="Снимок экрана 2022-12-21 в 14 35 07" src="https://user-images.githubusercontent.com/69715667/208897315-b4c84fde-ee53-479e-9daa-000e8d8f7a3f.png">
