### ISSUE TITLE
docs: Заменить ссылки на портал на гитхабе во всех репозиториях

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#2824]

**Comment by N1MBER** [comment]
Сделано в:

- [ ] ag-grid-adapter
- [ ] icons
- [ ] gantt-task-react-adapter
- [ ] rc-tree-adapter
- [ ] rc-table-adapter
- [ ] react-big-calendar-adapter
- [ ] analytic-ui
- [ ] gpn-responses
- [ ] stats
- [ ] widgets
- [ ] amcharts-map-example

Неполучилось (нету прав):
- [ ] uikit
- [ ] charts
- [ ] header
