### ISSUE TITLE
Switch: Задизейбленный и выключенный свитч очень похожи

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#2840]
Нужно подумать, что поменять, чтобы разница была более заметна.

**Comment by errorry** [comment]
Исследование других систем и ui kits 
Выявлен одинаковый паттерн отображения недоступного состояния для переключателя (закрашивается бэк)

<img width="412" alt="Снимок экрана 2022-12-27 в 12 38 24" src="https://user-images.githubusercontent.com/90323723/209655928-7306e474-bd72-49e1-bf04-650022bcb25f.png">
<img width="974" alt="Снимок экрана 2022-12-27 в 12 39 00" src="https://user-images.githubusercontent.com/90323723/209655936-74bddfa5-bb8b-46b5-ae02-3cb06c6ad965.png">
<img width="231" alt="Снимок экрана 2022-12-27 в 12 45 48" src="https://user-images.githubusercontent.com/90323723/209655946-ac10fa87-dbd6-4e98-85a0-c9d3cd8a301b.png">
<img width="262" alt="Снимок экрана 2022-12-27 в 12 55 59" src="https://user-images.githubusercontent.com/90323723/209655951-162f3cf8-76d6-4c3f-bee8-67cb3a58a38f.png">

в мобильном ките используется данный паттерн

<img width="532" alt="Снимок экрана 2022-12-27 в 12 46 58" src="https://user-images.githubusercontent.com/90323723/209656313-0b85750b-8aa7-4b44-aece-ba833b140465.png">

пример стиля для переключателя консты

<img width="735" alt="Снимок экрана 2022-12-27 в 12 53 52" src="https://user-images.githubusercontent.com/90323723/209656407-f3c5229a-7cbc-4b6f-b5ed-3e547bcde16a.png">

+выявлена ошибка в стиле активного переключателя ghost display (обводка из другой темы)

**Comment by errorry** [comment]
Изменены переключатели в недоступном состоянии
Поправлен активный переключатель ghost display
Поправлены цвета примеров переключателей hover

https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=58%3A2269&t=umD6aEOyjrEmp3s1-1

**Comment by N1MBER** [comment]
Уже реализовано в коде (сопоставил все цвета из фигмы и те что имеются в коде)
<img width="267" alt="Снимок экрана 2023-02-02 в 11 47 47" src="https://user-images.githubusercontent.com/44449561/216275567-4b202d98-d840-44c2-8da8-a877920d7f36.png">
