### ISSUE TITLE
ChoiceGroup: В песочнице подгружается Collapse и не работает выбор view в предпросмотре

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#2845]
В песочнице для choiceGroup подгружается Collapse и не работает выбор view в предпросмотре
![image](https://user-images.githubusercontent.com/75978078/209940165-a61750bb-9e37-4652-8dae-a76f63007dbe.png)

**Comment by N1MBER** [comment]
Проблема с песочницей закрыта в этой прке https://github.com/consta-design-system/uikit/pull/2910. Проверил варианты, view работает, для этого нужно выбрать хотяб одно значение
