### ISSUE TITLE
Select, Combobox: Ховер для view clear

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#2850]
https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=115806%3A290581&t=KTcjc1LKf1dosiFu-1

**Comment by hell0anna** [comment]
добавлено описание к TextField, Select, Combobox, UserSelect

**Comment by hell0anna** [comment]
https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=115806%3A290581&t=KTcjc1LKf1dosiFu-1
