### ISSUE TITLE
docs: Корректировка документации по мобильным UI-kit

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#2852]
тут лежит мобильный кит 
https://www.figma.com/file/ZGwiodCiyPsoTvDLCcfQ77/Consta-UI-kit-%E2%80%94-Mobile?node-id=298%3A12962&t=ztsG35BhD4rjksl6-1

на каждой страничке компонента будет появляться текстовая часть с описанием и картинками. Нужно будет проверить текст на адекватность, ошибки и может даже что-то переписать )

Спасибо :3

**Comment by hell0anna** [comment]
лучше оставлять правки комментариями, а мы потом сами внесем в макет, чтобы между собой не запутаться)
