### ISSUE TITLE
Table: Вертикальные связи между уровнями

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#2863]
У нас возникла следующая потребность: в иерархических таблицах нам очень нужны вертикальные связи между уровнями таблиц. Желаемый вид отобразили на макете, скриншот во вложении.  
![image](https://user-images.githubusercontent.com/75978078/213416356-b94aed99-0db7-4e2f-b2e9-17e85b7bbdc1.png)

**Comment by lisaovcharenko** [comment]
Рассмотрим возможность добавления функционала в новую библиотеку Consta Table.
