### ISSUE TITLE
Icons: Добавить новые иконки

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#2866]
из комментариев в канале

**Comment by Lyubavskaya** [comment]
Просьба от команды Astra: 

- [ ] Иконка дерево (отображение иерархии) 
![image](https://github.com/consta-design-system/uikit/assets/75978078/3ebb63db-791e-42d5-b9ae-0008942c8920)
(аналог в MUI: https://mui.com/material-ui/material-icons/?query=tree&selected=AccountTree)

- [ ] Иконки сворачивания / разворачивания боковой панели
![image](https://github.com/consta-design-system/uikit/assets/75978078/75686bb8-eae2-4eaa-92cd-8c9830b2d1b2)
(аналог в MUI: сворачивание: https://mui.com/material-ui/material-icons/?selected=KeyboardDoubleArrowLeft
разворачивание https://mui.com/material-ui/material-icons/?selected=KeyboardDoubleArrowRight)

- [ ] Иконка регулирования ширины боковой панели 
![image](https://github.com/consta-design-system/uikit/assets/75978078/8f5f9c96-0a72-4e7a-8198-9a5299ea9e27)
(аналог в MUI: https://mui.com/material-ui/material-icons/?selected=DragHandle)

- [ ] Иконка отмены действия
![image](https://github.com/consta-design-system/uikit/assets/75978078/43e1d9cb-ca5f-438f-9c05-e6ff724d44dd)
(аналог в MUI: https://mui.com/material-ui/material-icons/?query=redo&selected=Undo)

- [ ] Иконка восстановления действия 
![image](https://github.com/consta-design-system/uikit/assets/75978078/9a517588-24d0-4a57-8554-830f89acf85f)
(аналог в MUI: https://mui.com/material-ui/material-icons/?query=redo&selected=Redo)

**Comment by linturaven** [comment]
<img width="738" alt="Снимок экрана 2023-07-06 в 11 55 08" src="https://github.com/consta-design-system/uikit/assets/94055055/b490e802-0595-4a7c-9d6b-90d31d1c0a3e">
Добавили новые иконки для проекта iFDP

**Comment by linturaven** [comment]
i в круге для ДП

**Comment by linturaven** [comment]
<img width="286" alt="Снимок экрана 2023-07-12 в 17 52 23" src="https://github.com/consta-design-system/uikit/assets/94055055/85376a49-c667-466e-ab2c-637c5fcb2a90">
Добавили

**Comment by linturaven** [comment]
<img width="377" alt="Снимок экрана 2023-09-12 в 16 26 26" src="https://github.com/consta-design-system/uikit/assets/94055055/7c07b9e8-a932-4bc1-b52d-62df055fb974">

Изменили @N1MBER

**Comment by linturaven** [comment]
<img width="105" alt="Снимок экрана 2023-09-13 в 15 15 52" src="https://github.com/consta-design-system/uikit/assets/94055055/ca52000c-5ea6-4818-bb0e-3c4049773c01">

И эту обновить
