### ISSUE TITLE
List: Синхронизировать в коде и дизайне

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#2867]
проверить "добавить" и "не найдено"

нужно обсудить настройки листа на страницах других компонентов. Импортируются отдельно или вместе? настраивать внешний вид в компоненте или в листе? и тп **+ написать об этом на портале**

+ подумать над тем, чтобы добавить настройки листа в обзор селекторов (коллапсом и тп), чтобы дать понять как ограничены возможности листа в конкретном компоненте и как его настраивать

**Comment by hell0anna** [comment]
нужно обсудить настройки листа на страницах других компонентов. Импортируются отдельно или вместе? настраивать внешний вид в компоненте или в листе? и тп **+ написать об этом на портале**

**Comment by hell0anna** [comment]
В дизайне пересобрали компонент List

Договорились, что в коде в состоянии Loading размер обертки списка будет стандартным как в дефолтном состоянии (200рх), список элементов не отображаем. Отображаем только индикатор загрузки
