### ISSUE TITLE
List: Добавить заголовок в дизайн

### ISSUE THREAD

**Issue by avtanart** [consta-design-system/uikit#2874]
В дизайне нет варианта с заголовком. Хотя в гайде https://uikit.consta.design/libs/uikit/components-select-stable он есть. 

Также необходимо исправить описание компонента. Сейчас описание и примеры противоречат друг другу.

<img width="890" alt="image" src="https://user-images.githubusercontent.com/59948750/215421344-4d442997-c9fe-4dcc-9fe3-4e5c8b7c88dd.png">

<img width="572" alt="image" src="https://user-images.githubusercontent.com/59948750/215421781-b86074e5-3c5a-4f61-a942-2f51fc38ef0a.png">

**Comment by hell0anna** [comment]
в дизайне есть вариант с заголовком, указывается свойством _header_. В новой сборке будет указываться булиевым свойством _GroupHeader=true_

**Comment by hell0anna** [comment]
примеры поправили
