### ISSUE TITLE
Combobox: добавить SelectAll

### ISSUE THREAD

**Issue by agkruchkov** [consta-design-system/uikit#2891]
Добрый день. 

Предлагаю добавить в Combobox пункт "Выбрать все" (или SelectAll). Пытались сделать это вручную, но у селектов Консты два состояния: выбран или нет. 

Предлагается следующее:
1) Нажатие на пункт "Выбрать все" делает выбранными все видимые элементы
2) Если какие-то элементы вручную сделать невыбранными, то у пункта "Выбрать все" состояние меняется на третий тип: "Выбрано частично". 
3) Нажатие на пункт "Выбрать все" в состоянии "Выбрано частично" делает все видимые элементы выбранными и меняет состояние самого пункта "Выбрать все" на "Выбран". 
4) Нажатие на пункт "Выбрать все" в состоянии "Выбран" сбрасывает выбор со всех видимых элементов и меняет состояние самого элемента "Выбрать все" на "не выбран".
5) Предполагаю, что можно добавить флаг в Combobox нужен этот пункт или нет. Ну и если "Выбрать все" есть в Combobox, то он при задании поиска по элементам не скрывается, а виден всегда.

Вдохновлялись вот этим: https://dev.to/ctrlhack/implementation-of-the-select-all-functionality-using-react-select-package-4dh2

**Comment by gizeasy** [comment]
еще добавить чекбокс на группу
