### ISSUE TITLE
`MixScroll`: добавить миксин для скролов

### ISSUE THREAD

**Issue by gizeasy** [consta-design-system/uikit#2894]
сейчас все скроллы выглядят одинаково, хотелось бы иметь возможность делать их меньше или вовсе скрывать

также убрать из проекта css c определением для всех элементов стилизации скрола `*`

**Comment by lisaovcharenko** [comment]
@gizeasy а к тебе были запросы по этому поводу?

**Comment by gizeasy** [comment]
готово
