### ISSUE TITLE
switch на edge немного стили поехали

### ISSUE THREAD

**Issue by SergeyKatugin** [consta-design-system/uikit#2908]
**Описание бага**
В браузере edge, версия Version 110.0.1587.41 (Official build) (64-bit)
"Шарик" свича немного смещен вверх.
На 11 винде не так сильно
![image](https://user-images.githubusercontent.com/29751109/219305915-3f9b8d24-489e-4866-b4e3-1e04af7aa24b.png)

А на 10 винде, смещение вниз(версия Windows 10 pro, 21H2, браузер edge 109.0.1518.55)
![image](https://user-images.githubusercontent.com/29751109/219306010-06f1f537-a84a-46a0-9735-57b7d16e7e5b.png)

**Как воспроизвести баг** (опционально)  
Просто зашел в консту и сразу же видно ошибку https://uikit.consta.design/libs/uikit/components-switch-stable

**Ожидаемое поведение** (опционально)  
В Chrome "шарик" ровно, хотелось бы как в хроме

**Версия Consta Kit**
4.10.0

**Comment by N1MBER** [comment]
Нет возможности проверить в старой версии (из-за автоматического обновления) в версии 115.0.1901.200, проблемы уже точно нет
