### ISSUE TITLE
Tooltip появляется изначально не в ожидаемом положении и быстро перемещается в нужную позицию

### ISSUE THREAD

**Issue by SergeyKatugin** [consta-design-system/uikit#2909]
**Описание бага**
Повторяется на офф сайте https://uikit.consta.design/libs/uikit/components-tooltip-stable
При первом появлении тултипа, если у него позиция указана сверху(либо с других мест) он сначала появляется сбоку, а потом идет вверх.
И идет блики таким образом

Прикладываю видео
https://user-images.githubusercontent.com/29751109/219307614-75b00ca5-fc2a-47d7-8af6-6e6e42767d8a.mov

**Как воспроизвести баг** (опционально)  
Первый клик на тултип, если тултип показываем сверху

**Ожидаемое поведение** (опционально)  
Тултип появляется сразу в нужном месте и не бликует

**Версия Consta Kit**
4.10.0

**Параметры софта на компьютере:**
windows 11 
chrome Version 110.0.5481.100 (Official Build) (64-bit)

**Comment by gizeasy** [comment]
Мы в курсе об этой проблеме, что вы можете сделать сейчас:
1) Укажие тултипу `direction` в ту с торону в которую он с большей верояностью нормально развернется, `possibleDirections` в той последовательности приоритетов чтобы быстрее нашлась нужная позиция [подробнее про подбор направления](https://consta.design/libs/uikit/components-popover-stable/dev?hash=%D0%BD%D0%B0%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D1%80%D0%B0%D0%B7%D0%B2%D0%BE%D1%80%D0%B0%D1%87%D0%B8%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F)
1) Укажие тултипу постоянную ширину

Мы уже протестировали решение этой проблемы, и скорее всего выпустим уже новый тутлтип, так как апи немного поменяется.

**Comment by gizeasy** [comment]
Исправлено в другой задаче
