### ISSUE TITLE
Selects: Пересборка селектов в дизайне 

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#2921]
- [x] - Устранение расхождений с кодом
- [x] - Пересборка 
- [x] - Не забыть проверить ишью по селектам - возможно, что-то сразу учесть в дизайне

**Comment by hell0anna** [comment]
https://github.com/consta-design-system/uikit/issues/2874
https://github.com/consta-design-system/uikit/issues/2850
