### ISSUE TITLE
UserSelect: Возможность добавления нового элемента 

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#2925]
Всем привет!
Возник запрос на реализацию в UserSelect функционала добавления нового элемента (эта функция реализована у Combobox).
Спасибо )

Проверить если такая возможность в коде и составить пример.

**Comment by Lyubavskaya** [comment]
сделать как в List

**Comment by hell0anna** [comment]
https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?type=design&node-id=116525%3A329424&t=OvFmtzaxIZ0jh5rR-1

**Comment by gizeasy** [comment]
Задача реализована
