### ISSUE TITLE
Docs: Тексты о статусах компонентов на портале

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#2930]
- Тултипы c подсказками на бейджах
- Описания в компонентах Canary, Deprecated

Предложены варианты, отредактированы тексты (Demo): https://www.figma.com/file/GHfK2MTZYaGpSxT7Imv0gM/Consta%3A-%D0%A0%D0%B5%D0%B4%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD-%D0%BF%D0%BE%D1%80%D1%82%D0%B0%D0%BB%D0%B0?node-id=103%3A5937&t=tXvB6MXFF1RQHMEj-1

**Comment by linturaven** [comment]
<img width="755" alt="Снимок экрана 2023-03-01 в 15 44 12" src="https://user-images.githubusercontent.com/94055055/222142886-19521d53-bf71-427c-a900-f96e4c5ea96b.png">

**Comment by linturaven** [comment]
<img width="603" alt="Снимок экрана 2023-03-01 в 15 45 59" src="https://user-images.githubusercontent.com/94055055/222143217-b95f153d-890a-4b20-9ca8-4c13eedfa6e3.png">
