### ISSUE TITLE
IconPlay: Выровнять иконку по весу в контейнере (сейчас кривит в лево)

### ISSUE THREAD

**Issue by Mokudorudoku** [consta-design-system/uikit#2951]
> Полные [правила оформления issue](https://consta-uikit.vercel.app/?path=/docs/common-develop-issues--page)

**Описание бага**
Мы будем рады:

- подробному описанию
- скриншотам и любым другим изображениям  
  Если изображения не прикрепляются к задаче, прикрепите архив или поставьте ссылку на облако. Объём любой, главное — понятно и по-человечески. Хочется, чтобы в любой момент и автору, и исполнителю было понятно, что делать.

**Как воспроизвести баг** (опционально)  
Опишите пошагово

**Ожидаемое поведение** (опционально)  
Опишите ожидаемое поведение

> Если баг в коде, необходимо заполнить поля ниже ↧

**Версия Consta Kit**
Укажите версию

**Параметры софта на компьютере:**

- ОС:
- Браузер и его версия:

**Параметры смартфона:** (опционально)

- Модель:
- ОС:
- Браузер и его версия:

**Дополнительная информация**
Все, что считаете нужным.

**Comment by errorry** [comment]
Поправлены иконки [github issues](https://www.figma.com/file/u4fDZ5rdcEoJUZ7cITlVJx/Github-issues?node-id=3525%3A100079&t=fxWZVcFDOiYbXBqY-1)
так же есть блок с вариантами иконок которые можно добавить

**Comment by linturaven** [comment]
<img width="224" alt="Снимок экрана 2023-09-12 в 16 35 55" src="https://github.com/consta-design-system/uikit/assets/94055055/74b00f53-29a6-4a8e-ba92-44e5af762b9d">

Можно публиковать @N1MBER
