### ISSUE TITLE
Docs: Структура страницы про визуальный язык 

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#2963]
Ссылка на макет:

https://www.figma.com/file/gNkkKAs5u30BkvSFf7GnWX/Consta-Portal?type=design&node-id=2150%3A45209&mode=design&t=dL23B1xXFdNMry84-1

**Comment by BagenovA** [comment]
**Структура страницы:**

1. **Вступление.** Про основные приципы визуальной коммуникации в Consta
2. Работа с цветом. Описание палитры и правил её использования
- Палитры
- Цветовые схемы/темы
3. **Шрифты.** Шрифтовые схемы, типографика и работа с текстом
- Наборы шрифтов
- Размерные сетки
4. **Графика**
- Графические приёмы 
- Иконки
- Иллюстрации
5. **Паттерны**
6. **Отступы**


Вопрос: у нас есть что-то про использование логотипов?

**Comment by BagenovA** [comment]
Драфт статьи: https://docs.google.com/document/d/1HM4OCS2Z-KzZF8SV9WDrvAnhNZzeISj_0k_SZI4D9S0/edit?usp=sharing

**Comment by BagenovA** [comment]
@linturaven прикрепи к задаче ссылку на дизайн
