### ISSUE TITLE
IconTop: поправить размерность, выровнять в контейнере

### ISSUE THREAD

**Issue by hell0anna** [consta-design-system/uikit#2969]
Нужно проверить иконки стрелочек IconTop, IconDown, IconArrowRight, IconArrowLeft, IconArrowUp, IconArrowDown

сейчас иконки стрелочек имеют дробные размеры и криво стоят в контейнере. Нужно выровнять
<img width="565" alt="image" src="https://user-images.githubusercontent.com/51019093/227202732-f688600b-6844-4835-959e-ba24b348023c.png">

**Comment by errorry** [comment]
Поправлены иконки [github issues](https://www.figma.com/file/u4fDZ5rdcEoJUZ7cITlVJx/Github-issues?node-id=3525%3A100079&t=fxWZVcFDOiYbXBqY-1)
так же есть блок с вариантами иконок которые можно добавить
