### ISSUE TITLE
Анимация открытия Sidebar проскакивает и сайдбар вылетает на середину экрана

### ISSUE THREAD

**Issue by idmx** [consta-design-system/uikit#2970]
**Описание бага**
При открытии Sidebar у некоторых пользователей происходит вылет сайдбара на середину экрана перед открытием. Есть вероятность, что это связано как-то с анимацией открытия сайдбара.

Версия консты 4.14.2.

[5253933398983976024.webm](https://user-images.githubusercontent.com/37012523/228143312-61bd0226-9cec-4a2d-89d9-0ad3b3f13227.webm)

**Comment by N1MBER** [comment]
Проверили на версии 4.22, не смогли повторить, посмотри нет ли у тебя стилей, которые перекрывают стили сайдбара. Также обнови версию и попробуй посмотреть снова

**Comment by idmx** [comment]
Нашел в чем причина. Внутри сайдбара параллельно с открытием происходил скролл к нужному элементу коллапса и его открытие и видимо страница не выдерживала напряжения и сайдбар прыгал. Поставил задержку перед скроллом и все стало работать хорошо. Спасибо за потраченное время!
