### ISSUE TITLE
Сhips: Дизайн нового компонента 

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#2980]
![image](https://user-images.githubusercontent.com/75978078/233496904-1035124d-73e3-4379-ae64-22cb76c7919b.png)

**Comment by errorry** [comment]
Спроектированы варианты для темы default. Необходимо отревьюить
[Ссылка на фигму](https://www.figma.com/file/25Ok1NUniIgyxbX0Vw8BoB/Draft.UI-kit?type=design&node-id=2212%3A90390&t=MGe0mGGWhO1QImnn-1)
