### ISSUE TITLE
Badge: Доработать компонент, чтобы можно было использовать как Counter

### ISSUE THREAD

**Issue by linturaven** [consta-design-system/uikit#2981]
Нужен компонент счётчика Counter. Например, для ситуаций, когда необходимо показывать количество пропущенных сообщений или уведомлений.

**Comment by linturaven** [comment]
Можно взять из мобильного кита

**Comment by Lyubavskaya** [comment]
- Проверить, подходящие ли для этих целей варианты размеров
- Подумать над круглой формой (когда в бэйдже одна цифра) 
- Подумать над белой обводкой/тенями

**Comment by Lyubavskaya** [comment]
![image](https://user-images.githubusercontent.com/75978078/234596299-670adbca-a5bc-47cb-b71c-1013ceb6d781.png)
![image](https://user-images.githubusercontent.com/75978078/234596327-cf004de8-af0a-4f9b-9ebb-ff8e8451af13.png)

**Comment by errorry** [comment]
[Ссылка на решение](https://www.figma.com/file/25Ok1NUniIgyxbX0Vw8BoB/Consta.UI-kit.draft?type=design&node-id=2715%3A97319&mode=design&t=XQIxbgHZb7fSmKpX-1)

**Comment by hell0anna** [comment]
нужно подумать и прорисовать крайнее состояние, когда число в каунтере слишком большое. будет ли что-то с ним происходить или нет) Если нет, то прописать это в доке

пока оставляю на ревью
