### ISSUE TITLE
ThemeConstructor: Доработки

### ISSUE THREAD

**Issue by N1MBER** [consta-design-system/uikit#2984]
- [x] баг с сохранением цветов в hsla (не правильный цветовой формат)
- [x]  автосохранение (продумать логику обновлений)

**Comment by linturaven** [comment]
<img width="182" alt="Снимок экрана 2023-04-07 в 11 07 25" src="https://user-images.githubusercontent.com/94055055/230569454-a452fa49-913b-4f65-ba61-0972205dee5e.png">
Элементы выравниваются не относительно центра друг друга

<img width="138" alt="Снимок экрана 2023-04-07 в 11 07 53" src="https://user-images.githubusercontent.com/94055055/230569520-ae7ca6f9-3ae8-4b5f-8607-ed8a4bc8d677.png">
Давай по-умолчанию давать светлую тему + сначала солнышко, потом луна

<img width="284" alt="Снимок экрана 2023-04-07 в 11 08 28" src="https://user-images.githubusercontent.com/94055055/230569634-2dcf7916-8eed-4af4-8e80-7f4e895c5774.png">
Эта кнопка должна отвечать за сохранение, вроде импорт мы хотели пока не делать. Свериться с макетом. Если иппорт возможен — тогда нужны 2 кнопки: импорт + сохранить изменения

<img width="460" alt="Снимок экрана 2023-04-07 в 11 10 09" src="https://user-images.githubusercontent.com/94055055/230569926-a2c4619f-4308-44b4-80e2-251db4899b19.png">
В #ЗНАЧЕНИЯХ невозможна установка букв. Здесь же — давай колорпикер вызывать кликом по всему цветовому прямоугольнику, а кнопку шестерёнки оставим просто иконкой. Нужно будет и мне как-то доработать иконку, чтобы она при разных цветах была различима — иногда её не видно

<img width="193" alt="Снимок экрана 2023-04-07 в 11 13 26" src="https://user-images.githubusercontent.com/94055055/230570479-ac9f259d-c7c2-45ec-8804-b4d8dfcb7046.png">
Кнопка сброса не работает, когда значение в поле модифицировано и не корректно, а будто бы должна

<img width="335" alt="Снимок экрана 2023-04-07 в 11 15 02" src="https://user-images.githubusercontent.com/94055055/230570791-7d3f0ac6-f2fe-4b89-99bf-11cd0e36175b.png">
Переход по этим ссылкам должен сопровождаться моталкой об уходе (есть в макетах)

<img width="377" alt="Снимок экрана 2023-04-07 в 11 17 10" src="https://user-images.githubusercontent.com/94055055/230571134-f272885d-e665-4784-8c07-8ede99949170.png">
Давай сделаем так, чтобы тултип всегда был виден, без клика по кнопки и спозиционируем его внизу от кнопки

<img width="761" alt="Снимок экрана 2023-04-07 в 11 18 08" src="https://user-images.githubusercontent.com/94055055/230571297-2ab66c40-28f8-4af1-8078-90cbff2742bd.png">
Кажется, что в светлой теме некорректный цвет бейджей. По крайней мере надпись у нас там точно не чёрная

В карточках же — проверь соответствует тень той, что стоит в макетах, там она более мягкая, а в коде грубая. Если у нас так сильно они отличаются — нужно будет в будущем решать вопрос этого расхождения

<img width="481" alt="Снимок экрана 2023-04-07 в 11 20 20" src="https://user-images.githubusercontent.com/94055055/230571654-78516344-bd12-4f3a-8152-296d079c2180.png">
Почему-то шрифт в аватарках не такой, как в аватарках в макете (размер/жирность), надо чекнуть

<img width="228" alt="Снимок экрана 2023-04-07 в 11 21 22" src="https://user-images.githubusercontent.com/94055055/230571851-48ca2cf8-4c6d-4359-bd77-40a2e745fdfa.png">
Brand цвет как-то сильно отличается от того, что в дизайне

<img width="319" alt="Снимок экрана 2023-04-07 в 11 21 58" src="https://user-images.githubusercontent.com/94055055/230571986-27131819-d965-4175-9c01-5ff13ab5dea3.png">
Или меня глючит, или цвет этих двух контролов отличается друг от друга (кнопка скачать, чойсгруп) — в дизайне одинаковый

<img width="836" alt="Снимок экрана 2023-04-07 в 11 23 07" src="https://user-images.githubusercontent.com/94055055/230572180-c1820cca-fe67-4fa4-9a92-e40949bec115.png">
Давай не закреплять футер от тестового интерфейса, пусть он будет в самом его конце

<img width="1440" alt="Снимок экрана 2023-04-07 в 11 23 43" src="https://user-images.githubusercontent.com/94055055/230572270-8531c44e-88e9-4cf5-b1a3-16a4a7111ba1.png">
В идеале бы сделать 2 независимых скролла левой и правой части — сейчас сложно сверять конкретную настройку с конкретным куском

<img width="505" alt="Снимок экрана 2023-04-07 в 11 24 27" src="https://user-images.githubusercontent.com/94055055/230572392-7754fd77-bea8-4c9d-b525-0403ed9faf50.png">
В будущем нам нужно будет ещё подумать над настройками отступов, сейчас очень жёстко аффектит макет

<img width="505" alt="Снимок экрана 2023-04-07 в 11 25 59" src="https://user-images.githubusercontent.com/94055055/230572675-2c6897e0-0995-433c-84df-976b91500bd3.png">
Возьми описания базовых цветов из кода наших тем, там они были, как комменты, кажется

<img width="409" alt="Снимок экрана 2023-04-07 в 11 26 47" src="https://user-images.githubusercontent.com/94055055/230572808-ab4bb72a-b89c-4084-b80b-5134db5f6ad7.png">
Сюда я тебе дам гифку

**Comment by Lyubavskaya** [comment]
https://github.com/consta-design-system/theme-constuctor/pull/1

**Comment by N1MBER** [comment]
Поправить zindex у селектор в шрифтах
