### ISSUE TITLE
[3279] ConstaTable: Требования к таблице 

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#2987]
Список требований к таблице (от СИ CAPEX/OPEX):
1. Возможность настройки отображения столбцов (сворачивание/разворачивание)
2. Многоуровневые заголовки (до 4 уровня)
3. Возможность фильтрации в заголовках столбцов:
- по одному значению
- по нескольким значениям
- по диапазону (для числовых)
- с поиском по значениям и возможностью сбросить все
4. Возможность разворачивания строк (иерархия) до 10 уровней вложенности
5. Возможность добавления и редактирования строк
6. Возможность отобразить чекбоксы для выбора строк для массовых действий над ними
7. Возможность настроить цвета/шрифты/размеры содержимого под ГПН
8. Возможность сортировки по столбцу (по возрастанию \ убыванию)
9. Возможность пагинации и скролла с подгрузкой
10. Возможность встроить в строку кастомные элементы (а ля кнопку запихнуть в ячейку) или элементы доп управления (детализация)
11. Возможность кастомизации самого контейнера строки (Details Row) (когда нужно добавить в контейнер строки помимо самой строки что то еще не на уровне столбцов, а самой верстки (скажем результаты расчета каждой строки).

**Comment by nixolympica** [comment]
Добавить возможность вызова тултипа по ховеру на ячейку шапки. 
Кейс: В шапке либо сокращенное название, либо аббревиатура и требуется отображать юзеру подсказку с полным названием. 
![2023-05-24_15-17-35](https://github.com/consta-design-system/uikit/assets/93970306/025ebee4-80a9-4fc2-addf-181b297074e8)

**Comment by Nastya112** [comment]
Добавить возможность выделения нескольких строк через Ctrl (через строки)/Shift (несколько строк одновременно)

Пользователю необходимо выделять несколько объектов для визуализации
Проект Геомейт

**Comment by Lyubavskaya** [comment]
От проекта Система мониторинга недропользования: 

•	minWidth/maxWidth для колонок таблицы
•	выделение строки сейчас происходит с помощью свойства activeRow. Рекомендуется сделать выбор не только одной строки, но и нескольких. В проекте СМН присутствует функционал, использующий множественный выбор строк. 
•	редактирование таблицы, в том числе и по дизайн-составляющей: показать, как должно выглядеть редактирование, желательно на примере (есть). Для редактирования одной ячейки иметь возможность редактировать данные не только с помощью поля input, но и с полями другого типа, которые каким-либо образом вносят данные. Например, выпадающие списки.
•	валидация таблицы, в том числе и по дизайн- составляющей: показать, как должна выглядеть валидация по ячейке/по строке/по столбцу/в целом всей таблицы, с возможным toolTip’ом с текстом ошибки для каждой ячейки. 
•	хотелось бы видеть так же и реализацию server-side операций (группировка, фильтрация, сортировка, пагинация («нативная», «бесконечная»)) в примерах использования Table.
