### ISSUE TITLE
Spoiler: Новый компонент

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#2992]
Компонент, в котором текст скрывается и снизу «расширить» или "Показать еще"
Может быть горизонтальным и вертикальным.
Что-то в этом роде: 
![image](https://user-images.githubusercontent.com/75978078/231431950-f2448911-3c4b-4767-bfba-fe44611a84c1.png)

**Comment by errorry** [comment]
[Ссылка на GitHub](https://www.figma.com/file/u4fDZ5rdcEoJUZ7cITlVJx/Github-issues?type=design&node-id=3599%3A100933&t=u6by6BfJQXEIGDFZ-1)
Добавлен компонент в 3х темах. Необходимо проверить описание и название самого компонента
