### ISSUE TITLE
DragNDropField: 

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#3004]
DragNDropField не работает загрузка нескольких файлов. При указании свойства multiple компонент отдает только последний файл. Если закидывать туда по одному файлу за раз элемент заменяет предыдущий файл на новый, а не добавляет его в File[]. При закидывании нескольких файлов за раз компонент возвращает правильно массив с несколькими файлами. Ниже скрины кода и выводы фалов при закидывании их по очереди. 
![screenshot0-SD-20818028](https://user-images.githubusercontent.com/75978078/233188042-29c97aa6-c9e3-40c3-a353-bc098622b80d.png)
![screenshot1-SD-20818028](https://user-images.githubusercontent.com/75978078/233188067-daff25dd-4797-43f0-a963-b950cc8627d5.png)

**Comment by gizeasy** [comment]
дело в том что компонент отдает событие добавление файлов в 1 момент, а как хранит эти файлы решает проект.
К примеру если вам нужно сохранят все файлы которые пользователь перетаскивает:

```tsx
 const [files, setFiles] = useState<File[]>([]);
 const addFiles = useCallback((files: File[]) => {
    setFiles((state) => [...state, ...files]);
 }, []);

<DragNDropField
 multiple
 onDropFiles={addFiles}
>
```
