### ISSUE TITLE
Navbar: Дизайн нового компонента

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#3008]
- [x] подготовить к переносу в UI-kit
- [x] перенести и добавить 2 темы

https://www.figma.com/file/u4fDZ5rdcEoJUZ7cITlVJx/Github-issues?type=design&node-id=3605%3A101256&mode=design&t=HGplxEIjupkA71S2-1 Секция «Готовое»

**Comment by Lyubavskaya** [comment]
1. Доработать имеющийся Navbar (drawer)
2. Разработать узкий Navbar (rail)
3. Сделать пример с анимацией и миксин для нее

**Comment by gizeasy** [comment]
https://github.com/consta-design-system/uikit/issues/2662

хотелки

**Comment by hell0anna** [comment]
[Drawer](https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?type=design&node-id=133305%3A1137&mode=design&t=o8qkXXx6JZhGT2wz-1)
[Rail](https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?type=design&node-id=133347%3A62078&mode=design&t=o8qkXXx6JZhGT2wz-1)

@BagenovA Настя, глянь пожалуйста тексты

**Comment by BagenovA** [comment]
@hell0anna готово. Оставила комментарии по текстам.

**Comment by BagenovA** [comment]
@hell0anna оставила комментарии по текстам

**Comment by hell0anna** [comment]
[компонент готов](https://www.figma.com/file/LKYyjgQ3khFHvXraZAG1n1/Consta-Components?type=design&node-id=5561%3A6670&mode=design&t=W3eKvYIpaZlXFrIa-1)
