### ISSUE TITLE
portal: Добавить ссылку на канал на портал 

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#3020]

**Comment by linturaven** [comment]
Дизайн готов, смотрите на странице "Спецификации" @gizeasy

**Comment by linturaven** [comment]
https://www.figma.com/file/gNkkKAs5u30BkvSFf7GnWX/Consta-Portal?type=design&node-id=1476%3A98551&mode=design&t=rmWZXERX6qtlHWcV-1
