### ISSUE TITLE
CollapsegroupItem - настроить размеры

### ISSUE THREAD

**Issue by Ilyashis** [consta-design-system/uikit#3024]
нужно посмотреть компонент - CollapsegroupItem
- Размеры отличаются от других компонентов если выбирает по соотвествующему размеру
- При отключение контента внутри, скачет размер по высоте

**Comment by hell0anna** [comment]
@Ilyashis привет! 
подскажи пожалуйста, актуален ли еще 2й пункт? сейчас компонент полностью переделан и его структура немного другая. Второй пункт проверим, его нужно согласовывать с кодом

**Comment by Ilyashis** [comment]
да, все ок
пункт не актуален

**Comment by hell0anna** [comment]
пока на паузе. Договорились, что @linturaven и @Ilyashis обсудят вопрос с размерами в пн (21 авг)

**Comment by Ilyashis** [comment]
Задача не актуальна

**Comment by hell0anna** [comment]
закрываю
