### ISSUE TITLE
Tooltip: добавить возможность делать тултип светлым

### ISSUE THREAD

**Issue by hell0anna** [consta-design-system/uikit#3029]
часто просят дать возможность в светлой теме оставить тултип светлым.
договорились, что по-умолчанию он будет темным, но сделаем пропс, позволяющий переключить его на светлый

в дизайне не отрисовываем, просто пишем в доке на портале и в фигме

<img width="447" alt="image" src="https://user-images.githubusercontent.com/51019093/236137720-81880c61-753d-43cf-bb84-4164f8d1df5a.png">

**Comment by lisaovcharenko** [comment]
@gizeasy что думаешь по этому поводу?

**Comment by gizeasy** [comment]
я думаю, что проблема глубже чем кажется ))) надо пообщаться

**Comment by lisaovcharenko** [comment]
Решили, что пока не готовы добавлять такую возможность, но было бы полезно послушать аргументы "за".
