### ISSUE TITLE
Slider: Добавить возможность менять значение при движении мыши

### ISSUE THREAD

**Issue by iskhakovrr** [consta-design-system/uikit#3031]
В компоненте Slider с type='range' прошу менять значение при движении мыши, а не после отпускания кнопки мыши.
Нужно это для более лучшего понимания текущего значения, ибо сейчас чтобы понять какое значение надо отпустить кнопку мыши (событие onChange).

**Comment by N1MBER** [comment]
Проверить работу и добавить в документацию свойство onAfterChange
