### ISSUE TITLE
DragNDropField: отображения ошибок

### ISSUE THREAD

**Issue by hell0anna** [consta-design-system/uikit#3039]
по результатам ишью #1833 появился вариант отображения ошибок с тултипом
обсудили, что этот вариант не самый удачный

Нужно подумать как правильней отображать кейс с ошибкой загрузки, как смэтчить ошибку загрузки в **Attachment**, обсудить с разработчиками

**БЛОКЕР** https://github.com/consta-design-system/uikit/issues/3346

**Comment by hell0anna** [comment]
на проверку варианты @linturaven 

https://www.figma.com/file/u4fDZ5rdcEoJUZ7cITlVJx/Github-issues?type=design&node-id=4588%3A85230&mode=design&t=iBRjV90qKPNCULwY-1

жду ревью

**Comment by linturaven** [comment]
Оставил комменты @hell0anna
