### ISSUE TITLE
portal: Замена эмодзи

### ISSUE THREAD

**Issue by gizeasy** [consta-design-system/uikit#3047]
Замена эмодзи в блоке около футера

**Comment by hell0anna** [comment]
https://www.figma.com/file/gNkkKAs5u30BkvSFf7GnWX/Consta-Portal?type=design&node-id=1768%3A109678&t=0KrfD6A8zPtEH0HA-1

**Comment by linturaven** [comment]
![Снимок экрана 2023-08-09 в 14 22 19](https://github.com/consta-design-system/uikit/assets/94055055/4e8e6754-1a7d-4cfe-9a1b-d8ddb19e9123)

Я за такие

**Comment by gizeasy** [comment]
> <img alt="image" width="282" src="https://user-images.githubusercontent.com/51019093/262279055-06114a60-ca43-497e-be74-d6dad698b75a.png"> тут у иконки гитхаба фактический размер 18х18рх, а должен быть 24х24. Из-за этого она выглядит меньше, чем иконка с вопросиком

да но если взять эти 2ве иконки в одном размере то они так и смотрятся, кажется нужно их в одну сетку залокать и выровнять размер у самих иконок
