### ISSUE TITLE
Slider: Пофиксить отображение всплывашки со значением слайдера.

### ISSUE THREAD

**Issue by ronyapeperonya** [consta-design-system/uikit#3052]
> Полные [правила оформления issue](https://consta-uikit.vercel.app/?path=/docs/common-develop-issues--page)

**Описание бага**

При наведении курсора на ползунок слайдера, появляется динамическая всплывайшка, которая отображает значение слайдера.
Данная всплывашка перемещается постоянно влево-вправо.

**Как воспроизвести баг** (опционально)  
1) Открывается страница со слайдером.
2) Наводится курсор на ползунок слайдера.
3) Всплывашка перемещается динамически, постоянно, влево-вправо.

**Ожидаемое поведение** (опционально)  
1) Открывается страница со слайдером.
2) Наводится курсор на ползунок слайдера.
3) Всплывашка статична, по отношению к ползунку.

**Дополнительная информация**
Скриншоты не прикрепляются, во время снимка экрана, всплывашка статична.

**Comment by gizeasy** [comment]
#2991 проблема исправиться когда вольем эту прку

**Comment by gizeasy** [comment]
https://github.com/consta-design-system/uikit/pull/2912
