### ISSUE TITLE
Select: добавить поиск по значениям

### ISSUE THREAD

**Issue by avtanart** [consta-design-system/uikit#3065]
При открытии селекта нет возможности найти значение. Было бы удобно добавить такую функциональность для больших баз данных. Сейчас приходится использовать комбобокс, но он не совсем для этого подходит.

**Comment by gizeasy** [comment]
@avtanart в каком кейсе вам не подходит комбобокс?

**Comment by avtanart** [comment]
@gizeasy он не подходит в варианте, когда необходимо только выбрать вариант, а не вписать еще свой. если пользователь введет свой вариант, и он применится, это будет считаться ошибкой. а чтобы не искать значение в селекте в больших БД, желательно иметь поиск по значениям

**Comment by gizeasy** [comment]
> @gizeasy он не подходит в варианте, когда необходимо только выбрать вариант, а не вписать еще свой. если пользователь введет свой вариант, и он применится, это будет считаться ошибкой. а чтобы не искать значение в селекте в больших БД, желательно иметь поиск по значениям 

В комбобокс, есть возможность не создавая нового элемента, просто выбирать из списка и пользоваться поиском.
