### ISSUE TITLE
Select, Combobox: Появление всплывающего окна на Enter

### ISSUE THREAD

**Issue by avtanart** [consta-design-system/uikit#3066]
В текущей реализации неудобно пользоваться селектами и комбобоксами с клавиатуры. Сейчас всплывающее окно появляется только после нажатии стрелки вниз на клавиатуре. Хочется чтобы оно появлялось автоматически в активном состоянии, а стрелками можно было выбрать вариант.

Принудительный вызов всплывающего окна предлагаю сделать на Enter, а не на стрелку вниз.

**Comment by gizeasy** [comment]
реализовали в другой задаче
