### ISSUE TITLE
Combobox: убрать фокусное состояние с крестика

### ISSUE THREAD

**Issue by avtanart** [consta-design-system/uikit#3068]
При переходе по нескольким заполненным комбобоксам с помощью клавиатуры постоянно приходится нажимать на Tab два раза. Мешает крестик для закрытия, его приходится прокликивать. Если можно, то уберите переход на фокусное состояние крестика при управлении с клавиатуры.

https://github.com/consta-design-system/uikit/assets/59948750/8557fcc8-44a4-4f73-820c-8a1972753267

**Comment by gizeasy** [comment]
Реализовали в другой задаче
