### ISSUE TITLE
[3286] Добавление режима alert для кнопки

### ISSUE THREAD

**Issue by SergeyKatugin** [consta-design-system/uikit#3072]
**Описание фичи или улучшения**
Не хватает режима view="alert" для компонента Button.(скриншот ниже)
Так же, когда сами фон устанавливали, не нашли цвета --color-bg-alert с hover
В итоге мы поменяли фон, а ховер не смогли, в итоге ховер сделали синхронным с обычным красным

**Почему улучшение или фича необходима?**
Часто, для кнопки "удалить" дизайнеры делают её красной, что бы пользователю было понятнее

**Реализация предложения**
Добавить новый тип для view и делать новый класс по этому view="alert", в котором фон будет --color-bg-alert, а ховер - это новый цвет, который ваши дизайнеры добавят

**Дополнительная информация**
![image](https://github.com/consta-design-system/uikit/assets/29751109/15ff49d3-766a-427c-b0d0-9b37d6f6aa52)

**Comment by gizeasy** [comment]
Будем решать эту задачу созданием статусных тем для компонетов.
https://github.com/consta-design-system/uikit/issues/3286

**Comment by gizeasy** [comment]
Будем решать эту задачу созданием статусных тем для компонетов.
https://github.com/consta-design-system/uikit/issues/3286
