### ISSUE TITLE
Icons: Возможность накинуть на иконку дополнительные стили в getItemIcon 

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#3073]
"Сейчас в большинстве компонентов есть штука типа getItemIcon и туда просто подставляем иконку
А хотелось чтобы в этот момент можно было на иконку дополнительные стили накинуть" (проект ГРР)

**Comment by N1MBER** [comment]
Можно накинуть стили несколькими способами:

- Создание кастомной иконки

```tsx
const MyIcon: IconComponent = (props) => <ConstaIcon {...props} classname="MyClassName">

<Button iconLeft={MyIcon} />
```

- Указание стилей прямо в свойстве

```tsx
<Button iconLeft={(props) => <ConstaIcon {...props} className="MyClassName" />} />
```
