### ISSUE TITLE
Шаблон чек-листа

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#3075]
### **Проектирование**

 **1. Дизайн**
 [дизайнер ]
 - [ ] продумать образ компонента [?ч]
 - [ ] продумать архитектуру свойств  [?ч]
 - [ ] создать компонент в Figma  [?ч]
 - [ ] продумать адаптив/мобильную версию [?ч]
 - [ ]  сделать версию в тёмной теме  [?ч]
 - [ ] сделать версию в дисплейной теме  [?ч]
 - [ ] оформить страницу компонента  [?ч]
 - [ ] сделать описание компонента [?ч]
 - [ ] *сделать анимацию  [до 1ч]
 - [ ] *сделать обложку  [до 0,5ч]

**2. Ревью дизайна**
[ дизайн-лид ]
- [ ] провести ревью  [до 0,5ч]
- [ ] оформить комментарии [до 0,5ч]

[разработчик]
- [ ] провести ревью  [до 0,5ч]
- [ ] оформить комментарии [до 0,5ч]

[дизайнер]
- [ ] *внести изменения в макеты [?ч]

**3. Подготовка спецификации**
[дизайнер]
- [ ] описать работу компонента [?ч]
- [ ] оформить спецификацию [?ч]

**4. Ревью текста** 
[UX-писатель]
- [ ] провести ревью  [до 0,5ч]
- [ ] оформить комментарии [до 0,5ч]

[дизайнер]
- [ ] *внести изменения в макеты [?ч]

 **5. Передача разработчикам**
[дизайнер]
- [ ] поставить встречу [-ч]
- [ ]  презентовать макет и спецификацию  [до 1ч]
- [ ] оформить мемо по вопросам в issue [до 0,5ч]
- [ ]  *внести изменения в макеты [?ч]
- [ ] передать материалы по макету через issue [-ч]

[разработчик]
- [ ] поучаствовать во встрече, задать вопросы [до 1ч]

**Comment by Lyubavskaya** [comment]
### **Разработка**

- [ ] **1. Погружение**
[разработчик]
- [ ] изучить спецификацию
- [ ] *оформить вопросы в issue
- [ ] продумать архитектуру
- [ ] обсудить архитектуру с лидом

- [ ] **2. Кодинг/тесты**
[разработчик]
- [ ] разбить задачу на функциональные блоки

- [ ] Функциональный блок 1
- [ ] разработать блок
- [ ] написать черновик документации
- [ ] написать тесты
- [ ] отправить PR на ревью

- [ ] Функциональный блок N
- [ ] разработать блок
- [ ] написать черновик документации
- [ ] написать тесты
- [ ] отправить PR на ревью

- [ ] *создать новый репозиторий
- [ ] *оформить витрину и раздел на портале

- [ ] 3**. Ревью**
[дизайнер]
- [ ] провести ревью 
- [ ] оформить комментарии
[разработчик-лид]
- [ ] провести ревью
- [ ]  оформить комментарии
[UX-писатель]
- [ ] провести ревью
- [ ]  оформить комментарии
[разработчик]
- [ ] *внести изменения в код

**Comment by Lyubavskaya** [comment]
### **Релиз**

- [ ] **1. Подготовка RN**
[разработчик-лид] 
- [ ] собрать перечень доработок к релизу
- [ ] подготовить описание для RN
[дизайнер-лид]
- [ ] собрать перечень доработок к релизу
- [ ] подготовить описание для RN

- [ ] **2. Ревью RN** 
[UX-писатель]
- [ ] провести ревью
- [ ]  скорректировать тест

- [ ] **3. Выпуск релиза**
[дизайнер-лид]
- [ ] *подготовить обложку для библиотеки
- [ ]  опубликовать компоненты на команду
- [ ]  *оформить описание библиотеки в Community 
- [ ] опубликовать библиотеку в Community
- [ ] *актуализировать быстрый старт 
- [ ] опубликовать быстрый старт 
- [ ] опубликовать RN в Telegram 

[разработчик-лид]
- [ ] опубликовать релиз и новый NPM пакет
- [ ] проверить коррекность RN в Telegram
- [ ]  обновить портал

**Comment by Lyubavskaya** [comment]
Проектирование
 1. Дизайн[дизайнер ]

 продумать образ компонента [?ч]

 продумать архитектуру свойств  [?ч]

 создать компонент в Figma  [?ч]

 продумать адаптив/мобильную версию [?ч]

  сделать версию в тёмной теме  [?ч]

 сделать версию в дисплейной теме  [?ч]

 оформить страницу компонента  [?ч]

 сделать описание компонента [?ч]

 *сделать анимацию  [до 1ч]

 *сделать обложку  [до 0,5ч]

 2. Ревью дизайна
[ дизайн-лид ]

 провести ревью  [до 0,5ч]

 оформить комментарии [до 0,5ч]

[разработчик]

 провести ревью  [до 0,5ч]
 оформить комментарии [до 0,5ч]
[дизайнер]

 *внести изменения в макеты [?ч]

 3. Подготовка спецификации
[дизайнер]

 описать работу компонента [?ч]

 оформить спецификацию [?ч]

 4. Ревью текста 
[UX-писатель]

 провести ревью  [до 0,5ч]

 оформить комментарии [до 0,5ч]

[дизайнер]

 *внести изменения в макеты [?ч]

 5. Передача разработчикам
[дизайнер]

 поставить встречу [-ч]

  презентовать макет и спецификацию  [до 1ч]

 оформить мемо по вопросам в issue [до 0,5ч]

  *внести изменения в макеты [?ч]

 передать материалы по макету через issue [-ч]

[разработчик]

 поучаствовать во встрече, задать вопросы [до 1ч]

**Comment by gizeasy** [comment]
- - [ ] продумать образ компонента [?ч]
- - [ ] продумать образ компонента 
- - [ ] продумать образ компонента [?ч]
-  - - [ ] продумать образ компонента [?ч]

**Comment by Lyubavskaya** [comment]
- [ ] продумать образ компонента [?ч]
- [ ] продумать образ компонента 
- [ ] продумать образ компонента [?ч]
-  - [ ] продумать образ компонента [?ч]

**Comment by lisaovcharenko** [comment]
Чек-лист готов, задачу закрываю.
