### ISSUE TITLE
Portal: Верифицировать тексты описаний статусов

### ISSUE THREAD

**Issue by linturaven** [consta-design-system/uikit#3080]
Хотим вернуть тултипы по хаверу на статусы компонентов. В тултипах расшифровывается смысл статуса. Необходимо проверить текст на адекватность и передать Андрею в разработку. Можно править напрямую в макете: https://www.figma.com/file/gNkkKAs5u30BkvSFf7GnWX/Consta-Portal?type=design&node-id=1620%3A106606&t=xt4UclzeOI6Nc2Id-1

<img width="1247" alt="Снимок экрана 2023-05-26 в 20 35 34" src="https://github.com/consta-design-system/uikit/assets/94055055/3fbe4c7a-dbed-453e-a481-791da727f44f">

**Comment by BagenovA** [comment]
У статуса In Progress текст тултипа и информера одинаковые. Предложила варианты текста для тултипа в макете (вкладка Local Components).

**Comment by BagenovA** [comment]
@gizeasy можно брать в работу
