### ISSUE TITLE
Добавление компонента "legend"

### ISSUE THREAD

**Issue by SergeyKatugin** [consta-design-system/uikit#3085]
**Описание фичи или улучшения**
Хотелось бы видеть готовый компонент lengend.
В которую мы сможем прокинуть массив объектов, по типу:

```js
[
  {
    label: 'Легенда 1',
    leftComponent: ReactComponent, // Тут можно дать дефолтные компоненты и кастомный
  }
]
```

Пример скриншота 
![image](https://github.com/consta-design-system/uikit/assets/29751109/626f5c0d-8fe4-4797-b14b-e2c047b2104f)

**Почему улучшение или фича необходима?**
Частая фича, нам приходится её делать, мне кажется удачно впишется в вашу либу

**Comment by gizeasy** [comment]
https://consta.design/libs/widgets/components-legend-stable

это подойдет?
