### ISSUE TITLE
doc: Оформить гайд по сборке компонентов на странице портала в разделе Контрибьютерам

### ISSUE THREAD

**Issue by Lyubavskaya** [consta-design-system/uikit#3086]
Гайд в Фигме: https://www.figma.com/community/file/1220795227825907928/%F0%9F%92%A0-%D0%93%D0%B0%D0%B9%D0%B4-%D0%BF%D0%BE-%D1%81%D0%B1%D0%BE%D1%80%D0%BA%D0%B5-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%BE%D0%B2 

смотреть тут https://consta.design/libs/portal/contributers-componentguide

**Comment by hell0anna** [comment]
нужны иллюстрации из оригинального гайда, без них читать гайд сложно

**Comment by hell0anna** [comment]
<img width="854" alt="image" src="https://github.com/consta-design-system/uikit/assets/51019093/86105d1f-cfe8-4667-8a59-00f9365e7bbc">
вот эти штуки выглядят как сломавшиеся информеры) + кажется оранжевый цвет не очень подходит, тк выглядит слишком тревожно. я бы заменила на серый или голубой, если есть потребность в выделении.

**Comment by hell0anna** [comment]
<img width="826" alt="image" src="https://github.com/consta-design-system/uikit/assets/51019093/26714efb-1331-4ed1-893c-7ae8ee2a5552">
пропала нумерация, я бы вернула ее обратно)

**Comment by hell0anna** [comment]
<img width="465" alt="image" src="https://github.com/consta-design-system/uikit/assets/51019093/d802614d-3958-4f89-a9dc-f143a3c9f759">
заголовок третьего(?) уровня выглядит как просто выделенный жирным текст. Мб рассмотреть вариант поднять уровни заголовков на 1 шаг наверх? — нужно обсуждать
