### ISSUE TITLE
DatePicker: Locale en-US не применяется для Time picker type'а

### ISSUE THREAD

**Issue by mnik01** [consta-design-system/uikit#3089]
![image](https://github.com/consta-design-system/uikit/assets/39025497/339e1956-3599-4b40-9291-bed3c3791bd3)

Я выставил en-US locale в сторибуке но все еще вижу русскую локаль в пикере
И нет возможности контролировать формат времени 24/ap&pm

**Comment by N1MBER** [comment]
Текст для локали можно определить так:

```tsx
<DatePicker
  locale={
    {
      ...locale,
      words: { 
        hours:  'H',
        minutes:  'M',
        seconds:  'S',
      }
    }
  }
/>
```

Расширения для формата будут решаться в этой задаче https://github.com/consta-design-system/uikit/issues/2625
