### ISSUE TITLE
Steps: Добавить размер "s" для компонента.

### ISSUE THREAD

**Issue by levi2ki** [consta-design-system/uikit#3106]
Просьба добавить для компонента Steps возможность выбора размера типа "s" - `size: 's' | 'm' | 'l'`

**Почему улучшение или фича необходима?**
В дизайне такая опция уже присутствует
https://www.figma.com/file/cJa9msmHAdUqPyR0kO8hOq/Consta-UI-Kit-(Community)?type=design&node-id=6775-0&t=gyrOZt0egyBzQkON-0

**Comment by N1MBER** [comment]
https://github.com/consta-design-system/uikit/pull/3055
