### ISSUE TITLE
BidirectionalBar: добавить в charts

### ISSUE THREAD

**Issue by gizeasy** [consta-design-system/uikit#3107]
https://charts.ant.design/en/examples/more-plots/bidirectional-bar/#basic

**Comment by hell0anna** [comment]
https://www.figma.com/file/lQJPpOcbtlRk18YSyb6inq/Consta-Charts?type=design&node-id=11196%3A22835&mode=design&t=REqIOLwmD8zESVpS-1

**Comment by hell0anna** [comment]
на странице разработчикам кажется баги в сетке примеров
<img width="415" alt="image" src="https://github.com/consta-design-system/uikit/assets/51019093/f80e811e-6d11-4b33-8bce-084ef55570f3">

**Comment by gizeasy** [comment]
Добавить пример с именами по центру

**Comment by linturaven** [comment]
@hell0anna есть баг, компонент не внутри варианта
![Снимок экрана 2023-08-09 в 14 27 59](https://github.com/consta-design-system/uikit/assets/94055055/3b848236-ed27-4f97-822f-86d47a5c7d69)


И масштабирование не работает
![Снимок экрана 2023-08-09 в 14 28 30](https://github.com/consta-design-system/uikit/assets/94055055/caea0f93-7271-42ef-9201-539516d3c20e)
