### ISSUE TITLE
Button: переделать состояние Loading

### ISSUE THREAD

**Issue by hell0anna** [consta-design-system/uikit#3111]
сейчас состояние загрузки выглядит как заблокированная. Нужно переделать так, чтобы стиль кнопки сохранялся. То есть кнопка **primary** в состоянии loading=true оставалась **синей с белым лоадером**

остальние view по аналогии

**Comment by errorry** [comment]
[Ссылка на решение](https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?type=design&node-id=117366%3A341958&mode=design&t=gKFVMeYwMlABjoOj-1)
