### ISSUE TITLE
ChoiceGroup: Добавить/переработать свойство Checked

### ISSUE THREAD

**Issue by linturaven** [consta-design-system/uikit#3114]
В фигме нет состояния checked. Приходится вручную задавать состояние активной кнопки и неактивной кнопки.

**Comment by linturaven** [comment]
<img width="1050" alt="Снимок экрана 2023-07-12 в 15 03 57" src="https://github.com/consta-design-system/uikit/assets/94055055/c5a278ff-26d5-4205-81c5-eaa4f33747e8">
Включение Disabled хочется перенести в отдельное от view свойство

**Comment by errorry** [comment]
Добавлены переключатели для состояний Active и disable во всех темах
