### ISSUE TITLE
Combobox: Отсутствует настройка Icon

### ISSUE THREAD

**Issue by MyasoutovaTatiana** [consta-design-system/uikit#3115]
нет настройки icon в Label размер M

Сейчас так
<img width="182" alt="Снимок экрана 2023-06-22 в 18 59 08" src="https://github.com/consta-design-system/uikit/assets/108055994/ec6ef517-397d-436a-a0a0-f280aca4bda6">

Должно быть
<img width="198" alt="Снимок экрана 2023-06-22 в 18 59 35" src="https://github.com/consta-design-system/uikit/assets/108055994/4def0994-a621-497c-8b12-4079ec2a8d84">

**Comment by errorry** [comment]
поправлено отображение иконки в размере M во всех темах
