### ISSUE TITLE
Pagination: вместо 10 пунктов сделать 9 пунктов

### ISSUE THREAD

**Issue by MyasoutovaTatiana** [consta-design-system/uikit#3119]
Старый дизайн (Фигма)
<img width="619" alt="Снимок экрана 2023-06-23 в 12 17 09" src="https://github.com/consta-design-system/uikit/assets/108055994/badb5381-d991-4fdb-9aa1-ab9cf55de2cd">
Новый дизайн (Фигма)
<img width="507" alt="Снимок экрана 2023-06-23 в 12 17 50" src="https://github.com/consta-design-system/uikit/assets/108055994/99e847e9-ca8b-4cfd-b116-961ab298b41b">

В коде всегда было сделано 10 внутренних пунктов (без стрелок)
<img width="721" alt="Снимок экрана 2023-06-23 в 12 20 09" src="https://github.com/consta-design-system/uikit/assets/108055994/6f4744b4-b5a5-4ec4-b220-422301b3eaa9">

Проблема: Так как использовался в макетах старый дизайн, то появляются расхождения с кодом. Пагинация занимает больше места, чем расчитывалось в дизайне
Не понятно почему используется 6 внутренних пунктов, а не 5? почему 3 пункта именно справа, а не слева? 
<img width="358" alt="Снимок экрана 2023-06-23 в 12 27 55" src="https://github.com/consta-design-system/uikit/assets/108055994/fd147662-a367-4aee-8af0-410a19fb49c4">

**Comment by hell0anna** [comment]
[готово](https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?type=design&node-id=122921%3A328019&mode=design&t=FjiSo39fBj9l0lc8-1)
