### ISSUE TITLE
DatePicker: не работает ввод даты с клавиатуры

### ISSUE THREAD

**Issue by Neoxenr** [consta-design-system/uikit#3121]
Не работает ввод даты с клавиатуры

**Версия Consta Kit**
4.19.0

**Параметры софта на компьютере:**

- ОС: Linux
- Браузер и его версия: Chrome 114.0.5735.133

**Comment by gizeasy** [comment]
пришлите пожалуйста пример кода в кодсандбокс

**Comment by Neoxenr** [comment]
> пришлите пожалуйста пример кода в кодсандбокс

https://codesandbox.io/s/datepicker-65v34q?file=/package.json

**Comment by gizeasy** [comment]
отключи `StrictMode`
