### ISSUE TITLE
Spoiler: добавить скрытие в 3 точки

### ISSUE THREAD

**Issue by gizeasy** [consta-design-system/uikit#3179]
можно сделать что если указываешь высоту то блюр эффект а если количество строк то три точки

https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp

вроде бы везде работает

**Comment by gizeasy** [comment]
Добавить возможность скрытия кнопки `Свернуть`

**Comment by gizeasy** [comment]
Добавить возможность рулить отступом от кнопки

**Comment by gizeasy** [comment]
Добавить позиционирование копки показать еще

**Comment by linturaven** [comment]
Spoler — всё хорошо, я б единственное пробежался по свойствам перед тем, как релизить
