### ISSUE TITLE
Loader: добавить размер XS

### ISSUE THREAD

**Issue by hell0anna** [consta-design-system/uikit#3186]
возникают ситуации, когда размер S слишком крупный, а XS — нету
например, в кнопках:
<img width="562" alt="image" src="https://github.com/consta-design-system/uikit/assets/51019093/2ac16bc2-373f-4528-bf5b-7be880c5bd4c">

надо добавить

**Comment by errorry** [comment]
Компонент добавлен в [ файл Github issues](https://www.figma.com/file/u4fDZ5rdcEoJUZ7cITlVJx/Github-issues?type=design&node-id=4548%3A2109&mode=design&t=DppERrwh9UvzTXYc-1)
