### ISSUE TITLE
Switch: переключение между двумя состояниями

### ISSUE THREAD

**Issue by AlinaMishchenkova** [consta-design-system/uikit#3191]
![image](https://github.com/consta-design-system/uikit/assets/140629739/13d00643-fd97-4b4e-a844-ba0b22a2a63f)
Предлагаем добавить возможность переключения между двумя состояниями в компоненте Switch, например, между разными котировками или источниками данных.

**Comment by gizeasy** [comment]
@linturaven что думаешь?

**Comment by linturaven** [comment]
Пообщаться поподробнее

**Comment by lisaovcharenko** [comment]
@AlinaMishchenkova компонент Switch используется для работы со значениями true/false (вкл/выкл). В указанном случае подразумевается переключение между несколькими вариантами - для этого лучше использовать компонент ChoiceGroup.
