### ISSUE TITLE
Select: поправить auto layout в компоненте

### ISSUE THREAD

**Issue by MyasoutovaTatiana** [consta-design-system/uikit#3195]
при переключении на заголовок с левой стороны, не подтягивается контейнер модуля

<img width="464" alt="Снимок экрана 2023-08-01 в 14 30 51" src="https://github.com/consta-design-system/uikit/assets/108055994/3d5b42dc-e0f5-4b8b-b831-e2d0284784b4">

**Comment by hell0anna** [comment]
проверила, поправила констрейны. Ждем релиза раскатать обновления
