### ISSUE TITLE
Collapse: перестал работать пропс начального положения иконки

### ISSUE THREAD

**Issue by ArkhipovKI** [consta-design-system/uikit#3220]
В новой версии перестал работать пропс начального положения иконки
<img width="286" alt="Снимок экрана 2023-08-23 в 11 54 33" src="https://github.com/consta-design-system/uikit/assets/75221293/d608e698-08d9-43a4-8f45-98134a38996d">
<img width="739" alt="Снимок экрана 2023-08-23 в 11 55 16" src="https://github.com/consta-design-system/uikit/assets/75221293/4ece1d77-d32c-46fb-b7d6-fbf98fa5aa5e">

**Comment by ArkhipovKI** [comment]
У спойлера такая же проблема, видимо что-то с компонентом самой иконки

**Comment by N1MBER** [comment]
Необходимо обновить версию библиотеки @consta/icons, минимальная версия с которой будет работать 0.6.0
