### ISSUE TITLE
BidirectionalBar: Сделать и поставить обложку карточки компонента

### ISSUE THREAD

**Issue by linturaven** [consta-design-system/uikit#3221]
Не хватает обложки, сейчас стоит заглушка. Как сделаешь — отправь задачу на разработку

**Comment by hell0anna** [comment]
[готово](https://www.figma.com/file/u4fDZ5rdcEoJUZ7cITlVJx/Github-issues?type=design&node-id=2426%3A26259&mode=design&t=d3sMnVkhtMs39wM2-1)

**Comment by linturaven** [comment]
Отдаю в разработку

**Comment by hell0anna** [comment]
[поменяла](https://www.figma.com/file/u4fDZ5rdcEoJUZ7cITlVJx/Github-issues?type=design&node-id=2426%3A26259&mode=design&t=rCkU0Eaye4KCeSMU-1) размер на 200х120
