### ISSUE TITLE
TextField: Некорректно отображается 0 типа number

### ISSUE THREAD

**Issue by Zorblack** [consta-design-system/uikit#3225]
**Описание бага**
Если в параметр value передать 0 типа number, то он некорректно отображается в поле
![image](https://github.com/consta-design-system/uikit/assets/30463870/c9b53d56-c2ea-487c-b8dc-901635323994)

**Как воспроизвести баг** (опционально)  
В параметр value передать 0 типа number

**Ожидаемое поведение** (опционально)  
Корректное отображение 0

**Версия Consta Kit**
4.25.0

**Дополнительная информация**
Другие цифры отображаются корректно. Проблема возникает только для 0

**Comment by N1MBER** [comment]
В типах и списке свойств описано, что value может быть типа `string | null`
