### ISSUE TITLE
DatePicker/landing/storybook/doc: Скрывать выпадающий календарь при потере фокуса

### ISSUE THREAD

**Issue by yurimovo** [consta-design-system/uikit#3229]
**Описание бага**
При потере фокуса не скрывается выпадающий календарь.

**Как воспроизвести баг** (опционально)  
При ручном вводе даты с последующим нажатием Tab выпадающий календарь не скрывается.
![Безымянный](https://github.com/consta-design-system/uikit/assets/81562474/a2c4e00c-4377-4f58-9f46-efa76f5dd8aa)

**Comment by gizeasy** [comment]
уже есть задача исправлящая эту проблему
https://github.com/consta-design-system/uikit/issues/3090

Суть в том что при фокусе календарь и не будет открываться он будет открываться если в фокусном состоянии нажать enter и по tab или esc закроется (ну и клик во вне поля)
