### ISSUE TITLE
Chips: проверить документацю

### ISSUE THREAD

**Issue by gizeasy** [consta-design-system/uikit#3304]

**Comment by BagenovA** [comment]
Оставила комменты по доке: https://www.figma.com/file/25Ok1NUniIgyxbX0Vw8BoB/Consta.UI-kit.draft?type=design&node-id=2490-83846&mode=design&t=THb8dpCIji0OPvGc-0

**Comment by linturaven** [comment]
Здесь финальная версия: https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?type=design&node-id=135102%3A14062&mode=design&t=tNTvWKfitO6NLn14-1 @BagenovA
