### ISSUE TITLE
Portal: добавить опросник

### ISSUE THREAD

**Issue by gizeasy** [consta-design-system/uikit#3305]
- #3306

**Comment by lisaovcharenko** [comment]
Дубль, задачу закрываю. Опросник будет добавлен в рамках эпика https://github.com/consta-design-system/uikit/issues/3320

**Comment by lisaovcharenko** [comment]
Дубль, задачу закрываю. Опросник будет добавлен в рамках эпика https://github.com/consta-design-system/uikit/issues/3320
