### ISSUE TITLE
[3320]ConstaPortal: найти место для кнопки конструктора

### ISSUE THREAD

**Issue by linturaven** [consta-design-system/uikit#3318]
EPIC https://github.com/consta-design-system/uikit/issues/3320
Нужно ещё раз подумать, куда дополнительно можно разместить кнопку перехода на конструктор тем.

**Comment by hell0anna** [comment]
https://www.figma.com/file/gNkkKAs5u30BkvSFf7GnWX/Consta-Portal?type=design&node-id=2284%3A40922&mode=design&t=15bOF0cogNDAJBci-1

ссылки на конструктор добавляем в места:
- делаем отдельную страницу со ссылкой и текстом про конструктор, чтобы он искался в поиске и отображался в меню, в разделе Тематизация и на всех обзорных страницах
- на каждой странице раздела Тематизация добавляем блок со ссылкой на конструктор
- на главной странице добавляем отдельный баннер со ссылкой на конструктор

@BagenovA Настя, тебе делаю отдельную задачку на контент для отдельной страницы + проверку текста на банерах
