### ISSUE TITLE
[3286] Button: статусные кнопки в Коде

### ISSUE THREAD

**Issue by hell0anna** [consta-design-system/uikit#3344]
Добавить свойства и варианты для статусных кнопок.

EPIC: https://github.com/consta-design-system/uikit/issues/3286

Нужно создать библиотеку и темы.

промежуточный результат в дизайне:

https://www.figma.com/file/elVbeup31NtoDiJo3DoRa3/Consta-Default-Status-Colors?type=design&node-id=0%3A1&mode=design&t=cXHTgzx74AKMXbG7-1

дизайн пока на паузе, ждем первых наработок в коде, чтобы понять как будем хранить в дизайн-файлах

**Comment by hell0anna** [comment]
@N1MBER @gizeasy обратите внимание, что для стилей текста в основе используется цвет переменных типа **--color-typo-success** , а для бордеров и заливок **--color-bg-success**

**Comment by lisaovcharenko** [comment]
@gizeasy а какой статус у задачи?

**Comment by hell0anna** [comment]
@gizeasy  задача у тебя на ревью?
