### ISSUE TITLE
Sidebar: Появляется скролл

### ISSUE THREAD

**Issue by monolithed** [consta-design-system/uikit#3352]
Если открыть сайдбар в полноэкранном режиме, то со всех сторон присутствует скролл, хотя скроллировать там нечего.

<img width="500" alt="Screenshot 2023-10-16 at 17 40 18" src="https://github.com/consta-design-system/uikit/assets/803674/f0ca6503-0f24-4876-8253-7c9f45487489">

Воспроизвести можно по [ссылке](https://6jz6xz.csb.app). 
macOS: Сhrome, Safari

**Comment by gizeasy** [comment]
В примере не полосы скролла появляются вне зависимости от SideBar, они сразуже есть. Они появляются из-за дефолтных margin у body
