### ISSUE TITLE
Tabs: Доработать адаптивность

### ISSUE THREAD

**Issue by your-destiny** [consta-design-system/uikit#3364]
## Баг 1

**Описание**
Если fitMode="scroll" и добавлять табы динамически, кнопки для скроллинга не появляются, пока не изменится размер экрана.

**Ожидаемое поведение**
- Появление кнопок для пролистывания табов, если табы не помещаются в области
- Дополнительный пропс для показа кнопок вне зависимости от размера экрана или количества табов

![tabs scroll](https://github.com/consta-design-system/uikit/assets/28622169/7e6a29e9-dec9-4222-8b08-c627a195c01d)

## Баг 2

**Описание**
Если fitMode="dropdown", то выпадающий список появляется не с первого нажатия.

**Ожидаемое поведение**
Исправить появление выпадающего списка.

![tabs dropdown](https://github.com/consta-design-system/uikit/assets/28622169/cd71b4e0-3744-443d-b1fb-c210102a2ad7)

## Дополнительная информация

Воспроизвести баги - https://codesandbox.io/s/tabs-forked-8thfs2
Версия Consta Kit - 4.31.2
ОС - Linux 6.5.5-1-MANJARO
Браузер - Google Chrome 118.0.5993.88

**Comment by N1MBER** [comment]
Первый случай поправил, второй повторяется только в codesandbox, как я понял это проблема уже в самой песочнице и его работе с react-devtools-inline_legacy.

Если я ошибаюсь и второй случай у тебя повторяется локально, то скинь пожалуйста свой пример кода, буду смотреть

**Comment by your-destiny** [comment]
Добрый день
https://github.com/your-destiny/test-issue-3364
