### ISSUE TITLE
DatePicker: обработка ошибок

### ISSUE THREAD

**Issue by nea2310** [consta-design-system/uikit#3373]
**Описание бага**
Поведение демонстрационного примера отличается от того, что описано в документации - при попытке ввести дату From позже даты To происходит автоисправление (даты меняются местами), а ошибка не выводится.

Соответственно, при попытке добавить в код передачу коллбэка в пропсе onError в компонент DatePicker - также происходит автоисправление, коллбэк не вызывается. 
![DatePicker](https://github.com/consta-design-system/uikit/assets/61518711/a28f6e14-7884-43cb-823d-9da375478339)

**Как воспроизвести баг** 
1) Ввести дату начала
2) Ввести дату окончания раньше, чем ната начала
3) Даты поменялись местами, ошибка не появилась

**Ожидаемое поведение**
1) Ввести дату начала
2) Ввести дату окончания раньше, чем ната начала
3) Даты не поменялись местами,  появилась ошибка 

**Версия Consta Kit**
4.28.0

**Параметры софта на компьютере:**

- ОС: Windows 11
- Браузер и его версия: Google Chrome 118.0.5993.117

**Comment by gizeasy** [comment]
Здравствуйте, мы реализовали авто фикс этой ошибки, теперь эта ошибка не обрабатывается. Спасибо что заметили исправим.

**Comment by lisaovcharenko** [comment]
@gizeasy поменяла приоритет, обсудите с Аленой, пжл

**Comment by gizeasy** [comment]
@nea2310 При вводе с клавиатуры в поле ввода, не верного диапазона ошибка стрельнет. А если выбирать с клавиатуры то произойдет автофикс диапазона.
