### ISSUE TITLE
Компонент Tabs: исправить обозначение активного таба при linePosition left и right

### ISSUE THREAD

**Issue by nea2310** [consta-design-system/uikit#3387]
**Описание бага**

**Как воспроизвести баг**
1. Подключить компонент Tabs из трех табов, пропс linePosiotion установить равным left или right
2. Кликнуть на второй или третитй таб
3. Полоса, обозначающая активный таб, остается на уровне первого таба

**Ожидаемое поведение** 
1. Подключить компонент Tabs из трех табов, пропс linePosiotion установить равным left или right
2. Кликнуть на второй или третитй таб
3. Полоса, обозначающая активный таб, перемещается на уровень таба, по которому кликнули

![tabs](https://github.com/consta-design-system/uikit/assets/61518711/b357a420-e717-45e5-8a99-6760da03a786)

**Версия Consta Kit**
4.32.0 

**Параметры софта на компьютере:**

ОС: Windows 11
Браузер и его версия: Google Chrome 118.0.5993.117

Насколько могли заметить, последняя версия, где это работает корректно - 4.28.1

**Comment by gloginov** [comment]
Поддерживаю
При использовании со свойствами  linePosition=left / linePosition=right, не перемещается маркер активного пункта

consta/uikit@^4.31.2

macOS Sonoma 14.0
