### ISSUE TITLE
Docs: Обновить документацию для RcTableAdapter

### ISSUE THREAD

**Issue by Genotroid** [consta-design-system/uikit#3395]
Необходимо обновить документацию в связи с появлением новых свойств, а конкретно showLine, потому что по названию свойства непонятно что конкретно делает новая фича, всей командой надеемся на то, что вы реализовали подобный функционал
![image](https://github.com/consta-design-system/uikit/assets/32167360/448a1244-3e75-49cb-bed3-cb15416c4f64)

**Comment by lisaovcharenko** [comment]
@Genotroid привет! А точно речь про RCTable, а не RCTree?

**Comment by gizeasy** [comment]
Что-то я не наблюдаю у rc-table свойства showLine
У rc-tree есть такое свойство showLine, как то отдельно описывать это свойство не вижу необходимости, так как в документации к rc-tree есть описание
