### ISSUE TITLE
Checkbox: Не сменяется состояние, если отпустить кнопку мыши вне чекбокса

### ISSUE THREAD

**Issue by pavel-sid** [consta-design-system/uikit#3401]
**Описание бага**
Чекбокс не меняет своё состояние, если навести на него курсор и, нажав на левую кнопку мыши, сдвинуть курсор вне границы чекбокса и только потом отпустить кнопку — на чекбоксе выполнится анимация и смена состояния на короткое время, но потом сразу же он вернётся в исходное состояние
Не очень удобно работать с чекбоксами мышкой, когда это делаешь достаточно быстро и чекбоксы далеко друг от друга — невольно кликаешь, уводишь курсор, но отпустить кнопку успеваешь уже за границами

**Как воспроизвести баг** (опционально)  

1. Навести курсор на чекбокс
2. Зажать левую кнопку мыши
3. Увести курсор за границу чекбокса
4. Отпустить левую кнопку мыши

**Ожидаемое поведение** (опционально)  
Чекбокс сменил состояние

**Параметры софта на компьютере:**

- ОС: Win 11
- Браузер и его версия: Chrome 119

https://github.com/consta-design-system/uikit/assets/88885978/c6a76f00-7ebf-42c3-8606-5f6045a59fa1

**Comment by gizeasy** [comment]
это нативное поведение чекбокса, не хотелось бы его менять. Вы можете сверху доработать поведение которое вам требуется

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox
