### ISSUE TITLE
TextField: Добавить rightside в type=number

### ISSUE THREAD

**Issue by lisaovcharenko** [consta-design-system/uikit#3408]
При type=number и increment=false не работает правая часть инпута: невозможно выбрать иконку или поставить текст. Кейс - нет крестика для сброса в поле для ввода числовых значений.

**Comment by linturaven** [comment]
@gizeasy теперь крестик появляется при отключении кнопок инкремента. Но есть баг — если сбросить текст через крестик, при повторном вводе он снова не появляется

**Comment by gizeasy** [comment]
Спасибо поправлю
