### ISSUE TITLE
[3320] Consta Portal: проблема с роутером

### ISSUE THREAD

**Issue by lisaovcharenko** [consta-design-system/uikit#3410]
конструктор тем не открывается в Safari, если переходить через theme-constructor.consta.design

**Comment by gizeasy** [comment]
на сомом портале все работает не открывается конкретно стенд конструктора на отдельном домене, и не только в сафари а везде. Проблема в коде

**Comment by gizeasy** [comment]
если делать вот эту https://github.com/consta-design-system/uikit/issues/2223
то и не надо делать
