### ISSUE TITLE
Нет документации по предыдущей версии uikit v4.33.1

### ISSUE THREAD

**Issue by vitaliidasaev** [consta-design-system/uikit#3422]
> Полные [правила оформления issue](https://consta-uikit.vercel.app/?path=/docs/common-develop-issues--page)

**Описание бага**
Нет документации по предыдущей версии uikit v4.33.1:
ссылка https://v4-33-1.uikit.consta.design/ нерабочая

**Как воспроизвести баг** (опционально)  
в текущей документации только новая версия uikit v5.0.0

**Ожидаемое поведение** (опционально)  
Есть ссылка на документацию предыдущей версии uikit v4.33.1

**Comment by gizeasy** [comment]
@vitaliidasaev, cсылка на стенд кита предыдущей мажорной версии [v4.33.1] https://v4-33-1---uikit.consta.design
