### ISSUE TITLE
withTooltip,Button,Tooltip: Поправить или обновить типизацию, сделать обратную совмеcтимость

### ISSUE THREAD

**Issue by Troonsply** [consta-design-system/uikit#3441]
> Полные [правила оформления issue](https://consta-uikit.vercel.app/?path=/docs/common-develop-issues--page)

У меня установлены следующие версии библиотек consta:
"@consta/icons": "0.0.2",
"@consta/uikit": "^4.6.1",
При обновлении react и react-dom до 18.2.0, начали падать ошибки связанные с типизацией в компонентах или хуках (как withTooltip) которых раньше не было
![image](https://github.com/consta-design-system/uikit/assets/48718025/0037c502-11d9-4a6d-bf06-283a39ed403e)
![image](https://github.com/consta-design-system/uikit/assets/48718025/6b645fa5-2633-4947-90d2-f7c479b240ee)

Прикладываю фото зависимостей
![image](https://github.com/consta-design-system/uikit/assets/48718025/d4312273-2875-4530-9cf4-8f7b0c9e7886)

**Как воспроизвести баг** (опционально)  
Обновить версию реакт на проекте до 18

**Ожидаемое поведение** (опционально)  
Ничего не изменилось

> Если баг в коде, необходимо заполнить поля ниже ↧

**Версия Consta Kit**

"@consta/uikit": "^4.6.1"

**Параметры софта на компьютере:**

- ОС: Windows
- Браузер и его версия:Google Chrome - Версия 120.0.6099.216

**Дополнительная информация**
Эти ошибки не влияют на саму работу компонента, я проставила as any и ничего не изменилось в функциональности или отображении компонентов, работают как прежде, ошибок не выдают

**Comment by gizeasy** [comment]
@Troonsply для начала обнови @consta/uikit, до [0.11.0](https://www.npmjs.com/package/@consta/icons/v/0.11.0)

**Comment by Troonsply** [comment]
> @Troonsply для начала обнови @consta/uikit, до [0.11.0](https://www.npmjs.com/package/@consta/icons/v/0.11.0)

это ссылка на consta/icons точно ее обновить?

**Comment by gizeasy** [comment]
@Troonsply да точно обнови версию "@consta/icons": "0.11.0",

**Comment by Troonsply** [comment]
> @Troonsply да точно обнови версию "@consta/icons": "0.11.0",

обновила, картина та же пока что

**Comment by gizeasy** [comment]
> > @Troonsply да точно обнови версию "@consta/icons": "0.11.0",
> 
> обновила, картина та же пока что

ну ошибка с иконками должна была уйти

**Comment by Troonsply** [comment]
> > > @Troonsply да точно обнови версию "@consta/icons": "0.11.0",
> > 
> > 
> > обновила, картина та же пока что
> 
> ну ошибка с иконками должна была уйти

Эта? 
![image](https://github.com/consta-design-system/uikit/assets/48718025/cd3d71a9-1fa2-4b34-a01d-5fa071d320f3)

**Comment by gizeasy** [comment]
@Troonsply надо будет созвонится, на следующей неделе позвоню.

**Comment by Troonsply** [comment]
> @Troonsply надо будет созвонится, на следующей неделе позвоню.

ок, договорились

**Comment by Troonsply** [comment]
методом удаления о обновления package-lock.json и node_modules , ошибка с иконками решилась)

**Comment by KlochkovIUS** [comment]
У меня Tooltip стал требовать зависимость от placeholder. Выяснилось, что проблема в зависимости от `@types/react`

Если зафиксировать `"@types/react": "18.2.21"` - все работает, а при `"@types/react" :  "18.2.47"` ломается валидация TS. 

У меня стояла зависимость `@types/react" : "^18.0.28"`,  при которой npm фоном поставил 18.2.47 и пошли ошибки

**Comment by Troonsply** [comment]
> "@types/react" : "18.2.47"

ошибку с Popover и Tooltip решило,спасибо!
 но с withTooltip  ошибка типов осталась @gizeasy

**Comment by Troonsply** [comment]
В дополнение к комментриям выше, может кому-то поможет.
Начиная с React 17, типы TypeScript уже включены в сам React, что делает установку "@types/react" и "@types/react-dom" необходимой только если вы работаете с версией React меньше 17, поэтому я не стала фиксировать "@types/react": "18.2.21", а просто снесла его из зависимостей и ошибка с отсутствующим placeholder во всех компонентах ушла.

**Comment by yurrko** [comment]
как самый быстрый способ, чтобы не возиться с типизацией, могу предложить просто переименовать свойство с content на tooltipContent или любой другой, не конфликтующий с react
