### ISSUE TITLE
[3279] Consta Table компонент, проблемы в фильтрами

### ISSUE THREAD

**Issue by Valerdzhan** [consta-design-system/uikit#3444]
Добрый день. Обнаружил баг при использовании фильтров в таблице.
На ноутбуке используется масштаб 125%. При попытке применить фильтр, который не помещается по высоте, он отображается некорректно

Этапы воспроизведения.

1. Создать таблицу с записями
2. Добавить фильтрацию по столбцу
3. Увеличить масштаб чтобы фильтр не помещался по высоте

Ожидание:
- фильтра отобразится целиком, выровненный по нижней границе bottom: 0

Результат

![Consta table filter](https://github.com/consta-design-system/uikit/assets/66295814/128c0818-8d1e-4647-b4f2-5258c4ebe044)

**Comment by gizeasy** [comment]
не актуально для новой таблицы
