### ISSUE TITLE
Tooltip: поправить описание на сайте

### ISSUE THREAD

**Issue by agkruchkov** [consta-design-system/uikit#3448]
Версия uikit 5.0.0

На странице https://consta.design/libs/uikit/components-tooltip-stable/dev
Предлагается импортировать так: import { Tooltip } from '@consta/uikit/TooltipCanary';

Но пакет uikit не в курсе про TooltipCanary. Он готов импортировать так:
import { Tooltip } from '@consta/uikit/Tooltip'

**Comment by alyonurchick1** [comment]
https://github.com/consta-design-system/uikit/pull/3522
