### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by agkruchkov** [consta-design-system/uikit#3453]
Версия uikit@5.0.0

![image](https://github.com/consta-design-system/uikit/assets/61491839/97056be0-a571-49a6-a957-09d8b74ab998)

Используем пагинацию Консты в таком виде:
```
<Pagination
    size="s"
    value={currentPage}
    items={totalPages}
    arrows={[
        { label: 'Назад', icon: IconBackward },
        { label: 'Вперёд', icon: IconForward },
    ]}
    showFirstPage
    showLastPage
    onChange={(pageNumber: number) => {
        setCurrentPage(pageNumber);
    }}
/>
```

Наблюдается ряд багов:
1) Если все страницы помещаются в ряд, то остаются три точки в пагинации в которых нет необходимости (скриншот в начале ишью) 
2) У коллеги на другом проекте наблюдается даже такая картина (три точки между 1 и 2 страницами и почему-то 1 и "три точки"выделены) :
![image](https://github.com/consta-design-system/uikit/assets/61491839/e0dc1ee1-9853-4f10-b386-3244786e3448)

![image](https://github.com/consta-design-system/uikit/assets/61491839/9281a1df-1d46-4125-b323-1abaca9085c3)

3) При первоначальной загрузке страницы не выделяется первая страница если указан флаг showFirstPage (пример можно увидеть на скриншоте в начале ишью). Если кликнуть на любую другую страницу - они начнут становиться активными. Предположительно не устанавливается первой странице селектор `.PaginationItem_active` (только кнопка "Назад" делается не активной). 
4) Так же на сайте Консты на странице пагинации https://consta.design/libs/uikit/components-pagination-stable не работает переход на Codesandbox, кидает на https://codesandbox.io/embed/undefined

Прошу рассмотреть указанные выше вопросы, а так же дополнить сайт примерами использования с возможностью посмотреть код.

**Comment by idmx** [comment]
Если страницы, например, две, то при свойствах showFirstPage и showLastPage вот такая картина
![image](https://github.com/consta-design-system/uikit/assets/37012523/1eb4604e-1290-4de6-a2e9-38769534c583)

Если одна, то вообще вот так
![image](https://github.com/consta-design-system/uikit/assets/37012523/682172bb-3178-4c6c-aba9-85c727c9f135)

Как будто бы можно самим контролировать (вычислять, когда ставить true, когда false, но выглядит это больше как костыль)

**Comment by idmx** [comment]
Дополняю

При нажатии на многоточие происходит также перелистывание на страницу. По идее многоточие не должно быть кликабельное?
