### ISSUE TITLE
Pagination: не во всех вариантах хватает кнопок to first/last

### ISSUE THREAD

**Issue by linturaven** [consta-design-system/uikit#3456]
Нужно добавить кнопки "в начало" и "в конец" через булевы свойства в эти варианты компонента, чтобы они соответствовали реализации в коде:
<img width="622" alt="Снимок экрана 2024-01-17 в 16 19 51" src="https://github.com/consta-design-system/uikit/assets/94055055/d1eeaabc-5ea8-405c-b251-98b9554c3c96">

**Comment by MyasoutovaTatiana** [comment]
добавила кнопки, еще поправила мелкие баги по типу не выбранных пунктов и слетевших цветов
