### ISSUE TITLE
Изменить поведение дейтпикера

### ISSUE THREAD

**Issue by dAkhtyamov** [consta-design-system/uikit#3476]
При клике на вторую дату активируется ввод первой даты
![image](https://github.com/consta-design-system/uikit/assets/157356844/4cc5c373-afcd-4b7b-9602-7ef6eb454c12)

Хотелось бы при выборе редактирования даты, что бы фокус сразу был на ней.
Для того, чтобы пользователям было интуитивно понятно, что при выборе изменения дат, он будет изначально менять ту, которую выбрал

**Comment by gizeasy** [comment]
Дело в том что у нас есть еще и date-time-range, в котором перевод фокуса после выбора дату будет не уместен, так как пользователю возможно потребуется выбрать время.

Рекомендую вам самим реализовать перенос фокуса после выбора одной из дат.
