### ISSUE TITLE
ChipsChoice: добавить возможность задизейблить елемент 

### ISSUE THREAD

**Issue by gizeasy** [consta-design-system/uikit#3486]
по запросу

<img width="510" alt="image" src="https://github.com/consta-design-system/uikit/assets/51019093/f6d536f3-439f-4209-a44c-c00db51b9b05">

**Comment by MyasoutovaTatiana** [comment]
Добавила задизейбленное состояние
https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?type=design&node-id=135102%3A14062&mode=design&t=HXT8eVu89hYytGol-1
