### ISSUE TITLE
Tooltip: Отображение при скролле окна 

### ISSUE THREAD

**Issue by aleviel** [consta-design-system/uikit#3526]
**Описание бага**

есть область со скроллом (например модалка), в ней лежит форма, при валидации отображаются тултипы с ошибками. пока контролы в видимой области тултипы отображаются корректно. 
![image](https://github.com/consta-design-system/uikit/assets/56120255/8d5b04d4-a966-4960-a84f-257405a3c4db)

при скролле контролы (инпуты/кнопки/etc) попадают в невидимую область, но тултип продолжает отображаться и оказывается "подвешен" 
![image](https://github.com/consta-design-system/uikit/assets/56120255/820938e1-eee3-4be8-92f1-b2e153edbc4a)

**Ожидаемое поведение** 
тултипы скрываются при попадании элементов в невидимую область.

**Comment by gizeasy** [comment]
Обновите версию консты, появилась возможность указать [вьюпорт](http://localhost:8080/libs/uikit/components-tooltip-stable/dev?hash=viewport) для для тултипа за пределами которого он будет скрываться по умолчанию это window
