### ISSUE TITLE
[1833] Drag'n'DropField — валидация

### ISSUE THREAD

**Issue by hell0anna** [consta-design-system/uikit#3531]
Ждем дизайн
epic #1833

**Comment by Elena-BLZ** [comment]
Примеры:
1. Простой пример на валидацию размера и количества файлов
2. Асинхронный пример с "валидацией на бэке" fetch -> error,  timeout+loader
3. Большой пример со списком файлов в столбик
4. Пример с квадратными превьюшками и плюсиком

**Comment by Elena-BLZ** [comment]
В дизайне не проработан фокус на компоненте
