### ISSUE TITLE
Проблемы при обновлении до версии 5.0.3

### ISSUE THREAD

**Issue by Valerdzhan** [consta-design-system/uikit#3542]
Добрый день. Возникла небольшая проблема с обновлением @consta/uikit до версии 5.0.3 
при обновлении просит понизить версию для 
date-fns@"^2.30.0" from @consta/uikit@5.0.3 и 
react-dropzone@"11.3.4" from @consta/uikit@5.0.3

Посмотрите пожалуйста, и если есть возможность, то обновите зависимости.
Спасибо

**Comment by gizeasy** [comment]
@Valerdzhan, обнови консту до последней в ней react-dropzone используется последний.

а вот с date-fns, придется понижать, ну либо надеется что ни что не сломается))

пока завел ишью https://github.com/consta-design-system/uikit/issues/3677
