### ISSUE TITLE
[3543] Loader: добавить размер XS в фигму

### ISSUE THREAD

**Issue by hell0anna** [consta-design-system/uikit#3544]
1. в коде есть размер XS, нужно добавить его в фигму
2. заменить в кнопке в размере XS лоадер на XS
3. пройтись по всем компонентам, заменить на меньший лоадер там, где это нужно (+составить список компонентов,, где размер лоадера был изменен, записать в эту задачу)

Epic #3543

**Comment by MyasoutovaTatiana** [comment]
Список компонентов: 
Button
Chips
List
