### ISSUE TITLE
DatePicker: При первом рендере два раза вызывает callback onDropdownOpen

### ISSUE THREAD

**Issue by KlochkovIUS** [consta-design-system/uikit#3559]
**Описание бага**
При первом рендере (зависимость отображения от внешнего стейта) два раза вызывает callback onDropdownOpen со значением `open = false`. Далее, при необходимости меняет на  `dropdownOpen` (оптять же вызывая `onDropdownOpen `).

В итоге, если в  `dropdownOpen` передавать стейт обновляющийся по зависимости в `onDropdownOpen`, то получим 2 варианта поведения
1.  Елси `initialState` для  `dropdownOpen` будет `false`, то получим 2  вызова функции `onDropdownOpen(false)`
2.  Елси `initialState` для  `dropdownOpen` будет `true`, то получим вечный цикл.

**Как воспроизвести баг**
```
export const DatePickerBugExample = () => {
    const [isShow, setShow] = useFlag(false)
    const [value, setValue] = useState<Date | null>(null);
    const [isOpen, setOpen] = useFlag(true);
    const onDropdownOpen = useCallback((open: boolean) => {
        console.log('onDropdownOpen', open, isOpen)
        setOpen.set(open);
    }, []);

    return (
        < >
            <Button
                onClick={() => setShow.toggle()}
                label="Test"
            />
            {isShow ? <DatePicker
                placeholder="Выберите вариант"
                value={value}
                onChange={setValue}
                onDropdownOpen={onDropdownOpen}
                dropdownOpen={isOpen}
            /> : null}
        </>)
};
```

![image](https://github.com/consta-design-system/uikit/assets/48911799/9da25df3-59cc-470b-bb15-598c3d003abb)

**Ожидаемое поведение** (опционально)  
При появлении DatePicker не вызывается callback onDropdownOpen

> Если баг в коде, необходимо заполнить поля ниже ↧

**Версия Consta Kit**
"@consta/uikit": "^5.0.3"

**Comment by Elena-BLZ** [comment]
Добавить зависимости в useEffect
