### ISSUE TITLE
Badge: Увеличить отступы в размере S

### ISSUE THREAD

**Issue by linturaven** [consta-design-system/uikit#3560]
<img width="834" alt="Снимок экрана 2024-03-01 в 15 32 58" src="https://github.com/consta-design-system/uikit/assets/94055055/af1e1a4e-1d0b-418f-ab89-b2107da6dcbd">

У бейджа в размере S левый и правый отступ от текста не пропорционален другим размерам и сильно маленький. Необходимо рассмотреть возможность изменения размера отступа.

<img width="386" alt="Снимок экрана 2024-03-01 в 15 36 50" src="https://github.com/consta-design-system/uikit/assets/94055055/b6d20de4-42ef-49a8-a4b1-530d4ce2f2f6">

P.S. В дизайне отступы чуть больше, чем в коде.

**Comment by linturaven** [comment]
@gizeasy проверили, ошибка в коде

**Comment by linturaven** [comment]
@gizeasy оно на ревью, есть ПРка?

**Comment by gizeasy** [comment]
@linturaven готовая https://github.com/consta-design-system/uikit/pull/3598
