### ISSUE TITLE
Badge: добавить transparent view 

### ISSUE THREAD

**Issue by willadiym** [consta-design-system/uikit#3561]
В проектах часто бывает ситуация, когда filled бэйджи слишком яркие и из-за этого выбиваются.
на подумать: может добавить вью бейджика, где его фон полупрозрачен, по примеру 
<img width="92" alt="image" src="https://github.com/consta-design-system/uikit/assets/160031322/46926274-b0d7-429f-8f12-b892c1120318">

**Comment by linturaven** [comment]
@MyasoutovaTatiana Возьми в эпик по бейджам, которые прозрачные с обводкой, как новый информер

**Comment by MyasoutovaTatiana** [comment]
[макеты](https://www.figma.com/design/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=235-37206&t=hPZkbtutsUQWeQFD-1) готовы
