### ISSUE TITLE
Tasks: Завести ишью по комментариям из Figma

### ISSUE THREAD

**Issue by linturaven** [consta-design-system/uikit#3585]
Что надо сделать:
1. Посмотреть все комменты у компонетов в Figma
2. Создать ишью по комментариям:
- Если уверена, что коммент точно уходит в ишью - заводи
- Если не уверена - спроси у меня и я скажу, что делать
- Если это просто вопрос (даже с ответом) или абстрактный коммент - собери сюда списком вопрос + ответ (если есть)

**Comment by MyasoutovaTatiana** [comment]
**Вопросы**:
_ChoiceGroup (Canary)_ — почему состояния (Empty, choice (нет такого), disabled) лежат в view? Ориентируясь на другие элементы ДС, этот сбивает с толку где я могу поменять состояние ячейки
_Slider (Canary)_ — МБ сделаем версию с контролами под?
_Button_ — у кнопок нет ховер эффектов?
_Chips (Canary)_ — добавить стрелочки?
_ContextMenu (canary)_ — не понятно какую задачу решает доп. слой Layout в компоненте. В других компонентах есть скролл. мб он тут тоже должен быть?
_Pagination (Canary)_ — когда мы отключаем DESCRIPTION  не должна ли высота компонента подтягиваться под высоту области цифр?
_List_ — List единственный компонент где используется Disabled loader. С чем это связано?
_UserSelect_ — Что за ботомЛейбл?
_Table_ — коллеги, проверьте, правильно ли что кнопка не активна. 
_Table_ — состояние когда фильтруем по нескольким столбцам сразу, и когда нет результатов
_Scrollbar_ — непонятные цвета без привязки(

**Предложения:**
_Attachment_ — мб добавите для не одну, а группу кнопок, хотя бы 3. очень часто бывает такое, что можно не только удалить, но и скачать файл
_User_ — Предлагали выводить статус в выпадающем списке
_BookmarkTabs (Canary)_ — - неудобно, можно было бы разнести по левой и правой стороне. - что именно? - стрелки разных направлений рядом, лучше разносить их по левую и правую сторону, а в центре вкладки
_Combobox_ — Может для варианта "выбрать всё" в инпуте выводить не все теги, а просто слово Все? Так будет понятно, что выбрано действительно всё, а по одним лишь тегам непонятно всё выбрано или не всё.
_Table_ — давайте внутри не fixed, а hug  сделаем? в случае, если размер инпута понадобиться изменить, при этом оставить все атрибуты текущего размера самой ячейки
_Snackbar_ — нужно на портале добавить вкладку "как использовать" с описанием рекомендаций по тексту/кнопкам/таймеру

Задачи:
[issue #2794](https://github.com/consta-design-system/uikit/issues/2794)
https://github.com/consta-design-system/uikit/issues/3603
https://github.com/consta-design-system/uikit/issues/3604
https://github.com/consta-design-system/uikit/issues/3605


Оставшиеся комментарии в фигме нужно обсудить с @linturaven @hell0anna и @allamukhamedzynova (заметки к каким-то задачам)

**Comment by MyasoutovaTatiana** [comment]
**По этому коменту:**
Combobox — Может для варианта "выбрать всё" в инпуте выводить не все теги, а просто слово Все? Так будет понятно, что выбрано действительно всё, а по одним лишь тегам непонятно всё выбрано или не всё.

в коде сейчас так и реализовано
<img width="445" alt="Снимок экрана 2024-04-08 в 14 46 12" src="https://github.com/consta-design-system/uikit/assets/108055994/85d29e20-74e8-4a27-aef3-fcef33c6abb0">

**Comment by linturaven** [comment]
> _ChoiceGroup (Canary)_ — почему состояния (Empty, choice (нет такого), disabled) лежат в view? Ориентируясь на другие элементы ДС, этот сбивает с толку где я могу поменять состояние ячейки

Попробовать переработать свойства (в первую очередь под код)


> _Slider (Canary)_ — МБ сделаем версию с контролами под?

Делаем


> _Button_ — у кнопок нет ховер эффектов?

Надо завести большую задачу, где мы снова разберём вопрос про прототипирование


> _Chips (Canary)_ — добавить стрелочки?

Добавить розовые стрелочки, можно взять из примеров в Table


> _ContextMenu (canary)_ — не понятно какую задачу решает доп. слой Layout в компоненте. В других компонентах есть скролл. мб он тут тоже должен быть?

Вероятнее всего он сделан для скроллбара, надо разобраться добавлять его туда или нет, чтобы было единообразно с остальными компонентами


> _Pagination (Canary)_ — когда мы отключаем DESCRIPTION не должна ли высота компонента подтягиваться под высоту области цифр?

Должна, в коде сделано правильно


> _List_ — List единственный компонент где используется Disabled loader. С чем это связано?

Непонятно с чем, надо принять решение, что вообще делать с лоадером в листе, собрать рефы с разных продуктов и кодпена. Возможно придём к тому, что положим скелетон (полностью пустое состояние с подгрузкой и подгрузка дополнительных элементов)


> _UserSelect_ — Что за ботомЛейбл?

Это Caption, скорее всего нужно поправить названия во всех инпутах, можно протестить плагином Propstar и посмотреть, какие названия он даст, если Caption по результатам теста — переименовываем везде, если нет — надо снова обсуждать, может быть проблема в слоях и свойствах


> _Table_ — коллеги, проверьте, правильно ли что кнопка не активна.

Неправильно, должна быть активна


> _Table_ — состояние когда фильтруем по нескольким столбцам сразу, и когда нет результатов

Нужно добавить пример в котором фильтрация идёт по двум столбцам и изобразить состояние, когда фильтры настроены так, что в таблице пусто, нет выдачи


> _Scrollbar_ — непонятные цвета без привязки(

Заводить ишью и обсуждать, возможно оставим так, возможно пересмотрим переменные цвета

**Comment by linturaven** [comment]
> _Attachment_ — мб добавите для не одну, а группу кнопок, хотя бы 3. очень часто бывает такое, что можно не только удалить, но и скачать файл + у атачмента свойство с датой загрузки и размером файла скорее caption, а не label мб

Берём в работу, с учетом того, что нас устраивает, что компонент можно использовать и в контексте загрузки на сервис, и в контексте просмотра списка файлов + да, caption, а не Label, возьмем за правило, что Label наверху



> _BookmarkTabs (Canary)_ — - неудобно, можно было бы разнести по левой и правой стороне. - что именно? - стрелки разных направлений рядом, лучше разносить их по левую и правую сторону, а в центре вкладки

Рассмотрел бы, как альтернативное расположение кнопок + возможно в компоненте стоит предусмотреть листинг всех вкладок (видел в гугл таблицах)



> _Combobox_ — Может для варианта "выбрать всё" в инпуте выводить не все теги, а просто слово Все? Так будет понятно, что выбрано действительно всё, а по одним лишь тегам непонятно всё выбрано или не всё.

В коде так и работает, но нужно добавить в фигму свойство, чтобы быстро включать и пример



> _Table_ — давайте внутри не fixed, а hug сделаем? в случае, если размер инпута понадобиться изменить, при этом оставить все атрибуты текущего размера самой ячейки

Разобраться в комментарии



> _Snackbar_ — нужно на портале добавить вкладку "как использовать" с описанием рекомендаций по тексту/кнопкам/таймеру

Задача уже есть

**Comment by MyasoutovaTatiana** [comment]
Задачи:
https://github.com/consta-design-system/uikit/issues/3623
https://github.com/consta-design-system/uikit/issues/3622
https://github.com/consta-design-system/uikit/issues/3621
https://github.com/consta-design-system/uikit/issues/3620
https://github.com/consta-design-system/uikit/issues/3619
https://github.com/consta-design-system/uikit/issues/3618
https://github.com/consta-design-system/uikit/issues/3617
https://github.com/consta-design-system/uikit/issues/3616
https://github.com/consta-design-system/uikit/issues/3615
https://github.com/consta-design-system/uikit/issues/3614
https://github.com/consta-design-system/uikit/issues/3613
https://github.com/consta-design-system/uikit/issues/3612
https://github.com/consta-design-system/uikit/issues/3611
https://github.com/consta-design-system/uikit/issues/3610
https://github.com/consta-design-system/uikit/issues/3609
