### ISSUE TITLE
DatePicker устранить ошибку очистки поля

### ISSUE THREAD

**Issue by shushLaris** [consta-design-system/uikit#3588]
**Описание бага**
При попытке очистить поле компонента в консоль валится предупреждение, при этом не происходит изменение значения даты на null

```

Element value was changed outside of mask. Syncronize mask using mask.updateValue() to work properly. 

```
**Как воспроизвести баг** (опционально)  
Попытаться очистить дату в датапткере по кнопке. Например, на стенде

**Ожидаемое поведение** (опционально)  
Значению присвоен null, никаких сообщений в консоли

**Версия Consta Kit**
5.1.0

**Comment by gizeasy** [comment]
исправлено
