### ISSUE TITLE
loader: Сделать новый более удобный в работе дизайн компонента

### ISSUE THREAD

**Issue by linturaven** [consta-design-system/uikit#3589]
Можно поискать референсы тут https://codepen.io/nikhil8krishnan/pen/rVoXJa

**Comment by MyasoutovaTatiana** [comment]
добавить в UI-kit

loader dots
loader circle

**Comment by MyasoutovaTatiana** [comment]
Дизайн готов
https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?type=design&node-id=2334%3A37477&mode=design&t=8HSzaWcLV1zff2kl-1

Скорость анимации как у ProgressSpin
Движение по часовой стрелке
