### ISSUE TITLE
Attachment: добавить группу кнопок

### ISSUE THREAD

**Issue by MyasoutovaTatiana** [consta-design-system/uikit#3619]
очень часто бывает такое, что можно не только удалить, но и скачать файл.
Берём в работу, с учетом того, что нас устраивает, что компонент можно использовать и в контексте загрузки на сервис, и в контексте просмотра списка файлов

**Comment by MyasoutovaTatiana** [comment]
@linturaven @allamukhamedzynova что по задаче?

**Comment by allamukhamedzynova** [comment]
https://www.figma.com/design/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=43155-107729&t=n0EOwu2ErIF2YU4H-1
