### ISSUE TITLE
Table: добавить возможность зафиксировать колонки справа

### ISSUE THREAD

**Issue by korolevevev** [consta-design-system/uikit#3624]
**Описание**
Добавить возможность указывать количество колонок, которое нужно зафиксировать (stickyColumns) с правой части таблицы

**Почему улучшение необходимо?**
Кейс: при наведении на таблицу в видимой части справа должны быть действия с данной строкой (ячейка с набором кнопок, например). Сейчас это можно реализовать только слева. Особенно актуальна проблема в таблице с горизонтальным скроллом, когда крайние правые столбцы не отображаются в видимой части таблицы, и до них надо скроллить.

**Реализация предложения**
Добавить атрибут stickyColumnsRight или дать возможность указывать stickyColumns в виде массива [1, 1] для правой и левой части таблицы.

**Comment by gizeasy** [comment]
в новой таблице это возможно
