### ISSUE TITLE
Table: добавить возможность позиционировать элементы в строке относительно её видимой части

### ISSUE THREAD

**Issue by korolevevev** [consta-design-system/uikit#3625]
> Полные [правила оформления issue](https://consta-uikit.vercel.app/?path=/docs/common-develop-issues--page)

**Описание улучшения**
Добавить возможность привязываться к контейнеру видимой части компонента Table или конкретной строке.

**Почему улучшение необходимо?**
Кейс: реализация появления справа в строке контекстных действий со ней при наведении. Если у таблицы есть горизонтальный скролл, то контекстные действия либо находятся в крайней правой невидимой части таблицы, до которой надо скроллить, либо их приходится размещать и фиксировать в столбце слева (что является костылём и компромиссом).

**Реализация предложения**
Сейчас при наведении на строку можно, к примеру, делать видимым крайний правый столбец и позиционировать контейнер в его ячейке "fixed". Однако при вертикальном скролле ячейки действий отрываются от строк (строки скроллятся, а контекстные действия - нет). Как вариант можно доработать этот момент с помощью рефов на видимую часть таблицы, а не на весь её контейнер. В текущем виде навешивание рефа через атрибут ref таблицы никак не помогает.

**Comment by gizeasy** [comment]
у popover и tooltip появилась возможность указания вьюпорта https://consta.design/libs/uikit/components-popover-stable/dev?hash=viewport

что решит вашу проблему
