### ISSUE TITLE
TextField и DatePicker

### ISSUE THREAD

**Issue by AnastasiaAvilova** [consta-design-system/uikit#3645]
**Описание бага**

в TextField  не пропадает clearButton когда сетаешь null, затем пропадает, если кликнуть в поле
в DatePicker, если value установлено  например value = new Date, то поле не очищается, если сетаешь value в null  и не работает очистка через clearIcon 
----

Добрый день, нашла 2 бага с TextField и DatePicker. Она появляютс, когда пытаюсь очистить оба поля
проблема с TextField : не пропадает clearButton когда сетаешь null, затем пропадает, если кликнуть в поле
проблема с DatePicker, если value установлено  например value = new Date, то поле не очищается если сетаешь value  в null  и не работает очистка через clearIcon 

> Если баг в коде, необходимо заполнить поля ниже ↧

import { TextField } from '@consta/uikit/TextField';
import {DatePicker} from "@consta/uikit/DatePicker";
...
  const [date, setDate] = useState<Date | null>(new Date());
  const [text, setText] = useState<string | null>(null);

  const handleClear= useCallback(() => {
    setDate(null);
    setText('')
  }, []);

...

  return (
       <div>
                <Button
                  label="Сбросить все"
                  view="clear"
                  className={cx('text-[14px] p-0', styles.iconButton, styles.primaryLinkButton)}
                  onClick={handleClear}
                />
                <TextField
                  label={"Text"}
                  onChange={setText}
                  value={text}
                  className={styles.input}
                  withClearButton
                />
                <DatePicker
                  label={"Date"}
                  withClearButton
                  onChange={setDate}
                  value={date}
                  placeholder="ДД.ММ.ГГГГ"
                  className={styles.input}
                />
              </div>
)

![v1](https://github.com/consta-design-system/uikit/assets/22530737/047069d4-4702-4dca-a9dd-aabd78ca297a)

**Версия Consta Kit**

"@consta/uikit": "^5.2.0",
"react": "^18.2.0",
"react-dom": "^18.2.0",

**Comment by ZettZet** [comment]
@gizeasy issue не закрылась

**Comment by gizeasy** [comment]
@ZettZet я хотел еще проверить, и в итоге еще проблемку нашли. Такое чувство что imask c обновлением сломал автоматическую синхранизации или она стала работать по другому, вообщем в ручную синхронизировал маску и текстовое поле и стало нормально. 

Создал, демку пакета, как проверят на проекте что все ок, так волью изменения
