### ISSUE TITLE
UserSelect: поправить положение стрелочки

### ISSUE THREAD

**Issue by hell0anna** [consta-design-system/uikit#3649]
у компонента userselect в размере S с закрытым и открытым списком стрелочка скачет вверх-вниз (см скрины)
нужно отцентрировать ее положение

<img width="429" alt="image" src="https://github.com/consta-design-system/uikit/assets/51019093/b8f9984b-7927-4c76-a076-73d6ca850e1b">

<img width="403" alt="image" src="https://github.com/consta-design-system/uikit/assets/51019093/94869c49-ce53-4107-ab9d-87eb4c3b4b1e">

**Comment by ZettZet** [comment]
Да не сказать, что он в остальных компонентах отцентрован

Вот они, слева на право: 
- UserSelect
- Select
- Combobox

![Screen Shot 2024-06-02 at 21 30 51](https://github.com/consta-design-system/uikit/assets/55871784/5ae95ea2-272e-4cfc-9f64-25fca476835d)

![Screen Shot 2024-06-02 at 21 28 01](https://github.com/consta-design-system/uikit/assets/55871784/e03575b4-0b89-4da7-9345-6d1322bebc96)
![Screen Shot 2024-06-02 at 21 27 08](https://github.com/consta-design-system/uikit/assets/55871784/27a08fe8-6c06-42c9-8be1-46848349e668)
![Screen Shot 2024-06-02 at 21 26 03](https://github.com/consta-design-system/uikit/assets/55871784/1489d0c6-13dd-4fda-80a5-2ae4fb21e5d6)
![Screen Shot 2024-06-02 at 21 24 12](https://github.com/consta-design-system/uikit/assets/55871784/64d628fb-8d8c-4e8f-981f-c4712414a9a6)


А вообще, выглядит так, будто эта иконка неправильно импортирована в consta/icons

![image](https://github.com/consta-design-system/uikit/assets/55871784/5e08e1a2-fe04-46c5-86a6-cdd169b672e3)

Она в себе содаржит отступы, а с такими иконками работать сложнее стократно, ибо `rotate(180deg)` перстает работать, как должно.

Нужна проработка

**Comment by hell0anna** [comment]
@gizeasy проверила дизайн, там иконка уже отцентрирована
нужно обновить иконки iconSelect и iconSelectOpen и обновить их в компонентах со списками (userselect, Select, Combobox)
