### ISSUE TITLE
Tooltip: исправить типизацию

### ISSUE THREAD

**Issue by MeowDevoteam** [consta-design-system/uikit#3655]
> Полные [правила оформления issue](https://consta-uikit.vercel.app/?path=/docs/common-develop-issues--page)

**Описание бага**
Проблема с типизацией компонентов с версией пакета `"@types/react": "^18.3.2"`. Помимо Tooltip'a задеты ещё некоторые компоненты.
![image](https://github.com/consta-design-system/uikit/assets/100582087/7ffc4bfe-e9bb-4955-b93b-63152cbe122e)

**Как воспроизвести баг** (опционально)  
Опишите пошагово
1. bun create vite vite-react --template react
2. bun add @consta/icons @consta/uikit
3. Добавить компонент тултипа в код 

> Если баг в коде, необходимо заполнить поля ниже ↧

**Версия Consta Kit**
@consta/uikit@5.3.1

**Параметры софта на компьютере:**

- ОС: Manjaro Linux Vulcan 23.1.4 x86_64
- Браузер и его версия: Google Chrome Version 124.0.6367.201 (Official Build) (64-bit)

**Дополнительная информация**
Подробнее в https://github.com/creativetimofficial/material-tailwind/issues/528

**Comment by ZettZet** [comment]
Более релевантная инфа в https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/69006 и https://github.com/microsoft/TypeScript/issues/57779
Там же есть обходные варианты, как например module augmentation, или понижение версии `@types/react` в проекте
Похоже, это проблема на уровне TS
