### ISSUE TITLE
onChange перестал функционировать во всех элементах после обновления версии

### ISSUE THREAD

**Issue by lolliuym** [consta-design-system/uikit#3657]
Все поля, включая TextField, Select, UserSelect и другие, перестали работать после обновления с версии 4.33.1 на 5.3.1. События onChange перестали отслеживаться. При этом все элементы остаются видимыми.

Список версий:
    "@consta/charts": "^1.0.0",
    "@consta/header": "^3.0.0",
    "@consta/icons": "^1.0.1",
    "@consta/uikit": "^5.3.1",

**Comment by ZettZet** [comment]
В соответствии с [changelog v5.0.0](https://github.com/consta-design-system/uikit/releases/tag/v5.0.0), мажорная версия 5.х.х несёт в себе изменения, ломающие обратную совместимость.
Это не баг
