### ISSUE TITLE
Добавить новые иконки расширений vsdx, vsd, msg для компонента Attachment.

### ISSUE THREAD

**Issue by VTSgit** [consta-design-system/uikit#3682]
> Полные [правила оформления issue](https://consta-uikit.vercel.app/?path=/docs/common-develop-issues--page)

**Описание фичи или улучшения**
У компонента Attachment нету иконок для vsd, vsdx, msg расширений нет иконок расширения. 
![image](https://github.com/consta-design-system/uikit/assets/70096379/a2813eda-db5d-4584-b884-f2dca72a5f4e)
![image](https://github.com/consta-design-system/uikit/assets/70096379/fc0e6d07-e0b1-4fe7-b35c-717cafb71e1a)
![image](https://github.com/consta-design-system/uikit/assets/70096379/4bafbff0-600a-4e32-8ac4-d08675f82f7c)

**Почему улучшение или фича необходима?**
Для всех остальных расширений есть, а для этих почему то нету.

**Реализация предложения**
Создать новые иконки, и добавить в компонент.

**Comment by linturaven** [comment]
@gizeasy иконки: https://www.figma.com/design/SLc0YGhuDotve6MTCBHlGxDU/Consta-Graphics?node-id=718-31&t=xo6UXubWJEsGDJyG-1

**Comment by gizeasy** [comment]
@linturaven нужна иконка msg
