### ISSUE TITLE
Consta UI Kit компонент DatePicker

### ISSUE THREAD

**Issue by KseniyaPoli** [consta-design-system/uikit#3691]
**Описание бага**
При выборе даты в правом инпуте в датапикере type: date-time-range, такой же, как в левом инпуте -> время в левом инпуте сбрасывается к 00:00:00

**Как воспроизвести баг** (опционально)  
1. Выбрать дату и время (отличное от 00:00:00) в левом инпуте датапикера
2. Выбрать в правом инпуте такую же дату, как в левом (п.1)

https://github.com/consta-design-system/uikit/assets/110175697/b3e1c7ee-c535-4d64-9fce-05838613cd29

**Ожидаемое поведение** (опционально)  
Время в левом инпуте не сбрасывается к 00:00:00.

**Дополнительная информация**
совсем не очевидно и не удобно, что дата в левом инпуте сбрасывается, при выборе такой же даты в правом

**Comment by ZettZet** [comment]
**`note:`** На самом деле, оно не сбрасывает значение, а меняет местами, потому что случается ситуация, когда от > до. Это легко проверить, если сначала выставить до, а затем выставить еще большее от

**Comment by gizeasy** [comment]
@KseniyaPoli коментарий выше внес ясности, проблем больше нет?

**Comment by karpovfv** [comment]
@gizeasy привет! да, комментарий внёс ясность, спасибо. я думаю можно закрыть ишью
