### ISSUE TITLE
при нажатии на одно и то же поле даты DatePicker календарь чередует дату начала и окончания события

### ISSUE THREAD

**Issue by riginapapakhina** [consta-design-system/uikit#3703]
**Описание бага**

Компонент DatePicker не работает корректно и интуитивно понятно, отображая вместо этого дату начала и окончания в календаре попеременно

**Как воспроизвести баг** 
Шаг 1. Указать дату начала и окончания события так, чтобы они были в разных месяцах (например, июнь и август)
Шаг 2. Убрать фокус с полей ввода
Шаг 3. Нажать. на поле окончания события. Снять фокус. Нажать на него повторно. 

**Ожидаемое поведение** 
Выпадающий ниже календарь должен отобразить месяц окончания события во все разы

**Результат** 
Выпадающий ниже календарь отображает попеременно то месяц начала события, то его окончание

<img width="449" alt="Снимок экрана 2024-07-17 в 09 16 44" src="https://github.com/user-attachments/assets/6732b838-9728-4731-ae19-2180b9d453d0">
<img width="448" alt="Снимок экрана 2024-07-17 в 09 17 00" src="https://github.com/user-attachments/assets/06ca85a4-de27-4938-951e-bfcec3b45a68">

**Версия Consta Kit**
"4.23.1

**Параметры софта на компьютере:**

- ОС: macOS 14.4.1 (23E224)
- Браузер и его версия:
Yandex 24.1.5.827

**Comment by ZettZet** [comment]
**`note:`** На последней версии не повторяется, но там другой трабл: клики по любому из полей открывают дату начала
Непонятно, как патчить версию, которая больше не поддерживается

**Comment by gizeasy** [comment]
Фиксить старую версию мы не будем, обновляйтесь))
