### ISSUE TITLE
Combobox: исправление логики работы onFocus и onBlur

### ISSUE THREAD

**Issue by KlochkovIUS** [consta-design-system/uikit#3724]
**Описание бага**
1. Событие `onFocus` отрабатывет только если происходит фокус на `inputRef`, а не на весь ref компоненты
2. Метод `focus` ни на одном из ref компоненты не приводит к раскрытию списка. Если же на метод` onFocus` добавить изменение состояния `dropdownOpen` на `true`, то при клике на компонент будет происходить двойной вызов `onDropDownOpen` и выыпадающий список покажется и сразу закроется.
3. Метод `onBlur` вызывается при клике на кнопку разворачивания списка (со стрелочкой вверх/вниз)

**Как воспроизвести баг** (опционально)  
```
export function ComboboxExampleItems() {
  const [value, setValue] = useState<Item | null>();
  const [isOpened, setIsOpened] = useState<boolean>(false);
  const onDropDownOpen = (open: boolean) => {
    setIsOpened(open);
  };
  const inputRef = useRef(null);
  const ref = useRef(null);

  const inputRefFocus = () => {
    inputRef.current?.focus();
    console.log('inputRef focus');
  };

  const refFocus = () => {
    ref.current?.focus();
    console.log('ref focus');
  };

  const onFocus = () => {
    console.log('onFocus event');
    setIsOpened(true);
  };

  return (
    <Example col={1}>
      <Button onClick={inputRefFocus} label="inputRefFocus" />
      <Button onClick={refFocus} label="refFocus" />
      <Combobox
        ref={ref}
        inputRef={inputRef}
        items={items}
        value={value}
        onChange={setValue}
        placeholder="Выберите нужный элемент из списка"
        dropdownOpen={isOpened}
        onDropdownOpen={onDropDownOpen}
        onFocus={() => onFocus()}
        onBlur={() => console.log('onBlur event')}
      />
    </Example>
  );
}
```

**Ожидаемое поведение** (опционально)  
Возможность вызывать методы focus и blur для компоненты из внешнего источника.

> Если баг в коде, необходимо заполнить поля ниже ↧

**Версия Consta Kit**
5.6.1

**Параметры софта на компьютере:**

- ОС: Windows
- Браузер и его версия: тестировал на Chrome и FF

**Comment by gizeasy** [comment]
1) `onFocus` так и должен отрабатывать так как фокус должен быть по нативному контролу.
2) `focus` не должен вызывать раскрытие списка.

Как я понял вам нужно чтобы при первом рендере компонент был в фокусе и с раскрытым списком

У нас есть пример [Управление состоянием выподающего списка](https://consta.design/libs/uikit/components-combobox-stable/dev?hash=%D1%83%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D1%81%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D0%B5%D0%BC-%D0%B2%D1%8B%D0%BF%D0%BE%D0%B4%D0%B0%D1%8E%D1%89%D0%B5%D0%B3%D0%BE-%D1%81%D0%BF%D0%B8%D1%81%D0%BA%D0%B0)

для того чтобы список был раскрыт  первый рендер добавте в компонент

```tsx
 useEffect(() => {
    onDropdownOpen(true);
  }, []);
```

**Comment by KlochkovIUS** [comment]
Добрый день. Не совсем. У нас кейс внешнего управления контролом. Т.е. есть внешнее событие, которое вызывает фокус на контроле Combobox и делает его активным. При событии фокуса для комбобокса (та же проблема и датапикером) необходимо открыть выпадающаю часть для выбора. Есть возможность для метода фокус использовать любой из ref(инпута, всего компонента или внешней обертки).

**Comment by gizeasy** [comment]
Так вто мешает из примера взять код там как раз внешнее событие открытия, после которого фокус и изменение dropDownOpen = true

**Comment by gizeasy** [comment]
так можно решить вашу задачу

```tsx
type Item = {
  label: string;
  id: number;
};

const items: Item[] = [
  {
    label: 'Первый',
    id: 1,
  },
  {
    label: 'Второй',
    id: 2,
  },
  {
    label: 'Третий',
    id: 3,
  },
];

export function ComboboxExampleOpenByFocus() {
  const [value, setValue] = useState<Item | null>();
  const [isOpened, setIsOpened] = useFlag();

  const inputRef = useRef<HTMLInputElement>(null);
  const ref = useRef<HTMLDivElement>(null);

  const handleFocus = () => {
    inputRef.current?.focus();
  };

  // Запрещаем всплытие клика c input, чтобы предотвратить рассинхронизацию isOpened
  // с внутреннем состоянием раскрытия списка. Так как клик по компонету переключает сотояние,
  // а нам при фокусе нужно не переключекние (toggle) а включение (setTrue)
  useEffect(() => {
    if (inputRef.current) {
      inputRef.current.onclick = (e) => e.stopPropagation();
    }
  }, [inputRef.current]);

  return (
    <>
      <Button onClick={handleFocus} label="Програмный фокус на элемент" />
      <Combobox
        ref={ref}
        inputRef={inputRef}
        items={items}
        value={value}
        onChange={setValue}
        placeholder="Выберите нужный элемент из списка"
        dropdownOpen={isOpened}
        onDropdownOpen={setIsOpened.set}
        onFocus={setIsOpened.on}
      />
    </>
  );
}
```
