### ISSUE TITLE
DatePicker - проблема с обнулением значения

### ISSUE THREAD

**Issue by KetrosGleb** [consta-design-system/uikit#3733]
ссылка на [сандбокс](https://codesandbox.io/p/sandbox/vigorous-tom-7l8rs3?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzwmmpbz0006356llblpuef1%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzwmmpby0002356lp7zxwk4b%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzwmmpby0003356ljsmmyr9b%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzwmmpby0005356ljwivi5cq%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzwmmpby0002356lp7zxwk4b%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzwmmpby0001356l4xzwtbhl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clzwoi0d00002356lh785tpp0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A19%252C%2522startColumn%2522%253A30%252C%2522endLineNumber%2522%253A19%252C%2522endColumn%2522%253A30%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clzwmmpby0002356lp7zxwk4b%2522%252C%2522activeTabId%2522%253A%2522clzwoi0d00002356lh785tpp0%2522%257D%252C%2522clzwmmpby0005356ljwivi5cq%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzwmmpby0004356lxy7ghod3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%255D%252C%2522id%2522%253A%2522clzwmmpby0005356ljwivi5cq%2522%252C%2522activeTabId%2522%253A%2522clzwmmpby0004356lxy7ghod3%2522%257D%252C%2522clzwmmpby0003356ljsmmyr9b%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clzwmmpby0003356ljsmmyr9b%2522%257D%257D%252C%2522showDevtools%2522%253Afalse%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

приложение простое: 
    есть список юзеров, он хранится в файле data.ts
    есть компонент List, в котором мы мапимся по этим юзерам
    есть модальное окно, состоящее из двух полей - имени и даты

логика работы модального окна
1. если оно открыто для редактирования пользователя:
    в него сетаются значения, содержащиеся в объекте юзера.
    при отправке формы объект пользователя обновляется.

2. если открыто для создания пользователя:
    оно заполняется пустыми полями.
    при отправке создается новый пользователь.

проблема в том, что если выполнить последовательность действий:
    1. открыть редактирование пользователя.
    2. закрыть окно.
    3. открыть добавление пользователя.
то поле имени обнулится, а поле даты будет содержать null, но при этом в поле будет вписано значение.

как убедиться, что там null: 
    при отправке формы создастся пользователь без даты.
    и плюс по умолчанию выбранная дата в клендаре заполняется синим кружком, а если нажать на пое ввода, то синим кружком ничего не обводится, но в поле вписано значение
При этом если закрыть добавление и снова открыть то поле обнулится полностью

**Comment by ZettZet** [comment]
Похоже на проблему, описанную в #3645
