### ISSUE TITLE
Tabs: ошибка добавления табов при выбранном последнем табе

### ISSUE THREAD

**Issue by baevm** [consta-design-system/uikit#3734]
**Описание бага**
В компоненте Tabs при выборе последнего таба и добавления новых элементов в массив табов падает ошибка:
![image](https://github.com/user-attachments/assets/4478f10e-2676-4d32-bb16-ce68a7f99909)

![bug](https://github.com/user-attachments/assets/e2f90b0c-8683-4dbd-b3b2-d65bbccb491c)

**Как воспроизвести баг** (опционально)  
[https://codesandbox.io/p/sandbox/hungry-clarke-d2c2pt](url)
1. Выбрать последний таб и добавить элемент - падает ошибка
2. Выбрать любой таб кроме последнего и добавить элемент - ошибок нет, элемент добавляется и рендерится

**Ожидаемое поведение** (опционально)  
Элемент добавляется и рендерится

**Версия Consta Kit**
5.7.0

**Параметры софта на компьютере:**

- ОС: Windows 11
- Браузер и его версия: Chrome 127.0.6533.120

**Comment by ZettZet** [comment]
Забавный баг
Не сразу получилось воспроизвести, но как я понял, прикол в функции insert
К сожалению, до конца не разобрался, в чем прикол, но при добавлении в конец или начало такого не происходит)
