### ISSUE TITLE
table/components-table-stable: Странное поведения авторасчёта ширины

### ISSUE THREAD

**Issue by vindi-r** [consta-design-system/uikit#3798]
> Полные [правила оформления issue](https://consta-uikit.vercel.app/?path=/docs/common-develop-issues--page)

**Описание бага**
При первом рендере ширина столбцов в таблице выглядит хорошо. Но если контейнер сожмется-разозжмется, пока в нём таблица, то все столбцы будут минимально допустимого размера, а последний столбец огромный.
Может и не является прямо багом, а просто сайд-эффект от текущих расчётов. Но есть ощущение, что что-то идет не так.

[Ссылка на песочницу](https://codesandbox.io/p/sandbox/attachment-forked-fdr2jz?from-embed=&workspaceId=bdab6013-a03f-49df-9ab6-ec20160c9cd6)

**Как воспроизвести баг** (опционально)  
Зайти в песочницу, убедиться, что таблица рендерится на Х ширине адекватно
Нажать "CHANGE WIDTH", убедиться, что таблица ужалась в Y ширину
Нажать "CHANGE WIDTH" снова, чтобы ширина контейнера вернулась в X
Посмотреть на колонки и понять, что их конфигурация изменилась
Доп шаг: Нажать на кнопку "RESET ALL" чтобы компонент таблицы размонтировался-примонтировался снова. Так мы увидим конфигурацию колонок как было на старте приложения

**Ожидаемое поведение** (опционально)  
Таблица при неизменности настроек колонок и контента должна вести себя на ширине X всегда одинаково или схоже, но не должен быть дисбаланс размера колонок

> Если баг в коде, необходимо заполнить поля ниже ↧

**Версия Consta Kit**
Всё указано в package.json песочницы.
На момент составления issue было
- "@consta/uikit": "5.12.0",
- "@consta/table": "0.1.0-beta",

**Параметры софта на компьютере:**

- ОС: Windows 10
- Браузер и его версия: Chrome 129

**Дополнительная информация**
Еще в документации таблицы указан старый код, который берёт из UIKIT.
![image](https://github.com/user-attachments/assets/16057ed2-1e72-4358-a796-570c73a1ea51)

**Comment by gizeasy** [comment]
Думаю что можно на проекте при разных ширинах таблицы давать свои наборы ширин колонок. Тогда таких проблем не будет. 
Можно взять [useBreakpoints](https://consta.design/libs/uikit/hooks-usebreakpoints-stable) брать последний брейкпоинт с помощью [getLastPoint](https://consta.design/libs/uikit/hooks-usebreakpoints-stable?hash=getlastpoint)  

cсоставить карту ширин типа 
```js
const columnsWidthMap = {
 s: {
   name: {
     width: 200,
     minWidth: 180,
     maxWidth: 300,
   },
   profession: {
     width: 300,
     minWidth: 250,
     maxWidth: 400,
   }
 }
}
```

пример, в конкретном случает так избыточно делать, можно просто настроить минимумы и максимумы у колонок

https://codesandbox.io/p/sandbox/attachment-forked-q2dg5l?from-embed=&workspaceId=76c098e3-8906-478a-90e2-682ffb6f9ef0

так же есть проблема с шириной данных в ячейках, скоро волью исправления.

**Comment by gizeasy** [comment]
не верный импорт исправил

**Comment by gizeasy** [comment]
Создать пример таблицы с изменением ее ширины и подстройкой пож эту ширину колонок
