### ISSUE TITLE
MdxInformer: добавить компонент в consta/stand

### ISSUE THREAD

**Issue by gizeasy** [consta-design-system/uikit#3801]

**Comment by gizeasy** [comment]
@alyonurchick1 для каждого статуса определить заголовок и иконку

view = 'outline'
size = 'm'

**Comment by alyonurchick1** [comment]
@gizeasy предлагаю пока для всех статусов информера сделать одну иконку, но соответствующего цвета, например, если статус "внимание", то иконка красная. Для иконок предлагаю такие варианты из нашей библиотеки Graphics
![image](https://github.com/user-attachments/assets/253173dd-c050-4a3b-a7d7-a132c0ee06ff)
Всего выделяю 4 статуса у информера: 
- "Совет" (зеленый), 
- "Примечание" (синий)
- "Предупреждение" (желтый или оранжевый)
-  "Внимание" (красный)
Цвет и заголовок у информера заданы для каждого статуса соответственно, они не кастомизируются
