### ISSUE TITLE
Table: Не работает компонент после установки версии 0.3.0

### ISSUE THREAD

**Issue by INGWVR** [consta-design-system/uikit#3827]
**Описание бага**
После установки новой версии библиотеки Table сломались импорты компонентов.
В папке node_modules/@consta/table отсутствуют компоненты.

**Версия Consta Kit**
UIKIT 5.14.0
Table 0.3.0

**Comment by gizeasy** [comment]
@INGWVR исправил в [0.3.1](https://www.npmjs.com/package/@consta/table?activeTab=code)
