### ISSUE TITLE
Combobox: дать возможность скопировать выбранное значение

### ISSUE THREAD

**Issue by Mokudorudoku** [consta-design-system/uikit#3834]
**Описание фичи или улучшения**
В одиночном поле combobox нельзя скопировать текст

**Почему улучшение или фича необходима?**
Пользователь выбирает что то в поле и после идут поля текстового ввода, куда во многих случаях он вписывает тоже самое, что и в первом поле. Сейчас это приходится делать вручную, ведь из комбобокса нельзя скопировать уже выбранный текст. И придется добавлять кнопку копирования отдельно.

**Реализация предложения**
Что бы в комбобоксе можно было мышкой выделить текст. 

**Дополнительная информация**

**Comment by gizeasy** [comment]
решили не делать, быстро не сделать, приходится сильно усложнять логику
